### ISSUE TITLE
Windoze installation - 0.1.11

### ISSUE THREAD

**Issue by FedeMPouzols** [tomopy/tomopy#110]
Dear tomopy developers,

I'm trying to install tomopy using the 0.1.11 egg file for windows on a windows 7 machine. The installation went well and in principle tomopy works (io routines can load files, etc.). But I'm getting `function not found` exceptions for all the C functions exported by libtomopy. For example:

```
In [46]: cen = tomopy.find_center(sim, ang)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-ddd150e43270> in <module>()
----> 1 cen = tomopy.find_center(sim, ang)

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\recon\rotation.pyc in f
ind_center(tomo, theta, ind, emission, init, tol, mask, ratio)
    119
    120     hmin, hmax = _adjust_hist_limits(
--> 121         tomo[:, ind:ind + 1, :], theta, ind, mask, emission)
    122
    123     # Magic is ready to happen...

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\recon\rotation.pyc in _
adjust_hist_limits(tomo, theta, ind, mask, emission)
    132 def _adjust_hist_limits(tomo, theta, ind, mask, emission):
    133     # Make an initial reconstruction to adjust histogram limits.
--> 134     rec = recon(tomo, theta, emission=emission, algorithm='gridrec')
    135
    136     # Apply circular mask.

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\recon\algorithm.pyc in
recon(tomo, theta, center, emission, algorithm, init_recon, ncore, nchunk, **kwargs)
    239         init_recon)
    240     return _dist_recon(
--> 241         tomo, recon, _get_func(algorithm), args, kwargs, ncore, nchunk)
    242
    243

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\recon\algorithm.pyc in
_dist_recon(tomo, recon, algorithm, args, kwargs, ncore, nchunk)
    294         axis=0,
    295         ncore=ncore,
--> 296         nchunk=nchunk)
    297
    298

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in distr
ibute_jobs(arr, func, axis, args, kwargs, ncore, nchunk)
    135
    136     # Start processes.
--> 137     return _start_proc(arr, _args)
    138
    139

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in _star
t_proc(arr, args)
    155     if len(args)==1:
    156         init_shared(shared_arr)
--> 157         _arg_parser(args[0])
    158     else:
    159         with closing(

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in _arg_
parser(args)
    169 def _arg_parser(args):
    170     func = args[0]
--> 171     func(*args[1::])
    172
    173

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\extern.pyc in c_gr
idrec(*args)
    218     recon = mproc.SHARED_ARRAY
    219
--> 220     LIB_TOMOPY.gridrec.restype = dtype.as_c_void_p()
    221     LIB_TOMOPY.gridrec(
    222         dtype.as_c_float_p(tomo),

C:\local\Anaconda\lib\ctypes\__init__.pyc in __getattr__(self, name)
    376         if name.startswith('__') and name.endswith('__'):
    377             raise AttributeError(name)
--> 378         func = self.__getitem__(name)
    379         setattr(self, name, func)
    380         return func

C:\local\Anaconda\lib\ctypes\__init__.pyc in __getitem__(self, name_or_ordinal)
    381
    382     def __getitem__(self, name_or_ordinal):
--> 383         func = self._FuncPtr((name_or_ordinal, self))
    384         if not isinstance(name_or_ordinal, (int, long)):
    385             func.__name__ = name_or_ordinal

AttributeError: function 'gridrec' not found
```

The dll/pyd file seems to load correctly:
```
In [61]: LIB_TOMOPY=tomopy.util.extern.c_shared_lib('libtomopy')

In [62]: LIB_TOMOPY
Out[62]: <CDLL 'C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\lib\libtomopy.
pyd', handle 65d80000 at 14146cc0>
```

```
In [39]: ctypes.cdll.LoadLibrary('C:/local/Anaconda/lib/site-packages/tomopy-0.1.11-py2.7-win-amd64.
egg/lib/libtomopy.pyd')
Out[39]: <CDLL 'C:/local/Anaconda/lib/site-packages/tomopy-0.1.11-py2.7-win-amd64.egg/lib/libtomopy.
pyd', handle 65d80000 at 4729eb8>
```

But it behaves as if it was empty. `dir()` doesn't help much, and if I try to get functions by ordinals I can only get `LIB_TOMOPY[1]` which returns a large integer number.

Would anyone have any idea of what I might have done wrong?

I'm also wondering if this is supported at the moment. The documentation for the current (0.1.x) releases does not include any section about windows, as in old releases (http://tomopy.github.io/tomopy/install.html#windows-installation). I could send you a patch/PR with the windows instructions if that helps.

Thank you,

**Comment by dakefeng** [comment]
can you use other reconstruction algorithm instead of gridrec to check if
it works?

**Comment by FedeMPouzols** [comment]
None of them work. For example:
```
In [20]: tomo_rec = tomopy.recon(tomo, theta, center=512, algorithm='art')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-2e430a0395bf> in <module>()
----> 1 tomo_rec = tomopy.recon(tomo, theta, center=512, algorithm='art')

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\recon\algorithm.pyc in
recon(tomo, theta, center, emission, algorithm, init_recon, ncore, nchunk, **kwargs)
    239         init_recon)
    240     return _dist_recon(
--> 241         tomo, recon, _get_func(algorithm), args, kwargs, ncore, nchunk)
    242
    243

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\recon\algorithm.pyc in
_dist_recon(tomo, recon, algorithm, args, kwargs, ncore, nchunk)
    294         axis=0,
    295         ncore=ncore,
--> 296         nchunk=nchunk)
    297
    298

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in distr
ibute_jobs(arr, func, axis, args, kwargs, ncore, nchunk)
    135
    136     # Start processes.
--> 137     return _start_proc(arr, _args)
    138
    139

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in _star
t_proc(arr, args)
    152
    153 def _start_proc(arr, args):
--> 154     shared_arr = get_shared(arr)
    155     if len(args)==1:
    156         init_shared(shared_arr)

C:\local\Anaconda\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in get_s
hared(arr)
    173
    174 def get_shared(arr):
--> 175     shared_arr = mp.Array(ctypes.c_float, arr.size)
    176     shared_arr = _to_numpy_array(shared_arr, arr.shape)
    177     shared_arr[:] = arr

C:\local\Anaconda\lib\multiprocessing\__init__.pyc in Array(typecode_or_type, size_or_initializer, *
*kwds)
    258     '''
    259     from multiprocessing.sharedctypes import Array
--> 260     return Array(typecode_or_type, size_or_initializer, **kwds)
    261
    262 #

C:\local\Anaconda\lib\multiprocessing\sharedctypes.pyc in Array(typecode_or_type, size_or_initialize
r, **kwds)
    113     if kwds:
    114         raise ValueError('unrecognized keyword argument(s): %s' % kwds.keys())
--> 115     obj = RawArray(typecode_or_type, size_or_initializer)
    116     if lock is False:
    117         return obj

C:\local\Anaconda\lib\multiprocessing\sharedctypes.pyc in RawArray(typecode_or_type, size_or_initial
izer)
     80     type_ = typecode_to_type.get(typecode_or_type, typecode_or_type)
     81     if isinstance(size_or_initializer, (int, long)):
---> 82         type_ = type_ * size_or_initializer
     83         obj = _new_value(type_)
     84         ctypes.memset(ctypes.addressof(obj), 0, ctypes.sizeof(obj))

AttributeError: class must define a '_length_' attribute, which must be a positive integer
```

And if I try to use them as attributes of `LIB_TOMOPY` (`=tomopy.util.extern.c_shared_lib('libtomopy'`) I get a `NameError: name ... is not defined`.

**Comment by dgursoy** [comment]
Hi @FedeMPouzols, after we started using Conda install, we stopped fully supporting Win, but @aglowacki may help on this. I remember he did that in the past. 

It would be awesome if you can send a PR for Win instructions.

**Comment by dakefeng** [comment]
To me it seems art algorithm you were trying to call gives different error, not the function/name not found in the library.

Are you building tomopy from source code? Did you try use dumpbin to browse the functions exposed from dll library?

**Comment by FedeMPouzols** [comment]
I'm using the egg package from the APS jenkins. `dumpbin` doesn't find much in the dll, and dependency walker either. So it really looks like the algorithm functions are not in there and definitely not exported:

```
Dump of file D:\libtomopy.pyd

File Type: DLL

  Section contains the following exports for libtomopy.pyd

    00000000 characteristics
    5599F3F6 time date stamp Mon Jul 06 04:20:22 2015
        0.00 version
           1 ordinal base
           1 number of functions
           1 number of names

    ordinal hint RVA      name

          1    0 00001470 initlibtomopy

  Summary

        1000 .CRT
        2000 .bss
        1000 .data
        1000 .edata
        1000 .idata
        1000 .pdata
        2000 .rdata
        1000 .reloc
       15000 .text
        1000 .tls
        1000 .xdata
```

**Comment by dakefeng** [comment]
Anything else other than libtomopy.pyd? are there something like libtomopy.dll?

Can you try build the source under windows?

**Comment by aglowacki** [comment]
Can you post how you installed TomoPy on Windows, or can you post the code you are trying to run with TomoPy?

**Comment by michael-sutherland** [comment]
Any progress here?  I'm having the same issue when trying to run tomopy under Anaconda in Windows.

**Comment by aglowacki** [comment]
@michael-sutherland   Can you post how you installed TomoPy on Windows, or can you post the code you are trying to run with TomoPy?

**Comment by michael-sutherland** [comment]
I'm on Windows 7.  I installed anaconda 2.2.0.  Then I did an pip install of pyWavelets.  Then I did an easy_install of tomopy:

>\>c:\Anaconda\Scripts\easy_install.exe tomopy-0.1.9-py2.7-win-amd64.egg
c:\Anaconda\lib\site-packages\setuptools-14.3-py2.7.egg\pkg_resources\__init__.py:2512:PEP440Warning: 'llvmlite (0.2.2-1-gbcb15be)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Processing tomopy-0.1.9-py2.7-win-amd64.egg
creating c:\anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg
Extracting tomopy-0.1.9-py2.7-win-amd64.egg to c:\anaconda\lib\site-packages
Adding tomopy 0.1.9 to easy-install.pth file
>
>Installed c:\anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg
Processing dependencies for tomopy==0.1.9
Finished processing dependencies for tomopy==0.1.9

>\>python -c "import tomopy"
WARNING:tomopy.io.reader:spefile module not found
WARNING:tomopy.io.reader:netCDF4 module not found
WARNING:tomopy.io.reader:EdfFile module not found


I'm assuming the warnings are normal if you don't have the packages installed to support those file types.  If I try to run some sample code, I get a failure:

In [1]: %paste
import tomopy
from tomopy.recon.algorithm import recon
import numpy as np
import h5py

\# Inputs:
\#----------------------------------------------------------------------------------

file_name = 'data.h5'
theta_start = 20
theta_end = 160
\#----------------------------------------------------------------------------------

f = h5py.File(file_name, "r+")

normalized = f['exchange/normalized']

\# half of normalized
normalized = normalized[::2,::2,::2]

\# Set data collection angles as equally spaced between start and end
theta  = tomopy.angles(normalized.shape[0], theta_start, theta_end)

\# Find rotation center.
rot_center = tomopy.find_center(normalized, theta, emission=False, tol=0.5)
print "Calculated rotation center: ", rot_center
\## -- End pasted text --
WARNING:tomopy.io.reader:spefile module not found
WARNING:tomopy.io.reader:netCDF4 module not found
WARNING:tomopy.io.reader:EdfFile module not found
\---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-a701f61aaa5f> in <module>()
     63
     64 # Find rotation center.
---> 65 rot_center = tomopy.find_center(normalized, theta, emission=False, tol=0.5)
     66 print "Calculated rotation center: ", rot_center
     67

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\recon\rotation.pyc in find_center(tom
, emission, init, tol, mask, ratio)
    119
    120     hmin, hmax = _adjust_hist_limits(
--> 121         tomo[:, ind:ind + 1, :], theta, ind, mask, emission)
    122
    123     # Magic is ready to happen...

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\recon\rotation.pyc in _adjust_hist_li
eta, ind, mask, emission)
    132 def _adjust_hist_limits(tomo, theta, ind, mask, emission):
    133     # Make an initial reconstruction to adjust histogram limits.
--> 134     rec = recon(tomo, theta, emission=emission, algorithm='gridrec')
    135
    136     # Apply circular mask.

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\recon\algorithm.pyc in recon(tomo, th
emission, algorithm, init_recon, ncore, nchunk, **kwargs)
    239         init_recon)
    240     return _dist_recon(
--> 241         tomo, recon, _get_func(algorithm), args, kwargs, ncore, nchunk)
    242
    243

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\recon\algorithm.pyc in _dist_recon(to
gorithm, args, kwargs, ncore, nchunk)
    294         axis=0,
    295         ncore=ncore,
--> 296         nchunk=nchunk)
    297
    298

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in distribute_jobs(arr
 args, kwargs, ncore, nchunk)
    135
    136     # Start processes.
--> 137     return _start_proc(arr, _args)
    138
    139

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in _start_proc(arr, ar
    155     if len(args)==1:
    156         init_shared(shared_arr)
--> 157         _arg_parser(args[0])
    158     else:
    159         with closing(

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\util\mproc.pyc in _arg_parser(args)
    169 def _arg_parser(args):
    170     func = args[0]
--> 171     func(*args[1::])
    172
    173

c:\Anaconda\lib\site-packages\tomopy-0.1.9-py2.7-win-amd64.egg\tomopy\util\extern.pyc in c_gridrec(*args)
    218     recon = mproc.SHARED_ARRAY
    219
--> 220     LIB_TOMOPY.gridrec.restype = dtype.as_c_void_p()
    221     LIB_TOMOPY.gridrec(
    222         dtype.as_c_float_p(tomo),

c:\Anaconda\lib\ctypes\__init__.pyc in __getattr__(self, name)
    376         if name.startswith('__') and name.endswith('__'):
    377             raise AttributeError(name)
--> 378         func = self.__getitem__(name)
    379         setattr(self, name, func)
    380         return func

c:\Anaconda\lib\ctypes\__init__.pyc in __getitem__(self, name_or_ordinal)
    381
    382     def __getitem__(self, name_or_ordinal):
--> 383         func = self._FuncPtr((name_or_ordinal, self))
    384         if not isinstance(name_or_ordinal, (int, long)):
    385             func.__name__ = name_or_ordinal

AttributeError: function 'gridrec' not found

In [2]:

**Comment by michael-sutherland** [comment]
I tried to build tomopy for windows from source using MSVC 2008 for Python 2.7, but that fails because of some unix specific libraries (stdbool.h, sys/time.h, and then some other errors...).  Also, it doesn't have C99 support.  As far as I understand, I can't use the newer version of MSVC with Python 2.7.  Is MinGW being used to compile tomopy on Windows?

**Comment by dakefeng** [comment]
Try mingw instead of msvc

**Comment by aglowacki** [comment]
Can you try removing tomopy and installing a newer version. You can download the egg on our build server:
https://jenkins.aps.anl.gov/view/Python/job/Tomopy_trunk/ws/dist/tomopy-0.1.11-py2.7-win-amd64.egg

Same for the install:
easy_install tomopy-0.1.11-py2.7-win-amd64.egg

And try again. Also what sample are you trying to run? I tried this one 
http://tomopy.readthedocs.org/en/latest/source/demo/doc.demo.rec_aps_32id_full.html
with a dataset I have and it completed without errors. I only got the warning about missing spefile, netcdf4, and Edffile.

**Comment by michael-sutherland** [comment]
I installed the new egg (tomopy 0.1.11) and am now having a different issue.  It appears that the recon function is spawning the various processes and it returns a numpy array; however, it returns faster than I would expect and the reconstruction is all 1e-6 in value.  Even for the sample reconstruction snippet that is given in the code (see below).  I think it is initializing the output volume (which appears to be a shared memory object) and then returning that volume without processing it.  

BTW, there is another Windows issue.  64-bit Python on 64-bit windows defines the Python int type as 32-bit.  Normally this wouldn't matter much except to slow things down a bit when numbers get big and it has to convert to the Python long type.  However, for shared memory arrays, it appears that the size limit is set to the max int size.  My single field of view tomography easily surpasses this limit.

The line in question:
c:\Anaconda\lib\multiprocessing\heap.pyc in __init__(self, size)
    240
    241     def __init__(self, size):
--> 242         assert 0 <= size < sys.maxint
    243         block = BufferWrapper._heap.malloc(size)
    244         self._state = (block, size)

I'm going to switch over to Linux to see if I have better luck there.  It would take a bit of effort to get MinGW installed.  Is there anything else you'd like me to test on Windows while I still have it all set up?

Test Snippet (rec is all 1E-6):

import tomopy
obj = tomopy.shepp3d() # Generate an object.
ang = tomopy.angles(180) # Generate uniformly spaced tilt angles.
sim = tomopy.project(obj, ang) # Calculate projections.
# Reconstruct object:
rec = tomopy.recon(sim, ang, algorithm=tomopy.astra,
      options={'method':'SART', 'num_iter':10*180,
      'proj_type':'linear',
      'extra_options':{'MinConstraint':0}})

**Comment by tomopy** [comment]
Sorry @michael-sutherland, I am not expert in Win issues, and relying on others in the solution. Have you had success on Linux?

**Comment by FedeMPouzols** [comment]
I came back to this and tried again with the egg that I got this morning from the APS jenkins (build #372) it now works but I'm finding similar issues as @michael-sutherland reported. The output from the recon algorithms is always a flat 1e-6 array. Previous issues with the DLL must have been a glitch. Now it is definitely starting the recon algorithms, allocating memory and doing some calculations, but the result is not produced and/or returned properly.

I'm also getting the issue with the int32 size limit, as @michael-sutherland : 
```
C:\local\Anaconda\lib\multiprocessing\heap.pyc in __init__(self, size)
    240
    241     def __init__(self, size):
--> 242         assert 0 <= size < sys.maxint
    243         block = BufferWrapper._heap.malloc(size)
    244         self._state = (block, size)
```
This implies that you cannot run recon if you have for example 1Kx1K projections as the output array would be already above the int32 limit.

**Comment by FedeMPouzols** [comment]
I forgot to mention that on linux it all seems to work perfectly, both with the Anaconda packages and building from sources.

**Comment by FedeMPouzols** [comment]
I've now tried installing tomopy from sources compiled with Mingw (TDM-GCC 64 bits). It installs happily on the Anaconda Python for windows, and you can import it and use it correctly. All fine, except that all the reconstruction algorithms return a 1e-6 flat array. The pyd extension compiles without any warnings or any bad signs.

Does anyone have any hints? Is it working for anyone on windows? Have there been any recent changes to the shared arrays / cdll stuff that might be behind this issue?

**Comment by GoHoHa** [comment]
I want to use tomopy under Win7 64bit with a portable WinPython 2.7. I got it running but all reconstructed values are 1e-6 too. Unfortunately the system were I want to use tomopy can not be converted to a *nix machine, so please help us users to get it run at Win again.

**Comment by GoHoHa** [comment]
By the way,to install tomopy I used the egg from [the APS Jenkins server](https://jenkins.aps.anl.gov/view/Python/job/Tomopy_trunk/ws/dist/tomopy-0.1.11-py2.7-win-amd64.egg).

**Comment by AaronBM** [comment]
**I would also like to vote for continued support of a windows release.**

I'm new to tomopy but am hoping to contribute.  I'll add to this discussion since it seems relevant but can move this to a new thread if need be.

I would prefer to work in the windows environment since I have more familiarity with it.  I have access to a VM install of Fedora 22, but haven't had any success running tomopy there yet either.    
In the meantime this is the progress I've made using the help provided on  *http://tomopy.github.io/tomopy/install.html#windows-installation*  I had followed these  instructions referencing 0.0.3 and tried using both 0.1.10 and 0.1.11.  I've attached the the progress I made here...

**Anaconda Command Window**
*C:\Users\...\AppData\Local\Continuum\Anaconda3>easy_install tomopy-0.1.11-py2.7-win-amd64.egg*
Processing tomopy-0.1.11-py2.7-win-amd64.egg
creating c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg
Extracting tomopy-0.1.11-py2.7-win-amd64.egg to c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages
Adding tomopy 0.1.11 to easy-install.pth file

Installed c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages\tomopy-0.1.11-py2.7-win-amd64.egg
Processing dependencies for tomopy==0.1.11
Searching for tomopy==0.1.11
Reading https://pypi.python.org/simple/tomopy/
Couldn't find index page for 'tomopy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for tomopy==0.1.11
error: Could not find suitable distribution for Requirement.parse('tomopy==0.1.11')

*C:\Users\...\AppData\Local\Continuum\Anaconda3>easy_install tomopy-0.1.10-py2.7-win-amd64.egg*
Processing tomopy-0.1.10-py2.7-win-amd64.egg
creating c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages\tomopy-0.1.10-py2.7-win-amd64.egg
Extracting tomopy-0.1.10-py2.7-win-amd64.egg to c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages
Removing tomopy 0.1.11 from easy-install.pth file
Adding tomopy 0.1.10 to easy-install.pth file

Installed c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages\tomopy-0.1.10-py2.7-win-amd64.egg
Processing dependencies for tomopy==0.1.10
Searching for tomopy==0.1.10
Reading https://pypi.python.org/simple/tomopy/
Couldn't find index page for 'tomopy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for tomopy==0.1.10
error: Could not find suitable distribution for Requirement.parse('tomopy==0.1.10')
**End Anaconda Command Window**

This is the result I get when checking the install in a new command window after the .egg easy install.  

**Anaconda Command Window**

*C:\Users\...\AppData\Local\Continuum\Anaconda3>python -c "import tomopy"*
WARNING:tomopy.io.writer:dxfile module not found
WARNING:tomopy.io.reader:spefile module not found
WARNING:tomopy.io.reader:netCDF4 module not found
WARNING:tomopy.io.reader:EdfFile module not found
**End Anaconda Command Window**


If I look for https://pypi.python.org/simple/tomopy/ I find an error.   However I still see it in the parent simple list.

**Comment by dgursoy** [comment]
Can anyone try the image at Docker Hub on a Win machine to see if it works:
```
https://hub.docker.com/r/dgursoy/tomopy
```

**Comment by gazzar** [comment]
I just tried it and the image appears to work. I was able to run the image and run a shell, run python and import tomopy. I didn't try any further than that as it's my first time trying to run Docker on Windows and I ran into all sorts of Docker-related problems and difficulties (unrelated to tomopy) which have temporarily overflowed my frustration reservoir. Let me know if there's anything specific you'd like me to test.

**Comment by dgursoy** [comment]
@gazzar: Thanks Gary. I was thinking to use Docker as an easy support for Win machines. But I have no Docker experience before so any comments or opinions are welcomed. What are the common problems that you can expect to see related to that project?

**Comment by gazzar** [comment]
I would say it could be a beneficial way to proceed for those people who can containerize their whole workflow. I'm not sure it will be helpful for me because my interest in tomopy is as a library. I'll try to list some problems I foresee. My initial experience getting Docker running on Windows (Win 7-64 Enterprise) wasn't great, so that might be an impediment. As I said, the big problem for me personally is that my interest in tomopy is as a library and that leaves me two possible options if I want to use a Dockerized-version of tomopy; move the rest of my code and development into the container or try to expose the bits of the API I want through some REST interface and add a lot of extra file i/o to get my data in and out. Of these, taking the first option seems more sensible but in that case I might as well just run a full Linux in a VM so I can set up a nice development environment. For the ASTRA toolbox support, I haven't looked into GPU support from containers; I'm told the latest version of CUDA and Virtualbox do support access to the GPU, but I haven't tried this, and I don't know if that extends to Docker.

**Comment by gazzar** [comment]
I was just chatting with someone (Robbie Clarken) about this and he suggested another way to interface with the containerized version. His idea was to run redis inside the container and access the tomopy API through python-rq. If this works, it sounds like a better solution than either of the options I thought of.

**Comment by dgursoy** [comment]
I now understand your pain. I agree that we can search and find more elegant ways of doing this, but at this point I would keep the Docker image as a quick fix for Win users.
