### ISSUE TITLE
Wrong default file name extension in tomopy.io.write_hdf5?

### ISSUE THREAD

**Issue by buzmakov** [tomopy/tomopy#111]
Hi, 

The tomopy.io.write_hdf5 parameter **fname** have dafault value 'tmp/data.**tif**f'.
https://github.com/tomopy/tomopy/blob/master/tomopy/io/writer.py#L157

It is seems that the more suitable default name for HDF5 file will 'tmp/data.**hdf5**' ?

**Comment by dgursoy** [comment]
Makes sense. Corrected.
