### ISSUE TITLE
HDF group/dataset names with Windows installation

### ISSUE THREAD

**Issue by michael-sutherland** [tomopy/tomopy#113]
The code in tomopy/io/exchange.py uses os.path.join to create paths into an HDF5 file.  On windows this will produce something like the following:

os.path.join('exchange', 'data') -> 'exchange\\data'

This is an invalid path for HDF5 (or at least h5py).  The correct path name is 'exchange/data'.  I would suggest not using the os.path.join function for something that isn't an os path.  Instead, you could use:

"/".join()

This will work for all operating systems.

**Comment by prjemian** [comment]
Agreed.  The os.path.* methods should only be used with files.

To create HDF5 paths within an HDF5 file, use like this:
'/'.join(['exchange', 'data'])

**Comment by dgursoy** [comment]
Corrected in #116. Thanks for pointing this out.
