### ISSUE TITLE
Multiprocessing error on win 7 64bit

### ISSUE THREAD

**Issue by bohell** [tomopy/tomopy#114]
When running the code, keep showing the following error message:

            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

My os is win 7 64bit, I installed Anaconda, I googled the error information, it seems I need to add 

    if __name__ == '__main__':
                    freeze_support()

to somewhere, does anyone know how to fix this? Thanks.

**Comment by dakefeng** [comment]
it should be where your program starts. typically it is at the bottom of
python source code.

**Comment by aglowacki** [comment]
For Windows you need to add :
import tomopy

if __name__ == '__main__':
    #rest of the code here
