### ISSUE TITLE
possible bug found in ospml algorithms.

### ISSUE THREAD

**Issue by dakefeng** [tomopy/tomopy#115]
In case dx can be divided by the block_number without remainder, there will be no last block needing to be dealt with. But in the source code, weighting the recon result will still execute. 

It is not a function or program bug. It could be just deviation from algorithm, or even the algorithm demands it to be like that.

The hardware acceleration strictly follows the source code interpretation. So that the test results agree.

Should it need change, please do inform so that I can update the hardware implementations.

BTW, tomopy_peri now support both Xeon Phi co-processor and nVidia GPGPU unit.

**Comment by tomopy** [comment]
Hi @dakefeng, which line of which script are you referring to? ...and thanks for the implementations. I am looking forward to compare it when we have the new machines.

**Comment by dakefeng** [comment]
In ospml_quad.c

line 104, subset_ind2 could be zero at the last block indicating there is no subset to be dealt with at the last block, so that the loop at line 113 will not do anything. But from line 184, right after the loop, it will still weight the whole recon again.

Similar thing in ospml_hybrid.c

**Comment by tomopy** [comment]
Ah I see now your point. The ordered subset part can be optimized further to correct for these things. But in this version I assume that the ``number of projection % number of subsets = 0``  and should be arranged before you run. Though it would be nice to correct this at some point, it is rather harmless.

**Comment by dakefeng** [comment]
Well, it is not only an optimization issue. I found this is because that my implementation in hardware parallel correct all blocks and then the result doesn’t agree.
The extra weighting recon modifies the dataset on the last projection % num_of_subsets = 0. 
I have to force hardware to weight the recon even there is no last_block to be dealt with, so that the result agrees.

**Comment by tomopy** [comment]
For now a basic if statement may solve that problem I guess, right?

**Comment by dakefeng** [comment]
correct. and regenerate the test data set for these two algorithms.

**Comment by dgursoy** [comment]
The arguments for recon algorithms are slightly changed with the newest PRs. ```emission``` is now removed from arguments, and ```sinogram_order``` is added as a new feature, where users can select if data is stored in sinogram order or in projection order. Could you check if all is working correctly with the peri plugin?
