### ISSUE TITLE
All output is 0 after reconstruction in Win 7

### ISSUE THREAD

**Issue by bohell** [tomopy/tomopy#125]
Hi, I encountered a strange issue when using tomopy. (win 7, anaconda, tomopy-0.1.11)
When I run the code, no matter what data I'm using, the output is always 0, even using the test data. 
When running there is no error, only a few warning, some module not found.
Any one knows how to deal with this problem? Thanks.

![tomopy](https://cloud.githubusercontent.com/assets/13590177/9826354/264a018c-589f-11e5-8b7c-01562a02c941.jpg)
![tomopy2](https://cloud.githubusercontent.com/assets/13590177/9826355/264c82ae-589f-11e5-9331-49fd650ebd6e.jpg)

**Comment by bohell** [comment]
By the way, I used all algorithms, the result is the same, all 0.

**Comment by GoHoHa** [comment]
Same problem here. I use Win7 64bit and WinPython 2.7. All reconstructed values are 1e-6. Same as [issue #110](https://github.com/tomopy/tomopy/issues/110)

**Comment by dgursoy** [comment]
merged with #110
