### ISSUE TITLE
Gridrec segfault when running with specific number of cores

### ISSUE THREAD

**Issue by dmpelt** [tomopy/tomopy#127]
Using both the latest conda build of tomopy (0.1.11) and the latest git master, I get a segfault when running `gridrec` with a specific number of cores. The result is the problem of #120, where you have to kill the parent python process in order to regain control of the terminal. The following script shows the problem on my machines:

    import tomopy
    import numpy as np
    ang = tomopy.angles(256)
    prj = np.zeros((256,100,256),dtype=np.float32)
    tomopy.recon(prj,ang,algorithm='gridrec',ncore=1) # works
    tomopy.recon(prj,ang,algorithm='gridrec',ncore=2) # works
    tomopy.recon(prj,ang,algorithm='gridrec',ncore=5) # works
    tomopy.recon(prj,ang,algorithm='gridrec',ncore=3) # works
    tomopy.recon(prj,ang,algorithm='gridrec',ncore=8) # hangs

The following `gdb` log shows the location of the segfault:

    #0  0x00007f7198ed1435 in gridrec (data=0x7f71d71de000, dx=256, dy=100, dz=256, center=0x7f7199213aa4, theta=0x0, recon=0x7f71910cf000, ngridx=256, ngridy=256, fname=0x1b62eb0 "shepp", istart=91, iend=100)
    at src/gridrec.c:311

Maybe something goes wrong earlier, since `theta` is already `0x0` in the function call. 

Some other combinations of numbers of angles, slices, detectors, and cores segfault as well, but many others work fine. I did not find a clear pattern yet...

**Comment by dgursoy** [comment]
This more seems to be a bug in python multiprocessing, though not yet clear. @aglowacki is investigating this and may have some better insights about the possible source.

**Comment by dmpelt** [comment]
I tried removing the multiprocessing parts to test it out, but the segfault kept appearing. 

In the end, I may have found a possible cause for this particular segfault, and why it only happens for specific number of cores and slices! It turns out that the segfault only happens when the final chunk starts with an odd slice index.

I submitted a PR with a fix in #129.

**Comment by dgursoy** [comment]
I assume this is now fixed.
