### ISSUE TITLE
different results from legacy and current tomopy

### ISSUE THREAD

**Issue by rh66** [tomopy/tomopy#132]
Just start to try tomopy in conda, and I get different results by using current tomopy in conda and legacy tomopy. I probably just don't know some fundamentals and therefore make the mistake. Hope someone can point out what I did wrong here.
I tested by assuming an object of round disc with intensity of 1 and radius of 200, with image width of 800. All the projections will be same since the rotation is centered at disc center. I generated projections, reconstructed it and plot the cross-section through disc center, as following:

```
data2=np.zeros((1200, 1, 800))
for i in range(400):
    data2[:, 0, i+200]=2*(200**2-(199.5-i)**2)**0.5
angle2=np.linspace(0,180.0,1200)*np.pi/180.0
rec2 = tomopy.recon(data2, angle2, center=399.5, algorithm='gridrec')
plt.plot(rec2[0,400,:])
plt.show()
```

The result is the left plot of attached image. If I use legacy tomopy, the result is shown on the right of attached image. The right one is my original object. And the code of using legacy tomopy is:

```
data2=np.zeros((1200, 1, 800))
for i in range(400):
    data2[:, 0, i+200]=2*(200**2-(199.5-i)**2)**0.5
dark = np.zeros((1, 800), dtype=float)
white = np.ones((1, 800), dtype=float)
theta = np.linspace(0, 180, 1200)
d = tomopy.xtomo_dataset(log='debug')
d.dataset(data2, white, dark, theta)
d.center=399.5
d.gridrec(emission=True)
```

Thank you for your attention and help.
Rong

![reconstructioncompare](https://cloud.githubusercontent.com/assets/6943918/10804812/e6103476-7d9f-11e5-99e7-e544c710f111.jpeg)

**Comment by dgursoy** [comment]
It is likely because of different filtering, and interpolation values. I will check what the default values were before and after. Otherwise the algorithm is unchanged and should produce the same results.

**Comment by dgursoy** [comment]
Tried with current version with the following code, and got some interesting results. 

- Top plot: Gridrec reconstruction of Shepp-Logan phantom. 
- Middle plot: Gridrec reconstruction values multiplied with two
- Bottom plot: Block-ART Iterative reconstruction plot

```Gridrec``` result seems to be multiplied by two. @michael-sutherland any comments or ideas why this may have happened?

```
import tomopy
import numpy as np

obj = tomopy.shepp2d(128)
ang = tomopy.angles(180)
prj = tomopy.project(obj, ang)

rec1 = tomopy.recon(prj, ang, 
    algorithm='gridrec', 
    filter_name='ramlak',
    num_gridx=128,
    num_gridy=128)

rec2 = tomopy.recon(prj, ang, 
    algorithm='bart',
    num_iter=40,
    num_gridx=128,
    num_gridy=128,
    num_block=10)

import matplotlib.pylab as plt

plt.subplot(1, 3, 1)
plt.plot(obj[0, 64, :], 'r', linewidth=3)
plt.plot(rec1[0, 64, :], 'b', linewidth=2)
plt.title('Gridrec')
plt.grid()
plt.axis('tight')

plt.subplot(1, 3, 2)
plt.plot(obj[0, 64, :], 'r', linewidth=3)
plt.plot(2*rec1[0, 64, :], 'b', linewidth=2)
plt.title('Gridrec multiplied by 2')
plt.grid()
plt.axis('tight')

plt.subplot(1, 3, 3)
plt.plot(obj[0, 64, :], 'r', linewidth=3)
plt.plot(rec2[0, 64, :], 'b', linewidth=2)
plt.title('BART')
plt.grid()
plt.axis('tight')

plt.show()
```

...and here's the output image:

![figure_1](https://cloud.githubusercontent.com/assets/1311208/14360958/51d59a78-fcbe-11e5-8dbd-e43ba81f0a72.png)

**Comment by michael-sutherland** [comment]
I looked through the changes to gridrec, but nothing stands out.  I'll need to go through the code a bit more to try to figure out why the 2x change.

**Comment by dgursoy** [comment]
This could be because of filters. Some can be from -0.5 to 0.5. Need to check.

**Comment by michael-sutherland** [comment]
Was this issue ever resolved?

**Comment by dgursoy** [comment]
FBP is actually BP without a filter implemented. So it makes sense them to be different. However, Gridrec values should I think be multiplied by 2 for a true quantification.

**Comment by michael-sutherland** [comment]
I think this issue was fixed, correct?  Can we close it?
