### ISSUE TITLE
Fresh Start with Old Data

### ISSUE THREAD

**Issue by AaronBM** [tomopy/tomopy#135]
I'm looking for advice on processing some data collected in March of this year.  I have a platforms I can choose from to process the data.

My primary computer is a Win7 machine with 32gb RAM and a dual Xeon E5 processors.  I know windows isn't supported but I can run a Fedora 22 virtual environment.  I have no administrator control of this computer and will need to make requests for significant software changes.  

My second option is a AMD FX-4130 with 32gb RAM.  It has Win10 and Fedora 22 available.  I can install any operating system on this computer

My third (and only option while on travel), is using an Intel Centrino with 8gb RAM.  It also was Win10 but can be re-purposed with any operating system.

My fourth option is to borrow a MacBook Pro with OSX 10.9.5 with 16gb RAM.

**What platform and OS combo has been used the most and/or has the most support?**

My goal is to dedicate one or all of these computers to reconstructing about 30 scans or 5 sample pieces.  My ideal deadline is to process this data within the next week.  How feasible is this?

**Comment by dgursoy** [comment]
Hi @AaronBM, I try to support only Linux and Mac installations. But for now please don't use latest Mac OS. I heard from some users that El Capitan can cause some issues, and I didn't have a chance to look into that. 

Also if you have micro-CT datasets of large sizes, I recommend upgrading your RAMs to 128GB or higher if possible (otherwise stick with the 32GB machines). Either case 30 scans can be processed within the deadline.

**Comment by AaronBM** [comment]
Hi @dgursoy!.   I'm on travel for the next couple days so I only have limited processing power.  Is it possible for me to scale down the chunk size and run at all?  I'm still looking to ensure that I have a complete procedure even if it takes overnight.   Once I have that I can move to a higher power machine when I get back to my office.

I'm jumping into the tail end of a program without full knowledge transfer from the previous user.  I know I need to do some trial and error to figure it all out.

**Comment by decarlof** [comment]
Do you have a copy of your raw data on petrel? If so i can send you batch that will work on your machine, or if you have fast network do the reconstruction here for you to download

F

Sent by T-mobile

**Comment by xianghuix** [comment]
Can I ask where your data come from? Where did you get your reconstruction script?

Thanks,

Xianghui
________________________________

**Comment by AaronBM** [comment]
I don't know if there are any other copies of raw data.   I only have it stored as several .hdf files on some external drives.  Each file is ~16gb.  I'm assuming this is the standard raw format. Please correct me if I'm wrong.

**Comment by xianghuix** [comment]
Is your data from 2-BM?

Thanks,

Xianghui
________________________________

**Comment by AaronBM** [comment]
Hi @xianghuix !  I’m working with Aaron Greco and reconstructing bearing samples to show any sub-surface cracks.   From the date on the code I’m guessing he was in APS sometime in March this year.  I have also seen mention of “building 431 sector 1-4 and I think 2BMB” in an email.  Does that help at all?   I'm trying to pick up where one of his students left off.

**Comment by xianghuix** [comment]
I see. I remember I suggest one of your fellows to build a Linux computer. 32GB RAM is okay but you need to use small chunk size. The reconstruction may take long time. I thought most data has been already reconstructed with the beamline computer.

Thanks,

Xianghui
________________________________

**Comment by AaronBM** [comment]
Hi @dgursoy @xianghuix,    I've made some progress finding a stable computer/environment but have come to a new point I need help with.


**Terminal** 
[tomtom@localhost APS]$ python Aaron_2015_03.py
Traceback (most recent call last):
  File "Aaron_2015_03.py", line 21, in <module>
    d = tomopy.xtomo_dataset(log='debug')
AttributeError: 'module' object has no attribute 'xtomo_dataset'
**End Terminal**


What would cause this "xtomo_dataset' error?   Am I not defining or referencing the dataset correctly in the existing script?

**Comment by decarlof** [comment]
@AaronBM @dgursoy @xianghuix 

Aaron,

I think the script you are using is for an old version of tomopy.
To read 2-BM data you should call read_aps_2bm.

can you share the full Aaron_2015_03.py ?

**Comment by AaronBM** [comment]
I will send this to you via email shortly.

**Comment by AaronBM** [comment]
@decarlof ,  I was able to incorporate the changes you sent with my existing file.   I've run a few iterations of sino_start, sino_end, chuck_size, and margin_slices to just test the script.  I have the script running in an older i5-750 with 16gb RAM in a Fedora 22 environment and also a MacBook Pro i7-2820 with 16gb RAM in OSX 10.9.5.  I'm able to run without errors and generate 100 tiff images with the following settings.  

best_center=1275.5
sino_start = 1200
sino_end = 1300

offset = 0
total_num_slices = 2000
chunk_size =10 
margin_slices = 5


I can understand that sino_start/end is related to how many tiff slices I generate.  How do I choose the correct starting point? 

How does sino_start/end relate to the number of slices?

How does margin_slices relate to chuck_size?

What does best center mean?

Is there a section in the documentation that will explain this in more detail?

**Comment by decarlof** [comment]
@AaronBM Great!

You can find the tomopy documentation at http://tomopy.readthedocs.org
there are examples for 2-BM and 32-ID. The sino start/end refers to the slice block you want to reconstruct. A slice correspond to a CCD raw (zero being the top). You can reconstruct them all or you can look at a projection image and discard the one where there is no sample (generally the top) or the sample holder is blocking the view (generally the bottom).

If you run on a limited memory machine you can also customize the 
example at http://tomopy.readthedocs.org/en/latest/source/demo/doc.demo.rec_aps_32id_chunk.html

**Comment by AaronBM** [comment]
I have set up a Dual-Xeon 28gb RAM Fedora 22 virtual machine to process the files over the weekend.   It seem to be running without any trouble now.   If all things go well I think we can close the thread next week.

**Comment by dgursoy** [comment]
I assume this is resolved and I close this.
