### ISSUE TITLE
Cannot allocate memory error

### ISSUE THREAD

**Issue by jangarrevoet** [tomopy/tomopy#143]
Hi Doha,

When reconstructing a dataset from a PCO 4000 (4008 by 2672 pixels) with 100 bright fields, 100 dark fields, and only 721 projections (16 bit tiff files), I get a Cannot allocate memory error.
I reduced the script to the bare minimum, reading in the files, normalising them, reconstruct using gridrec and all other default settings for the reconstruction. The reconstruction is performed on a 512 GB ram system. From looking at the memory usage it peaks at around 314 GB for the python process. 
The entire dataset is 17 GB on disk so it should be easy to fit this into memory.
It was run using the newest release 0.1.12.

greetings,

Jan Garrevoet
Desy
Germany

This is the traceback:

OSError                                   Traceback (most recent call last)
/asap3/petra3/gpfs/p06/2015/data/11000634/scratch_cc/tomo_test_17/sh17_tomo_update_test.py in <module>()
    183 #proj = tomopy.remove_stripe_fw(proj)
    184 print 'reconstruction'
--> 185 recon = tomopy.recon(proj,angle_list,center=centre,algorithm=alg,emission=False)
    186 tomopy.write_tiff_stack(recon,out_name,start=slice_start,digit=n_digits)
    187

/usr/lib64/python2.7/site-packages/tomopy/recon/algorithm.pyc in recon(tomo, theta, center, emission, algorithm, init_recon, ncore, nchunk, **kwargs)
    242         init_recon)
    243     return _dist_recon(
--> 244         tomo, recon, _get_func(algorithm), args, kwargs, ncore, nchunk)
    245
    246

/usr/lib64/python2.7/site-packages/tomopy/recon/algorithm.pyc in _dist_recon(tomo, recon, algorithm, args, kwargs, ncore, nchunk)
    297         axis=0,
    298         ncore=ncore,
--> 299         nchunk=nchunk)
    300
    301

/usr/lib64/python2.7/site-packages/tomopy/util/mproc.pyc in distribute_jobs(arr, func, axis, args, kwargs, ncore, nchunk)
    138
    139     # Start processes.
--> 140     return _start_proc(arr, _args)
    141
    142

/usr/lib64/python2.7/site-packages/tomopy/util/mproc.pyc in _start_proc(arr, args)
    157     shared_arr = get_shared(arr)
    158     init_shared(shared_arr)
--> 159     man = mp.Manager()
    160     queue = man.Queue()
    161     with closing(

/usr/lib64/python2.7/multiprocessing/__init__.pyc in Manager()
     97     from multiprocessing.managers import SyncManager
     98     m = SyncManager()
---> 99     m.start()
    100     return m
    101

/usr/lib64/python2.7/multiprocessing/managers.pyc in start(self, initializer, initargs)
    522         ident = ':'.join(str(i) for i in self._process._identity)
    523         self._process.name = type(self).__name__  + '-' + ident
--> 524         self._process.start()
    525
    526         # get address of server

/usr/lib64/python2.7/multiprocessing/process.pyc in start(self)
    128         else:
    129             from .forking import Popen
--> 130         self._popen = Popen(self)
    131         _current_process._children.add(self)
    132

/usr/lib64/python2.7/multiprocessing/forking.pyc in __init__(self, process_obj)
    119             self.returncode = None
    120
--> 121             self.pid = os.fork()
    122             if self.pid == 0:
    123                 if 'random' in sys.modules:

OSError: [Errno 12] Cannot allocate memory

**Comment by dgursoy** [comment]
Hi Jan, here's my calculation about the datasets. You have 721 raw image data with 4008x2672 pixels (721x4008x2672 int16 = 15.44GB). We have to convert it to float32 for float arithmetic. This would double the size of about (721x4008x2672 int16 = 31GB). Reconstruction (Gridrec) needs zero padding for FFTs to be accurate. So data sizes are organized as (721x4096x4096 float32 = 50GB). The reconstruction grid should also be allocated in memory with a size of (4096x4096x4096 float32 = 274GB, or if you place the detector 90 degrees rotated 2672x4096x4096 float32 = 180GB). So just to keep the raw data and the reconstruction data, you need about 320GB space (which seems to agree with your observation). Gridrec also allocates some internal matrices for calculations but if I remember correctly they shouldn't eat too much memory. Can you check the status of your memory just before the reconstruction starts?

**Comment by jangarrevoet** [comment]
It indeed does not fit into memory. Can thus be closed. Thx
