### ISSUE TITLE
Negative values after Fourier-Wavelet stripe removal

### ISSUE THREAD

**Issue by jangarrevoet** [tomopy/tomopy#152]
Hi,
after applying the Fourier-Wavelet stripe removal algorithm (all default values except ncore=30) on some normalised datasets I get negative values causing reconstruction problems due to the use of the logarithm. This results in reconstructed zero images in those slices which contain negative numbers.
greetings

**Comment by dgursoy** [comment]
Does applying ```proj = tomopy.remove_neg(proj)``` before the reconstruction solve the problem?

**Comment by jangarrevoet** [comment]
Hi Doga,
this does fix the reconstruction issue if you not forget to set the value different from the default but you decrease the dynamic range by doing this.
greetings

**Comment by dgursoy** [comment]
Why is that? I think you should want to use the default value, because you possibly want to assign zero to the negative values. Also the array is converted to float, so dynamic range should be fine?

**Comment by jangarrevoet** [comment]
I thought of not using the default since it would result in NaN when laking the log.
Regarding the dynamic range, does the routine rescale min max or just exchanges negative numbers by the set value? If the latter, if the negative range contains meaningful information it gets lost, therefor decreasing the dynamic range. Or am I mistaken?
Should it does be general practise to include the negative number NaN remover to avoid blank reconstructed images?

**Comment by dgursoy** [comment]
The function simply converts input values to floating numbers (if they aren't float) without changing the dynamic range (e.g., 130 to 130.0). Then it replaces NaN values with the values you specify. 

I don't think a negative value has a meaningful information about the sample content. The only information is the the fact that the sample was thick enough to absorb all incident x-rays and what you detect is the electronic noise. So I would replace these values with a value very close to zero then to avoid logarithm problems.

In fact I would just replace these numbers with the median value of their local neighborhood. Something like this should do the job I guess:
```
def remove_nonpositives(img):
    mask = np.zeros(img.shape)
    tmp = filters.median_filter(img, (5, 5))
    mask = (img <= 0).astype(int)
    return tmp * mask + img * (1 - mask)
```

I think it makes sense to do this in the background to avoid such issues.
