### ISSUE TITLE
problem updating to 0.1.13 version

### ISSUE THREAD

**Issue by prjemian** [tomopy/tomopy#154]
Last night, the installation on txmtwo was updated to 0.1.13, yet in #153, it was found that 
```
import tomopy
print tomopy.__version__
```
reports version 0.1.11

Here are the packages that conda has downloaded:
```
cd /local/usr32idc/Anaconda/pkgs
ll | grep -i tomopy

drwxr-xr-x  4 usr32idc pfs     4096 Oct 30 10:20 tomopy-0.1.11-nppy27_1
-rw-r--r--  1 usr32idc pfs  5212068 Oct 30 10:19 tomopy-0.1.11-nppy27_1.tar.bz2
drwxr-xr-x  4 usr32idc pfs     4096 Dec  4 15:29 tomopy-0.1.12-py27_0
-rw-r--r--  1 usr32idc pfs  5224993 Dec  4 15:28 tomopy-0.1.12-py27_0.tar.bz2
drwxr-xr-x  4 usr32idc pfs     4096 Dec 15 22:16 tomopy-0.1.13-py27_0
-rw-r--r--  1 usr32idc pfs  5233344 Dec 15 22:16 tomopy-0.1.13-py27_0.tar.bz2
```

Here are the *installed* tomopy versions:
```
cd lib/python2.7/site-packages/
ll | grep -i tomopy

drwxr-xr-x  9 usr32idc pfs    4096 Dec 15 22:16 tomopy
drwxr-xr-x  7 usr32idc pfs    4096 Oct 30 10:53 tomopy-0.1.11-py2.7-linux-x86_64.egg
drwxr-xr-x  2 usr32idc pfs    4096 Dec 15 22:16 tomopy-0.1.12-py2.7-linux-x86_64.egg-info
```

The timestamps associate that the update to version 0.1.13 was identified as 0.1.12 and installed to the tomopy directory.  The installation did not proceed correctly.

Suggest removing all installed tomopy versions and reinstalling from latest:

```
/local/usr32idc/Anaconda/bin/conda uninstall tomopy
cd /local/usr32idc/Anaconda/lib/python2.7/site-packages
/bin/rm -rf tomopy*
cd /local/usr32idc/Anaconda/pkgs
/bin/rm -rf tomopy*
/local/usr32idc/Anaconda/bin/conda install tomopy
ls -lart
```
Verify that the 0.1.13 version is listed amongst the last items in this directory listing

**Comment by prjemian** [comment]
Anomaly in the pre-installation files has been noted in #153, that version information is not consistent with the downloaded package.  This anomaly is found in both 0.1.12 and 0.1.13 version but not in 0.1.11:

#### tomopy-0.1.11-nppy27_1/info/files
```
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info
```

#### tomopy-0.1.12-py27_0/info/files
```
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info/PKG-INFO
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info/SOURCES.txt
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info/dependency_links.txt
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info/native_libs.txt
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info/not-zip-safe
lib/python2.7/site-packages/tomopy-0.1.11-py2.7-linux-x86_64.egg-info/top_level.txt
```

#### tomopy-0.1.13-py27_0/info/files
```
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/PKG-INFO
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/SOURCES.txt
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/dependency_links.txt
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/native_libs.txt
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/not-zip-safe
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/top_level.txt
```

**Comment by prjemian** [comment]
Look for a change in the packaging configuration between version 0.1.11 and 0.1.12

**Comment by dgursoy** [comment]
As I remember in between 0.1.11 and 0.1.12 some dependency packages were rebuilt and uploaded to conda to resolve numpy versioning conflicts.

**Comment by tomopy** [comment]
uninstall/reinstall did not work:

print tomopy.__version__
0.1.11

txmtwo% conda uninstall tomopy
Fetching package metadata: ......

Package plan for package removal in environment /local/usr32idc/Anaconda:

The following packages will be REMOVED:

    tomopy: 0.1.13-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%

txmtwo% conda install -c dgursoy tomopy
Fetching package metadata: ........
Solving package specifications: .....................
Package plan for installation in environment /local/usr32idc/Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    netcdf4-1.2.1              |      np110py27_0         1.4 MB

The following NEW packages will be INSTALLED:

    tomopy:  0.1.13-py27_0

The following packages will be UPDATED:

    netcdf4: 1.1.9-np110py27_0 --> 1.2.1-np110py27_0

Proceed ([y]/n)? y

Fetching packages ...
netcdf4-1.2.1- 100% |################################| Time: 0:00:00   1.61 MB/s
Extracting packages ...
[      COMPLETE      ]|#####################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#####################################| 100%
Linking packages ...
[      COMPLETE      ]|#####################################| 100%


print tomopy.__version__
0.1.11

**Comment by dgursoy** [comment]
#155 should resolve that. The test directory is excluded from the package. Also external libraries stays inside the distribution.
