### ISSUE TITLE
windows installation and docker

### ISSUE THREAD

**Issue by felix1223** [tomopy/tomopy#157]
Hi,

I would like to install tomopy on a windows 7 machine. I had actually done this in the past following the instruction for 0.0.3 version (http://tomopy.github.io/tomopy/install.html#windows-installation). However, the 0.0.3 version of tomopy.egg is not available on jenkins any more, and I lost the copy had (If someone can share me a copy of 0.0.3, it might solve the issue I'm having too). I tried the same procedure for 0.1.11 and 12 versions, but my reconstruction results don't seem to be right as some other users have reported (image with intensity of 1E-6). 

I also installed docker and went as far as pulling an image of tomopy (https://hub.docker.com/r/dgursoy/tomopy/). As I'm new to docker, and I'm not sure how to further proceed though. Can anyone provide me some detailed instruction on how to run tomopy using docker?

**Comment by dgursoy** [comment]
@felix1223 the same procedure will not work for versions after 0.0.3. Newer versions can work only with Docker on a Win machine. I am not a pro in Docker commands but ```docker run -i ...``` should be fine I guess. More: https://docs.docker.com/engine/userguide/basics/

@aglowacki: any idea what happened to this particular egg?

**Comment by aglowacki** [comment]
I don’t think TomoPy 0.0.3 is build on jenkins anymore, The oldest version is still on jenkins is  0.1.9.

**Comment by aglowacki** [comment]
I just added a jenkins entry for tomopy/legacy branch which looks like it is 0.0.3. I haven’t tested it but you can try the python egg here 
https://jenkins.aps.anl.gov/view/Python/job/TomoPy_0_0_3/ws/dist/tomopy-0.0.3-py2.7-win-amd64.egg <https://jenkins.aps.anl.gov/view/Python/job/TomoPy_0_0_3/ws/dist/tomopy-0.0.3-py2.7-win-amd64.egg>

**Comment by gazzar** [comment]
It was a public holiday here yesterday so I didn't respond to this. Now I'm
back, I just diffed the 0.0.3 egg that Arthur created with my locally
installed 0.0.3 egg directory. I see two minor differences:
1. in the stripe_removal2() function, the sinogram data is not log scaled
in my locally installed copy, but it is in the "new" 0.0.3 version.
2. The Gridrec() constructor was defaulting the emission parameter to False
in my locally installed copy, which is removed in the "new" 0.0.3 version.

@felix1223, if you see any differences in behaviour, just make sure it
isn't one of these two differences.

Gary

**Comment by felix1223** [comment]
Thank you all for your quick responses and help. 

@dgursoy I'll probably have to study more on docker, and try this again at some point.
@gazzar In one of the previous posts, I did see you were successful with installing tomopy using docker. Would you mind briefly explaining the steps you took?
@aglowacki Thank you very much for sharing a new python 0.0.3 egg. I tried installation several times, but I'm getting the same error shown below. I tried the installation on my home computer (office was closed due to snow removal in the east coast) but I intend to try again on my office computer tomorrow in case that was the issue. Looking at the error message, would you have any idea what may be the issue? My computer is running windows 7 home premium 64 bit and I installed anaconda 64bit version. 

[Anaconda2] C:\>python -c "import tomopy"
C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win-amd64.egg\tomopy/tools\tifffile.py:2178: UserWarning: failed to import _tifffile.decodepackbits
  warnings.warn("failed to import %s" % module_function)
C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win-amd64.egg\tomopy/tools\tifffile.py:2178: UserWarning: failed to import _tifffile.decodelzw
  warnings.warn("failed to import %s" % module_function)
C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win-amd64.egg\tomopy/tools\tifffile.py:2178: UserWarning: failed to import _tifffile.unpackints
  warnings.warn("failed to import %s" % module_function)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win-amd64.egg\tomopy\__init__.py", line 24, in <module>
    import xtomo.xtomo_preprocess
  File "C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win amd64.egg\tomopy\xtomo\xtomo_preprocess.py", line 23, in <module>
    from tomopy.algorithms.preprocess.phase_retrieval import phase_retrieval
  File "C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win-amd64.egg\tomopy\algorithms\preprocess\phase_retrieval.py", line 5, in <module>
    from tomopy.tools import fftw
  File "C:\Anaconda2\lib\site-packages\tomopy-0.0.3-py2.7-win-amd64.egg\tomopy\tools\fftw.py", line 13, in <module>
    libfftw = ctypes.CDLL(libpath)
  File "C:\Anaconda2\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by gazzar** [comment]
I scribbled down a few notes in my logbook about running the docker image in Windows. I'll repeat them here, which might help you, but mostly I just followed the Docker documentation:
First, I found I had to uninstall my existing installation of Virtualbox and reinstall it. This shouldn't be necessary, but I had a problem with network interfaces that this solved.
Then I installed Docker, ran Kitematic, downloaded the tomopy image. I was able to run the image and run python and successfully import tomopy inside the container. I found that if I run Docker Quickstart from the Windows Desktop icon, it opens an MSYS terminal/shell. Trying "docker run tomopy" from this terminal/shell fails. Instead, running Kitematic then running tomopy with its start button runs a Windows powershell prompt which gives access to the container. I found that I then had to run a bash shell then I could run python:
\# bash
\# python
\>>> import tomopy

Hope this helps.

**Comment by fkim1223** [comment]
@gazzar Thank you very much for the tip! Opening a shell from Kitematic definitely get things started, and I confirmed that tomopy can be imported. 
I spent some time studying docker today, and I also learned how to open a shell from docker quick start terminal. I also tried to mount local directory (c/tomopy) to the container directory(/tomopy), but that didn't really copy the data within the directory. I had to manually copy data between local and container directories. Hopefully, I can figure out a better way to do this. I tried reconstructing the demo data set from the legacy version, and reconstruction seems to have worked properly (I had to change some codes to accommodate the newer version). I would also like to find out how to add a text editor in the container. For now, here are the codes I ran in case they will help anyone:

docker pull dgursoy/tomopy
docker run -it -v /c/tomopy:/tomopy/ dgursoy/tomopy /bin/bash
exit
docker cp data.h5 <container ID>:/tomopy/data.h5
docker cp demo.py <container ID>:/tomopy/data.h5
docker run -it -v /c/tomopy:/tomopy/ dgursoy/tomopy /bin/bash
cd tomopy
python demo.py

**Comment by jeffgelb-sg** [comment]
Hi, sorry to resurrect an old, closed thread, but I am also trying to get tomopy running on Windows 10 Pro. I tried following the instructions here and in the installation guide, using the egg file posted in this thread, but it still won't load for me. Can anybody please offer some advice as to how to get tomopy running in a Windows environment?

**Comment by cgohlke** [comment]
I put some **untested** binaries for Windows at https://www.lfd.uci.edu/~gohlke/pythonlibs/#tomopy.  Compiled with Intel compiler and MKL. Replaced `posix_memalign` with `mkl_malloc`.

**Comment by jeffgelb-sg** [comment]
Hi, thanks for this! However, I can’t seem to get any of them to install… I get an error for each file that it “is not a supported wheel on this platform.” It is a 64-bit installation of Win 10 if that helps...
<img width="660" alt="wheel" src="https://user-images.githubusercontent.com/37162010/37126613-a896e3aa-2226-11e8-8ac5-9178201005ce.PNG">

**Comment by cgohlke** [comment]
The wheels are for Python 3.5 or 3.6, 32-bit or 64-bit.

**Comment by cgohlke** [comment]
Unfortunately `test_recon.test_algorithm.ReconstructionAlgorithmTestCase` segfaults with those binaries.

**Comment by jeffgelb-sg** [comment]
Cool, thanks!! I’m working my way through the dependencies with PIP, will update with results hopefully later tonight or tomorrow. 

The instructions say to use CPython, so I downloaded a fresh copy of 3.6 from python.org (and went ahead and disposed of all other python installations just to be safe). Out of curiosity, have you tried this with Anaconda v3? The package manager really puts the batteries in the language for me, haha... I was thinking to give that a try before really rolling up my sleeves (if just for kicks!).

**Comment by jeffgelb-sg** [comment]
Just wanted to let you know that I tested with Anaconda and: success! Here is the procedure I used:

1. Install Anaconda with Python v3.6 (64-bit)
2. Open Anaconda Prompt
3. conda install:
- numpy
- mkl
- mkl_fft
- fftw
- tifffile
- dxchange
4. pip install tomopy-1.1.2-cp36-cp36m-win_amd64.whl

Now on to try a recon... will report back.

**Comment by jeffgelb-sg** [comment]
Update: reconstructions seem to be converging as expected. Awesome!! I was even able to grab astra via conda and successfully completed a CUDA-accelerated FBP recon. Thanks so much for the help getting this configured!!

**Comment by jeffgelb-sg** [comment]
Hi, just wanted to update here that the wheel file continues to work well for me. 

I wanted to ask if you would mind building a version for Python 2.7 (64-bit)? I'd like to experiment with calling TomoPy via IronPython, but that is capped at Python version 2.7.
