### ISSUE TITLE
Travis build needs to be corrected

### ISSUE THREAD

**Issue by dgursoy** [tomopy/tomopy#168]
After merging #162, Travis keeps failing.

**Comment by tacaswell** [comment]
Looking up the path of the current file does not always play well with eggs.

**Comment by dgursoy** [comment]
What do you mean? Setting envs? (This is linked with #177 btw)

**Comment by tacaswell** [comment]
In #162 a bunch of things like https://github.com/tomopy/tomopy/pull/162/files#diff-c350ee70134bcb4c0e48a20436701a83R66  I have seen issues with things like that not properly finding files when things are installed as eggs, but if #177 fixes this then I am barking up the wrong tree :sheep:

**Comment by dgursoy** [comment]
Ah. I see. Travis's problem was sth different about linking external dependencies, and now seems to be fine. But real paths needs to be reworked and thanks for pointing to this, though not in this thread.

**Comment by dmpelt** [comment]
Fixed for Python 3 by #181. All travis checks pass now!
