### ISSUE TITLE
docs build needs to be corrected

### ISSUE THREAD

**Issue by dgursoy** [tomopy/tomopy#169]
After merging #162, readthedocs build keeps failing.

**Comment by decarlof** [comment]
autodoc does not find any of the module:
/local//tomopy/doc/source/api/tomopy.io.exchange.rst:4: WARNING: autodoc: failed to import module u'tomopy.io.exchange'; the following exception was raised:
Traceback (most recent call last):
  File "/local/decarlo/conda/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named io.exchange

checked conf.py and sys.path.insert(0, os.path.abspath('..'))
looks right ...

**Comment by dgursoy** [comment]
@decarlof I think this is a local issue you have. 

Read the Docs complains about not finding the Conda shipped external dependencies (particularly the header file):
http://readthedocs.org/projects/tomopy/builds/3848425/

This can't be mocked through conf.py and no idea how to resolve this. @tacaswell, @prjemian any idea?

**Comment by prjemian** [comment]
Haven't yet tackled that type of "mock" for RTD.
The only truly fancy thing I've done is to mock out all the Qt classes 
and methods _just_ for RTD.

Suggest posing question to StackOverflow.

Pete

**Comment by tacaswell** [comment]
One (un fun) way around it is to understand wheels enough to make manylinux wheels or convince rtd to install tomopy without compiling the c.

**Comment by dgursoy** [comment]
Any fun way of resolving this? I skimmed through internet and forums a bit but couldn't find any satisfying answer. I was somehow expecting many people would suffer from a similar problem..

**Comment by dmpelt** [comment]
I researched the same problem for the ASTRA toolbox a while ago, but did not find a good solution at the time. I may have found a solution for TomoPy though: not compiling any of the C code. A fix can be found in #185 . On my personal RTD page, it seems to compile fine, and the documentation seems OK (see [here](http://tomopy-dmpelt.readthedocs.org/en/build_without_c/index.html)). I am not really familiar with all details of TomoPy's documentation, however, so maybe I missed something.
