### ISSUE TITLE
Broken ASTRA integration

### ISSUE THREAD

**Issue by dmpelt** [tomopy/tomopy#170]
After #162, the ASTRA integration seems broken, returning empty arrays. 

This was probably expected. I will have a quick look to see whether it is easy to fix, but maybe someone who was involved in #162 might be able to fix it more easily?

**Comment by dgursoy** [comment]
Not sure why yet. @michael-sutherland?

**Comment by michael-sutherland** [comment]
I completely changed how mproc works.  Also, the recon function now rotates the data so that it is in sonogram order instead of radiograph order.  I should be able to help get ASTRA working again (I've been meaning to try running ASTRA myself).

**Comment by dmpelt** [comment]
Thanks!
I have been working on it today, and seem to be getting close to a good solution. I will create a PR soon, but I still have to do some tests to see whether performance or reconstruction quality regressed or something.

**Comment by michael-sutherland** [comment]
I'm hoping things being in sinogram order will make it easier (and faster).  I noticed a speedup for the gridrec algorithm solely from the order of the data.

**Comment by dmpelt** [comment]
A fix for the ASTRA integration can be found in #176. I did some tests, but did not find a significant speedup. I think this can be expected for usecases where using a GPU makes the most sense (long running iterative algorithms, where startup time and data access are probably not a significant part of the computation time). I did notice a very nice speedup for tomopy's gridrec algorithm!

It may be possible to optimize the ASTRA integration code a bit more for the new data ordering, but, again, this might not really improve things that much for iterative methods.

**Comment by michael-sutherland** [comment]
Good point, most of the time savings are a handful of seconds here and there (which are significant when doing a gridrec reconstruction).  We also save RAM usage (since we are no longer always making copies of the data).

**Comment by dgursoy** [comment]
Is this still active?

**Comment by dmpelt** [comment]
I've been using PR #176 for a few days now, seems to work fine. Once #176 is merged I am OK with closing this.
