### ISSUE TITLE
"conda build tomopy" fails the test

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#171]
===== testing package: tomopy-1.0.0-np19py27_0 =====
import: u'tomopy'
Traceback (most recent call last):
  File "/local/decarlo/conda/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import tomopy
  File "/local/decarlo/conda/anaconda/envs/_test/lib/python2.7/site-packages/tomopy/__init__.py", line 60, in <module>
    from tomopy.prep.phase import *
  File "/local/decarlo/conda/anaconda/envs/_test/lib/python2.7/site-packages/tomopy/prep/phase.py", line 57, in <module>
    import pyfftw
  File "/local/decarlo/conda/anaconda/envs/_test/lib/python2.7/site-packages/pyfftw/__init__.py", line 16, in <module>
    from .pyfftw import (
  File "numpy.pxd", line 155, in init pyfftw.pyfftw (/local/dgursoy/Applications/Anaconda/conda-bld/work/pyFFTW-0.9.2/pyfftw/pyfftw.c:13847)
ValueError: numpy.dtype has the wrong size, try recompiling
TESTS FAILED: tomopy-1.0.0-np19py27_0

**Comment by dgursoy** [comment]
Let the fun begin.. It'll be multiple iterations to digest this PR. 

Basically the main issue here is the new dependency FFTW, which is an external library (and used by Gridrec now, and also by pyfftw). 

How did you build? We don't have a conda installer currently but ```python setup.py build``` should work once you have the libraries in place, or LD_LIBRARY_PATH and C_INCLUDE_PATH points to your fftw3f libraries and headers if they are located somewhere unexpected.

**Comment by xianghuix** [comment]
I tried python setup.py install and got error of not finding fftw3.h. It seems this is not a standard library installed in the current APS system.


________________________________

**Comment by data-exchange** [comment]
right I used conda build ...  python setup install fails (missing fftw3.h). 
I added it in the src folder and now it compiles. see code in pull request

**Comment by prjemian** [comment]
We might have that installed on /APSshare/linux.
Is that useful for you or do you need a local install for this?
If it's not there, and it would be useful, I can try to put it there 
tomorrow.

**Comment by xianghuix** [comment]
fftw3.h is declared in gridrec.c. It is required to build tomopy.


________________________________

**Comment by decarlof** [comment]
OK check pull request #173

**Comment by xianghuix** [comment]
You are right, fftw3.h is installed on /APSShare/linux/. I defined C_INCLUDE_PATH and the python setup.py install works.
________________________________

**Comment by decarlof** [comment]
What about other installing tomopy? shall we include fftw3.h in the tomopy/src folder ?

**Comment by xianghuix** [comment]
it would be convenient I guess.

________________________________

**Comment by xianghuix** [comment]
once fftw3.h is located, the installation finishes correctly. when running a reconstruction, it pops up a warning

No handlers could be found for logger "tomopy.io.reader"

this does not affect the data processing. the data processing finishes correctly. In a second computer, a similar warning shows up for "tomopy.util.extern".
________________________________
From: Xiao, Xianghui
Sent: Tuesday, March 15, 2016 11:40 PM
To: tomopy/tomopy; tomopy/tomopy
Subject: RE: [tomopy] "conda buld tomopy" fails the test (#171)

You are right, fftw3.h is installed on /APSShare/linux/. I defined C_INCLUDE_PATH and the python setup.py install works.
________________________________

**Comment by decarlof** [comment]
this could be related to #169

**Comment by dgursoy** [comment]
@prjemian I think it's always nice to have fftw libraries installed and ready to use at APSshare. 

@decarlof I wouldn't ship the header file with tomopy, because it's an external file to the project and should come through Conda. We only need to make sure the linking is correct (and Conda does a good job on that most of the time). If not, we just have to set the environment variables point to the correct location.

@xianghuix logger warning is innocent, and will fade after we have setup a logger config. We can maybe put a do-nothing handler to avoid this for now.
