### ISSUE TITLE
Disable fftw multithreading

### ISSUE THREAD

**Issue by dmpelt** [tomopy/tomopy#178]
On some machines, the fftw calls in the new gridrec implementation of #162 uses multiple threads. Since tomopy does its own slice-based multithreading, the additional threads of fftw significantly decrease performance. By specifying `OMP_NUM_THREADS=1`, fftw is forced to use only a single thread and good performance is restored.

The strange thing is that it only seems to occur on some machines, but not on others. On all machines, I performed a standard `conda-build ./` in tomopy's root directory. I don't really know whether it is a configuration problem, or whether it is possible to force fftw do use only a single core in the code, but I at least wanted to report it here.

**Comment by michael-sutherland** [comment]
Strange, I thought you had to call fftw_init_threads to enable multithreading in FFTW.  (See [FFTW-Usage-of-multithreading](http://www.fftw.org/doc/Usage-of-Multi_002dthreaded-FFTW.html#Usage-of-Multi_002dthreaded-FFTW)).

**Comment by dmpelt** [comment]
Yes, that was what I thought as well. I will investigate a little bit more.

**Comment by dgursoy** [comment]
I think using ```OMP_NUM_THREADS=1``` makes sense, since it is the fail safe option here.

**Comment by dmpelt** [comment]
I think I've finally figured out what's going on here: 

It seems that if you do an `import numpy` anywhere in the code before doing `import pyfftw`, the intel MKL library is loaded and will override FFTW's functions. It probably means that the mkl libraries are dlopened before the fftw libraries and therefore take precedence. The MKL libraries use multithreading, which causes the additional threading I notice. 

This can be fixed by doing an `import pyfftw` as early as possible (before the first `import numpy` call). Indeed, if I put `import pyfftw` as the first line in a script, I get no additional multithreading. The additional threads can actually have a significant negative influence on the performance:

```
Without importing pyfftw first:
OMP_NUM_THREADS=1 python test.py 
3.05 seconds
python test.py 
3.80 seconds
With importing pyfftw first:
OMP_NUM_THREADS=1 python test.py 
2.77 seconds
python test.py 
2.78 seconds
```

If I do not import pyfftw first, I get much worse performance if I don't specify `OMP_NUM_THREADS=1`. If I do import pyfftw first, both timings are the same. In fact, fftw's implementation seems quite a bit faster than mkl's implementation on my machine, so it probably makes sense to force fftw in some way.

I think this will happen on many machines, since it is very likely that numpy is imported before pyfftw, and conda automatically installs mkl. The problem is that it is probably not enough to simply `import pyfftw` as soon as possible in tomopy's initialization code: it is likely that a user has already imported numpy before in their own script. We had a similar issue with mixing matlab and numpy with ASTRA, and we fixed it by setting `dlopen` parameters to `RTLD_NOW|RTLD_DEEPBIND` temporarily before importing. I will try something similar here and see whether it works as well.

**Comment by dmpelt** [comment]
I just updated #217 with a commit that does the `RTLD_NOW|RTLD_DEEPBIND` trick. Now the problem only occurs when a user first imports numpy, then pyfftw (or something else that dlopens libfftw), and finally tomopy. Any other order (pyfftw first, or tomopy first, or tomopy before pyfftw) will result in the correct fftw library to be used instead of the multithreaded one from MKL. We could mention somewhere in the docs that it is best to import tomopy as early as possible.

On a machine with 32 cores, this has a large impact, reducing the reconstruction time for a certain dataset from 56 seconds to 21 seconds. I think the additional threading by MKL is very bad for the CPU cache, causing a significant slow down.

This removes the need to specify OMP_NUM_THREADS=1 to disable the multithreading, allowing other uses of openmp again.

**Comment by jrmadsen** [comment]
Fftw has been removed
