### ISSUE TITLE
MKL not found

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#180]
bash-4.1$ conda install -c dgursoy tomopy
bash-4.1$ python rec_tomcat.py
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.

Shall we have them installed on /APSshare?

Are these freely available for all platform?

**Comment by dgursoy** [comment]
Not sure if we require MKL libs. For what it is needed (or complaining about) in re_tomcat.py?

**Comment by data-exchange** [comment]
https://github.com/tomopy/tomopy/blob/master/doc/demo/rec_tomcat.py
is one of the demo

**Comment by dmpelt** [comment]
Recent numpy builds of conda use MKL libs. I've seen these types of error before when there was a mismatch between the installed numpy and mkl packages. Does something like `conda install numpy` to update the numpy package work? If not, a completely clean environment should work.

**Comment by dgursoy** [comment]
Some more info about this:
https://docs.continuum.io/mkl-optimizations/index

**Comment by decarlof** [comment]
@dmpelt thank you Daniel! that was the problem
f
