### ISSUE TITLE
Emission=False changes data in place

### ISSUE THREAD

**Issue by dmpelt** [tomopy/tomopy#183]
I tried an old reconstruction script with the current master branch, and the results of repeated reconstruction calls were incorrect because the handling of `emission=False` changed (I think after #162).

After #162, using `emission=False` changes the data in place. This is probably a good idea for optimization, and does not affect a single reconstruction call, but it means that a different reconstruction call afterwards reapplies the data change, which results in incorrect reconstructions.

This will reproduce the problem:

```
rec = tomopy.recon(prj, theta, center=best_center, algorithm='gridrec', emission=False)
tomopy.io.writer.write_tiff_stack(rec, fname='./gridrec/rec', start=sino_start)

rec = tomopy.recon(prj, theta, center=best_center, algorithm='gridrec', emission=False)
tomopy.io.writer.write_tiff_stack(rec, fname='./gridrec2/rec', start=sino_start)
```

The first call will have correct reconstructions, the second one will be incorrect. In my case, it caused problems since I wanted to try different reconstruction methods in a single script using multiple calls, and only the first call had a correct reconstruction. If you change the calls _after_ the first one to `emission=True`, the reconstructions are correct, since the emission correction already has been applied.

I don't know what the best solution for this is, but I think there are at least two possibilities:

1. Change the `emission=False` handling to create a copy like the previous versions. This might have some negative impact on performance and memory requirements.
2. Move the `emission=False` handling to a separate preprocessing method, so it can be called only once before reconstruction if needed. Something like: `prj = tomopy.linearize(prj)` or something. This can be done inplace, so should not have a negative impact on performance, but it will make the code not backwards compatible.

What do you think?

**Comment by dgursoy** [comment]
Nice point. I think my vote is on the second option. There are two paths we can follow:

1. We put it in normalize, since it is calculated once. But the downside is we have multiple normalize functions, so we need to add it to each one of them which is not good.

2. We can have a new function, something like you suggested and use it for this.

I think second one would be better. Any objections?

**Comment by dmpelt** [comment]
I don't have a clear preference. Would there be a reason to either look at the data or adjust the data after normalization but before linearizing? If so, the second option would be better, since it will allow for this.

**Comment by dgursoy** [comment]
Let's have it as a separate function first, and we can afterwards add it as an optional argument in normalization functions. What to call this function? Simply ```tomopy.minus_log```, which is very direct and true?

**Comment by dmpelt** [comment]
Sounds good. Is there a common name that beamline scientists would use for this operation? If so, I would use that as the function name, but `minus_log` sounds good to me too.
