### ISSUE TITLE
minus_log

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#187]
adding minus_log causes recon to fail:

```
proj = tomopy.normalize(proj, flat, dark)
imlog = tomopy.minus_log(proj)
rec = tomopy.recon(imlog, theta, center=rot_center, algorithm='gridrec')
```

Traceback (most recent call last):
  File "rec_anka.py", line 52, in <module>
    rec = tomopy.recon(imlog, theta, center=rot_center, algorithm='gridrec')
  File "/local/decarlo/conda/anaconda/lib/python2.7/site-packages/tomopy-1.0.0-py2.7-linux-x86_64.egg/tomopy/recon/algorithm.py", line 209, in recon
    tomo = init_tomo(tomo, sinogram_order)
  File "/local/decarlo/conda/anaconda/lib/python2.7/site-packages/tomopy-1.0.0-py2.7-linux-x86_64.egg/tomopy/recon/algorithm.py", line 292, in init_tomo
    tomo = np.swapaxes(tomo, 0, 1) #doesn't copy data
  File "/local/decarlo/conda/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 498, in swapaxes
    return swapaxes(axis1, axis2)
ValueError: bad axis1 argument to swapaxes

**Comment by dgursoy** [comment]
This should work:

```
proj = tomopy.normalize(proj, flat, dark)
tomopy.minus_log(proj)
rec = tomopy.recon(imlog, theta, center=rot_center, algorithm='gridrec')
```

But the in-place computation should be optional I guess. Not intuitive as now. Let's keep this open till we fix that.

**Comment by cmkewish** [comment]
I just installed tomopy and don't find minus_log at all:

'In [13]: proj = tomopy.minus_log(proj)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-5bb480ea6b4a> in <module>()
----> 1 proj = tomopy.minus_log(proj)

AttributeError: 'module' object has no attribute 'minus_log'

In [14]: tomopy.m [tab]
tomopy.median_filter  tomopy.misc'

**Comment by dgursoy** [comment]
Strange.. Can you check if the version is 1.0.0? 
```
import tomopy
tomopy.__version__
```

**Comment by cmkewish** [comment]
Very strange. I'm looking at the screen in front of me with the results of 

```
conda install -c dgursoy tomopy=1.0.0
```
Giving me an all complete, all packages already installed for tomopy v1.0.0 for python27
Then when I import into python the version number is v0.1.15
Maybe I can update/upgrade since the install is being tricked into thinking everything is there?

**Comment by ravescovi** [comment]
@decarlof We should find a way to clean old eggs at the install script. I will look into that.

**Comment by tstannar** [comment]
I have also noticed a strange phenomenon with this function in Tomopy 1.0.0. When I use numpy to take the absolute value of the projection array, then the negative log, my reconstruction comes out ok. When I use the built in Tomopy log function instead, some of the slices will come out as NaNs.
