### ISSUE TITLE
Downsample odd values

### ISSUE THREAD

**Issue by ravescovi** [tomopy/tomopy#188]
For odd sized sinograms the downsample is behaving weirdly. It generates a drift on the donwsampled sinogram if the upsample size was not a multiple of the downsampling level.

**Comment by dgursoy** [comment]
I think it's when the dimension of the array to be downsampled is not power of two.

**Comment by ravescovi** [comment]
Exactly. When you downsample to a fractional number it gives the error. 
For ray values it is ok (you can crop or pad the image) but if you downsample angles that will give you a problem.
