### ISSUE TITLE
For new developers, what is the expected workflow for running unit tests?

### ISSUE THREAD

**Issue by skylarjhdownes** [tomopy/tomopy#212]
Hi there, new to group Python development here.  I'm wondering what the expected pattern for running the unit tests is.  I've tried running various files in the test directory, but none of them are giving me test output.  

I'd be happy to add some instructions to the docs once I've got a better understanding, if that would be useful.

**Comment by dgursoy** [comment]
Hi @skylarjhdownes, we try to check (at least!) all function returns with synthetic data, together with some dimension, type, etc. All tests sit in the test folder and have the same tree structure as the package modules with ```test_``` added as a prefix. Travis simply performs all checks before accepting PRs, and I believe you can use the same for checking coverage. 

Unfortunately we don't have much for developers but this might be the right time to have some text. I'd be glad if you can lead this! Thanks!

**Comment by skylarjhdownes** [comment]
Happy to help.  I'll do my best to update the docs as I familiarize myself with the code.

It sounds like there isn't a preferred way of running the tests locally?  I've had some success running them with [nose](http://nose.readthedocs.io/en/latest/) and [pytest](http://docs.pytest.org/en/latest/) after talking with @michael-sutherland , though pytest doesn't seem to like the tests in test_algorithm.py for some reason.

From the reading I've been doing I would lean towards using pytest, since it's more actively maintained. Though now that I know what it is, I'm noticing nose referenced in the tests.  Is that what Travis uses? `script: nosetests test --with-coverage` is in .travis.yml, so I would assume so.

**Comment by dgursoy** [comment]
Great! I use nose for testing and so does Travis. But I don't have any preference between the nose or pytest. As you may have noticed Coveralls also helps to track the test progress.
