### ISSUE TITLE
Cannot install using windows Conda

### ISSUE THREAD

**Issue by xianbo** [tomopy/tomopy#219]
I shows an error: Package missing in current win-64 channels.

**Comment by tomopy** [comment]
Currently only linux and OSX are actively maintained. If some windows developer reads this perhaps can help

Sent by T-mobile

**Comment by teracamo** [comment]
If you are interested in using windows, visit my fork branch win_x64 as I am not able to test my build on linux

**Comment by carterbox** [comment]
Duplicate of #283
