### ISSUE TITLE
ncore/nchunk having no effect

### ISSUE THREAD

**Issue by cmkewish** [tomopy/tomopy#221]
I'm seeing no difference in run times of gridrec for various versions of the parameters ncore and nchunk, using an edited version of the TomoPy example script on readthedocs.

Version: TomoPy 1.0.0
System: 4x 16-core CPU, 4TB RAM
OMP_NUM_THREADS=1 in system environment
Dataset: 1500 projections x 2048x2048 frame size x 17 MB TIFF
Read data function call:

```
for i in range(0,1499):
    file = '%sextpro_%04d.tiff' % (fname, i)
    proj[i,:,:] = dxchange.read_tiff(file)
```

Reconstruction function call: 

```
recon = tomopy.recon(proj, theta, center=1024, algorithm='gridrec', ncore=64, nchunk=32)
```

Output dataset: 2048x 33 MB TIFF

Writing in /home
ncore=64 and nchunk=32: `
    real    12m22.079s
    user    14m47.912s
    sys     5m59.012s`
run 2`
    real    12m21.421s
    user    15m2.416s
    sys     5m52.600s`
ncore=16 and nchunk=128`
    real    12m40.706s
    user    11m54.890s
    sys     5m26.917s`

Using a different write directory on a mount point:
ncore=64, nchunk=None`
    real    11m39.197s
    user    15m20.341s
    sys     5m37.033s`
2nd run:`
    real    10m25.411s
    user    15m24.228s
    sys     5m24.221s`
ncore=4, nchunk=None`
    real    12m20.970s
    user    10m5.310s
    sys     5m2.371s`
ncore=4, nchunk=1`
    real    14m21.153s
    user    14m46.437s
    sys     5m8.720s`

Is there something I'm supposed to enable for these parameters to work?

**Comment by dgursoy** [comment]
A bit of a side topic, but could you also check times by setting ```sinogram_order=True``` in your reconstruction? For this, you should first swap the order of the first and second axes of the sinogram before reconstruction:
```
for i in range(0,1499):
    file = '%sextpro_%04d.tiff' % (fname, i)
    proj[:,i,:] = dxchange.read_tiff(file)
```
```
recon = tomopy.recon(proj, theta, center=1024, algorithm='gridrec', sinogram_order=True)
```
