### ISSUE TITLE
Options to add cuda version of median_filter and outlier_removal

### ISSUE THREAD

**Issue by kyuepublic** [tomopy/tomopy#228]
Hi All:

Recently I develop a cython package including two cuda functions for median_filter and outlier_removal in tomopy. The results show some good speed up for small window size. But there are many type of CPU model and GPU model, and the performance will be different. For example, on my 4000$ workstation with 24 cores, a 300$ nvidia quadro 5000 can only be faster up to windows 7.  But if you ave a NVIDIA TITAN X, performance will be different.

Right now we have two options to merge into tomopy and we would like to hear your feedback that which one you prefer.

1 We will implement a configure function for you to use in your script for comparing the cpu version and gpu version function. You have to try yourself with different window size on your own platform to get a performance comparison, then remember this and use it in your future script.

2 We will do a thorough comparison on various combination of CPU and GPU model and choose the best one for you. If the GPU will not give you good performance, the function will choose the CPU version automatically for you. 

Thanks for your feedback and we will implement based on your preference.

**Comment by dgursoy** [comment]
I'd vote for 1 to keep hardware configuration separate from the algorithm library.

**Comment by decarlof** [comment]
I would go with 1 and let the user decide  if they want to run on CPU or GPU. This was they can independently do comparisons and select the best option for their hardware/window size.

with 2. there is no control on the hardware used,

f

**Comment by kyuepublic** [comment]
Hi All:

Thanks for the feedback and looks like all vote goes to the 1 option. So I just change my code and send a pull request for the merge.

**Comment by decarlof** [comment]
@kyuepublic should this be closed?

**Comment by kyueaes** [comment]
Sure, please go ahead, the interface has been merged.

Regards,
Ke Yue
________________________________

**Comment by data-exchange** [comment]
@kyueaes @kyuepublic I want to add docs for this new functionality. Can you please let me know what is the speed improvement for median_filter and outlier_removal for a 2,048 x 2,048 image compared to CPU? Also how scalable these methods are? thanks

**Comment by kyuepublic** [comment]
@data-exchange sure, I just redo the test on my workstation for a 2,048 x 2,048 image.
The GPU model I am using is nvidia Quadro 6000 which has 448 cores and worth around 800 bucks on amazon. The result is attached.

![performance](https://cloud.githubusercontent.com/assets/18356584/21032486/4e7e5b7c-bd6f-11e6-8b01-b9358f0bb57c.png)

Based on my current experience, there are a bunch of scalable factors here:
1 The image size, the bigger the image, the better the gpu performance.
2 The image data, if the image is a sparser matrix, which has bunch of 0s, the gpu would not be that good.
3 The value of the each pixel. If the pixel value is large number, it will perform good.

Based on my profiling of some tomopy script, when the window size becomes bigger, such as 5, or 7, the total running time of median filter and outlier removal takes more and more percentage of the total running time. Remove strip also takes a fair amount of time, but since it is not straight forward to change it to gpu code. I choose to optimize these two methods.

Becasue different people have different CPU and GPU, I can not say a 800 gpu can beat all of them, like the fancy 10K workstation we used here. But at some degree, it can provide a cheap alternative method to improve speed up.

And for anyone who wants to try compare the performance by themselves, I wrote a test script at [https://github.com/kyuepublic/tomocuda/blob/master/test/test.py](url). Thanks

**Comment by kyueaes** [comment]
For some reason, my figure can only shown on github, please check the image on github.

Thanks,

Regards,
Ke Yue

________________________________________

**Comment by decarlof** [comment]
@kyueaes thanks. are you saying for example that for a window size of 10 mfilter is 18x faster on GPU than CPU?

**Comment by kyuepublic** [comment]
yes it is, and it will even more faster if you have bigger pixel value and
bigger image. And my CPU is really powerful than the normal i7 people
generally use.
