### ISSUE TITLE
Cannot import due to missing dxchange

### ISSUE THREAD

**Issue by matze** [tomopy/tomopy#231]
The `dxchange` package is specified as a requirement but cannot be found on PyPI. Could you make this package either a soft dependency or push it to PyPI?

**Comment by dgursoy** [comment]
It shouldn't be a dependency at all actually. I will remove this from list of dependencies, but need to check first if any test, etc. is using it. Thanks.

**Comment by dgursoy** [comment]
Would conda work instead of pip?

**Comment by matze** [comment]
Personally, I am hesitant to use yet-another-package-manager and ignore my system's packages but … I suppose it could?
