### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by kohr-h** [tomopy/tomopy#236]
When `pip install`'ing straight from a repo clone, `import tomopy` fails due to a couple of missing dependencies. Perhaps you want to add them to `setup.py`?

List of missing dependencies:
- `pyfftw` (raised in `__init__.py`)
- `six` (raised in `util/dtype.py`)
- `h5py` (raised in `ip/writer.py`)
- `numexpr` (raised in `util/mproc.py`)
- `tifffile` (raised in `misc/phantom.py`)
- `dxchange` (raised in `recon/rotation.py`)
- `pywt` (raised in `prep/stripe.py`)
- `skimage` (raised in `recon/rotation.py`)

Edit: alternatively, if you want it to be optional, the potentially failing import statements should be fenced, and the case when they're not available should be handled.

Edit 2: Instead of opening new issues, I just add the other missing dependencies here.

**Comment by carterbox** [comment]
If you use `pip` instead of `conda` to install, the [requirements](https://github.com/tomopy/tomopy/blob/master/requirements.txt) list has most of these already, but if you are installing from a local clone, then I think you have to use `-r requirements.txt` to request that the dependencies are installed.

Considering the above, it seems that only `h5py` and `tifffile` are missing, but these are optional. I'm not sure if they are actually needed anyway because I believe that all the file io operations are being handled through `dxchange` now/soon.

**Comment by kohr-h** [comment]
Sure, it's up to you how you want to handle this. Requiring the `-r requirements.txt` is one way, but it's a bit annoying from a user's perspective. You can also read the file in `setup.py` and use the lines as `install_requires` in the call to `setup`.

**Comment by carterbox** [comment]
It's not up to me; I'm not a maintainer for this repository.

I agree it's a little annoying, but the recommended/supported package manager for `tomopy` is `conda`. With `conda`, the dependencies are installed automatically.

**Comment by kohr-h** [comment]
> It's not up to me; I'm not a maintainer for this repository.

Well then it's up to them if they want to close this issue or do something about it.



> I agree it's a little annoying, but the recommended/supported package manager for tomopy is conda. With conda, the dependencies are installed automatically.

That's true for releases, but for installation from source, the [instructions](https://tomopy.readthedocs.io/en/latest/install.html#installing-from-source-via-command-line) give an "old-fashioned" command (with `sudo`) that roughly does the same as `pip install --editable /path/to/repo`. So with the official instructions, you end up with an installation that is not usable, which is kind of bad.

**Comment by carterbox** [comment]
From that same instruction page:
>Tomopy is dependent on other libraries, listed in the requirements.txt and meta.yaml files.

I guess the assumption is that if you are a developer, then you already know how to obtain required packages.

Suggestion: Edit the developer documentation to include how to easily install the dependencies. The following method is probably the best way because `dxchange`, like `tomopy`, is not listed on `PyPI`.
```
$ conda install --file requirements.txt -c dgursoy
$ sudo python setup.py develop
```

**Comment by dgursoy** [comment]
We support and recommend use of ```conda``` for distribution. There are few reasons for doing that. First of all, it makes users life much easier. Developers should find a way to obtain them, either from a conda channel or elsewhere. Second, not all requirements are always available in PyPI and supporting them (or explaining how to get them) is mostly painful. Third, ```requirement.txt``` can be used as a useful guide telling user what is required, but it is far from replacing a proper package manager, and maintaining the versioning of each package in the text file becomes a headache with increasing number of dependencies.

**Comment by kohr-h** [comment]
I fully agree, but that still leaves the issue of non-working instructions. Perhaps you want to use the suggestion by @carterbox?

**Comment by prjemian** [comment]
Where is that suggestion?

Doga is absolutely right.  Building all parts from source is much harder to
support.

**Comment by kohr-h** [comment]
[There](https://github.com/tomopy/tomopy/issues/236#issuecomment-280518397)

**Comment by prjemian** [comment]
thx, insufficient CaFeINe to visualize properly

**Comment by dgursoy** [comment]
I created a PR (see above) to better explain the install from source. How does this read?

**Comment by kohr-h** [comment]
I think it's better than before. 
One thing I liked about the old formulation, though, was the "develop" option in the installation step. AFAIK it is also recommended to use `pip` for installing, not `python setup.py something`. In this case it would be `pip install --editable .`, or without `--editable` if users don't want a link, but then with `--user` to make a local install.

**Comment by dgursoy** [comment]
The reason I removed the develop option was that I want the developer use fork and PR model. This page is only for users.

**Comment by kohr-h** [comment]
Ok sure.
