### ISSUE TITLE
Issue running Astra wrapper with 2 GPUs

### ISSUE THREAD

**Issue by michael-sutherland** [tomopy/tomopy#242]
Moving discuss from #241 to here.  I can't run with more than one GPU when using the Astra wrapper.  Stepping through the code, it looks like the first GPU starts up just fine, but the second GPU kicks off the first one.  I tried changing my compute mode to EXCLUSIVE_PROCESS but it didn't seem to help.

**Comment by dmpelt** [comment]
I have been running ASTRA with multiple GPUs successfully in the past, so at least it was working before. I haven't tried it recently though, so maybe some of the recent changes broke it, although I am not seeing something suspicious in the code at the moment. I will try it soon on one of our machines here.

Have you tried running with `ncore=1` in the `tomopy.recon` call? Since all parallelization is done by the GPUs anyways, using `ncore=1` is usually better when running ASTRA CUDA algorithms. When `ncore>1`, TomoPy will launch multiple threads that each launch multiple threads themselves (one for each GPU) - maybe that causes issues...

**Comment by michael-sutherland** [comment]
Yes, I was using ncore=1 (also, I just changed it so that we don't spawn a thread when ncore=1).

**Comment by dmpelt** [comment]
That is strange then... I will test with the latest master branches of both TomoPy and ASTRA and report back.

**Comment by dmpelt** [comment]
I just checked with the latest master branches of both TomoPy and ASTRA:

If I don't supply `ncore=1`, the code is only run on the first index of `gpu_list`. When I use `ncore=1` however, it does run on all GPUs in `gpu_list`. So the following code runs on four GPUs on my test machine:

```python
tomopy.recon(d,a,algorithm=tomopy.astra, options={'method':'FBP_CUDA','proj_type':'cuda','gpu_list':[0,1,2,3]},ncore=1)
```

I'm not sure why it doesn't work when not using `ncore=1`: it could be that the threads-within-threads are causing problems. I will try to find out what is going on. 

Also, I don't know why it is not running on both GPUs on your machine even when using `ncore=1`. What does `nvidia-smi` output before and after starting the reconstruction call?

**Comment by michael-sutherland** [comment]
Before processing starts:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 370.28                 Driver Version: 370.28                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 0000:01:00.0      On |                  N/A |
| 23%   42C    P0    58W / 250W |    469MiB / 12189MiB |      1%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 0000:02:00.0     Off |                  N/A |
| 23%   34C    P8    14W / 250W |      1MiB / 12189MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1860    G   /usr/bin/Xorg                                  236MiB |
|    0      3692    G   /usr/bin/gnome-shell                           230MiB |
+-----------------------------------------------------------------------------+
```

After a single thread has been spawned (for GPU 0):

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 370.28                 Driver Version: 370.28                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 0000:01:00.0      On |                  N/A |
| 27%   53C    P2   223W / 250W |    653MiB / 12189MiB |     77%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 0000:02:00.0     Off |                  N/A |
| 23%   34C    P8    14W / 250W |      3MiB / 12189MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1860    G   /usr/bin/Xorg                                  236MiB |
|    0      3692    G   /usr/bin/gnome-shell                           231MiB |
|    0     11999    C   /home/tdsutherland/anaconda2/bin/python2.7     181MiB |
+-----------------------------------------------------------------------------+
```

After the second thread starts (notice that GPU 0 stops, and GPU 1 takes over):

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 370.28                 Driver Version: 370.28                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 0000:01:00.0      On |                  N/A |
| 31%   55C    P2    83W / 250W |    623MiB / 12189MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 0000:02:00.0     Off |                  N/A |
| 23%   42C    P2   230W / 250W |    214MiB / 12189MiB |     85%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1860    G   /usr/bin/Xorg                                  236MiB |
|    0      3692    G   /usr/bin/gnome-shell                           232MiB |
|    0     11999    C   /home/tdsutherland/anaconda2/bin/python2.7     151MiB |
|    1     11999    C   /home/tdsutherland/anaconda2/bin/python2.7     211MiB |
+-----------------------------------------------------------------------------+
```

**Comment by dmpelt** [comment]
That is strange... At least it is using each GPU at some point, so I think the parameters are passed correctly from TomoPy to ASTRA. Does simple wall clock timing show that running with `gpu_list=[0]` and `gpu_list=[0,1]` both take the same amount of time? And is the problem large enough to fully occupy both GPUs?

For my tests, I was running Python 3, and I know that some threading things changed between Python 2 and 3. It is a long shot, but maybe running in Python 3 fixes the problem. If not, we can try to run a simple CUDA kernel on both GPUs using the same `concurrent.futures` approach that is used in TomoPy+ASTRA to see if the same problem shows up.

It is a bit difficult to help with debugging since I can't reproduce the problem. I'll try to run the same tests with Python 2 and see what happens.

**Comment by michael-sutherland** [comment]
OK, I figured it out!  Python is sharing the "opt" dict in all of the threads when e.submit is called in wrappers.py.  Inside of this dict is a dict with the key 'extra_options'.  Inside of this dict is where we store which GPU to run (using key 'GPUindex').  Each thread is setting this value to the GPU to use and then reading it back for each slice, but this is a shared dict and hence a shared number.  First thread sets it to 0 and starts running on GPU 0.  Second thread sets it to 1 and now both threads start running on GPU 1.  This can be simply fixed by doing a deep copy of the opt dict before passing to the threads.  I'll push up a fix soon.

**Comment by dmpelt** [comment]
Wow, good find! Could the fact that I was not using any extra options be the cause that I was not having the same problems? In that case, an empty dict is created for each thread I think.

Thanks for investigating and writing the PR!

**Comment by michael-sutherland** [comment]
Yes, that's why you weren't having the issue.
