### ISSUE TITLE
Alignment of projection images

### ISSUE THREAD

**Issue by canismarko** [tomopy/tomopy#245]
More a question than anything else, but I was wondering what the current state is of automatic alignment of projection images. I'm considering trying to implement this but don't want to duplicate efforts. The FAQ states that this feature is on your wish list and that "There are multiple groups interested and working on developing robust methods for automatic alignment". Are any of these efforts nearing usability? If not, my thought was to try my hand at improving the strategy taken by [TXM Wizard](https://sourceforge.net/projects/txm-wizard/):

1. Create translation array with shape (n_projs, 2), initialized to all zeros.
2. Do initial phase correlation of projections to estimate translation array [10.1107/S1600577514013939](http://dx.doi.org/10.1107/S1600577514013939)
2. Apply translation array to raw projections
3. Perform reconstruction from translated projections
4. Project the (poorly) reconstructed volume to get new calculated projections
5. Do phase correlation between original projections (3) and calculated projections (4)
6. Update translation array with values from (5)
7. Return to step (3) until convergence or max_iters is reached.

I think a major challenge would be doing this with efficient memory usage, since it requires several, potentially large, intermediate arrays.

Thoughts?

**Comment by dgursoy** [comment]
Agreed and it'll be available very soon!

**Comment by dgursoy** [comment]
alignment is introduced now in current master
