### ISSUE TITLE
Astra_rec_cpu clips data when center of rotation is off

### ISSUE THREAD

**Issue by michael-sutherland** [tomopy/tomopy#247]
First off, is there no way to specify a center of rotation when running astra on a CPU?  If there is, let's use it and fix this issue the correct way.  

The function astra_rec_cpu does a np.roll to put the center of rotation in the middle and then zeros out the rolled over part of the data.  This may introduce issues in a reconstruction and also clips data.  I think it would be more accurate to create a large np.zeros sinogram and copy the data in to the larger sinogram for reconstruction (we also need to create a larger recon object).  Then after the reconstruction, extract the part that we want to put back in the recon object.  It adds two copies, but we can create the sinogram and recon object once and re-use it for each sinogram.

**Comment by dmpelt** [comment]
There is currently an open PR for ASTRA that adds a `parallel_vec` geometry (https://github.com/astra-toolbox/astra-toolbox/pull/69), which will enable us to set the center of rotation in a much nicer way. The current `np.roll` approach is indeed very hacky and doesn't produce the best results - I mainly added it as a temporary solution until the `parallel_vec` geometry stuff gets merged into ASTRA. Once it is, I will update the wrapper to use the new geometry object for both CPU and GPU computations.

**Comment by nghia-vo** [comment]
A simpler solution for this is:   
     sinogram = scipy.ndimage.interpolation.shift(sinogram,(0, shift), mode='nearest')
instead of np.roll.  In many cases (e.g samples bigger than FoV), np.roll gives a sharp jump of intensity at the shifted point which is enhanced by ramp filter ->ring artifacts.
    The option "mode = 'neareast'" in  scipy.ndimage.interpolation.shift acts as an edge padding at the shifted point -> reduce the sharp change of intensity at the boundary -> reduce artifact.
    Another advantage of using interpolation.shift is that you can shift with a float number (useful for sub-pixel CoR determination).

**Comment by carterbox** [comment]
The feature discussed here (use of `np.roll` in `astra_rec_cpu`) hasn't been touched in two years,

https://github.com/tomopy/tomopy/blob/788aaf43ff3db9392629ad0c10f4b29db31063f6/tomopy/recon/wrappers.py#L216

but astra-toolbox/astra-toolbox#69 was closed six months ago. @dmpelt, are you still planning to update the wrapper?

**Comment by dmpelt** [comment]
Indeed, I should have done this a long time ago! I will update this as soon as I find the time to properly write and test it.
