### ISSUE TITLE
Reducing noise in reconstruction with Gridrec

### ISSUE THREAD

**Issue by DimitarTasev** [tomopy/tomopy#257]
Hello dear TomoPy developers!

I have been using the TomoPy package to run reconstruction on Tomography images taken with neutrons, however in the end reconstruction I am getting a lot of noise, and the data is in a very small value range, sometimes mixed in with noise, and usually has **negative pixel values**, thus is hard to extract just the information I need.

I apologise for the *very* long post, I can provide further information if you think it'll be of any help. I understand this is not an issue with tomopy but I was hoping you could give me some ideas/suggestions

I am sorry, but I think it will not be possible to upload a whole sample (as they are ~20GB), so as a start I will provide a couple of images, an original, a pre-processed one, a reconstructed one, with their respective histograms, and the 3D visualisation of the object, with some of the noise clipped out.

I am posting this in the hope that you have encountered a similar issue, and could spot something I am unaware of (i.e. too much noise in the pre-processing image, or I need to do more post-processing to clean out the noise from the reconstructed images).

Original:
![image](https://cloud.githubusercontent.com/assets/9135965/23858100/4a6aec08-07f7-11e7-9a68-a6f2c1ec8bb4.png)

One of the pre-processed images:
![image](https://cloud.githubusercontent.com/assets/9135965/23857947/d8c9305a-07f6-11e7-9828-4c445baf439a.png)

Three of the reconstructed images (without any post-processing):
I know this first one looks a bit wrong, but that happened after I cropped a lot of the noise that was present in the pre-processing
![image](https://cloud.githubusercontent.com/assets/9135965/23858381/1b900458-07f8-11e7-8afa-a27b74c149fa.png)

![image](https://cloud.githubusercontent.com/assets/9135965/23858331/f69a1f12-07f7-11e7-94d1-2c8a83a61d1e.png)

![image](https://cloud.githubusercontent.com/assets/9135965/23858357/0cbe6cda-07f8-11e7-9f13-2cb596b4e0a0.png)

The visualisation of the reconstruction (with a lot of the cropped out):
Note: This has a ROI applied to it to show off the inside of the reconstruction.
![image](https://cloud.githubusercontent.com/assets/9135965/23859246/ec11f634-07fa-11e7-8f36-dc8e5039c653.png)
![image](https://cloud.githubusercontent.com/assets/9135965/23859565/f06f75a2-07fb-11e7-9baa-705a68d293fd.png)

You can see that the inside of the reconstruction has some noise left over. 
I am not sure what this is caused by, and this is what I am hoping you can help me with. 
Do I need to apply some pre-processing filter? Can you give me some suggestions about what I can try to reduce the noise, and should I apply it to the original images as pre-processing or the reconstruction as post-processing?

The pre-processing consisted of:
1. An image crop to a user selected ROI
2. A background normalisation with flat/dark images
3. A contrast normalisation with a ROI normalisation
4. A `tomopy.misc.corr.remove_outlier` with params: dif=8 size=8
5. A cut-off filter to crop out noise around the object

The parameters for the reconstruction are:
Algorithm: Gridrec
Center of rotations: List with centers interpolated for each slice (I think it works well enough)
Projection angles: List with calculated projection angles, the max angle is provided (360 degrees in this case as the sample did a full circle), and is then equidistantly spread out for each slice
Sinogram order: Was set to True, the images provided were converted to sinograms beforehand, to avoid the copy inside Tomopy's recon.

**Comment by dgursoy** [comment]
My instinct tells me you are not doing ```-log``` before reconstruction (i.e. proj = tomopy.minus_log(proj)). Could that be the reason?

**Comment by DimitarTasev** [comment]
@dgursoy Do I do that on the whole sample data stack? If so I will try it and get back to you in a bit :)

**Comment by dgursoy** [comment]
Yes indeed.

**Comment by DimitarTasev** [comment]
@dgursoy Hello again! Sorry for the delayed response, I've been playing with the -log reconstructions and I would like to thank you as that seems to have greatly improved the reconstruction quality!

I would like to ask about another thing I am curious about - the reconstructed images seem to have very low contrast, and values within the range of -0.02 to -0.00 (usually most of the noise) and then from 0.00 to 0.02 is the data. 
Is this normal or do I have to apply something else to expand the range of the values?

Some reconstructed images:
**No post processing**, and no contrast adjustment
![image](https://cloud.githubusercontent.com/assets/9135965/23988916/3dee8790-0a28-11e7-9c83-52d6cc519bd5.png)

**No post processing**, manual contrast adjustment
![image](https://cloud.githubusercontent.com/assets/9135965/23988927/4f6cca36-0a28-11e7-9576-03318eea2dd6.png)

And the renderings of the reconstruction:
X cross section
![image](https://cloud.githubusercontent.com/assets/9135965/23989127/299e64da-0a29-11e7-95ef-2acdd01c1c3d.png)

Y cross section
![image](https://cloud.githubusercontent.com/assets/9135965/23989133/312d6d04-0a29-11e7-9368-f9481e186a6c.png)

Thank you very much for your time,
Dimitar

**Comment by dgursoy** [comment]
You can try running below function after reconstruction:
```recon  = tomopy.circ_mask(recon, axis=0, ratio=0.9, val=0.0)```
This basically masks the outermost dark circular frames that spoils the dynamic range of the image values.

**Comment by DimitarTasev** [comment]
Thank you very much for your help! I'll close the issue now to not pollute the open issues list.

**Comment by dgursoy** [comment]
👍
