### ISSUE TITLE
No handlers could be found for logger "tomopy.io.writer"

### ISSUE THREAD

**Issue by ipostuma** [tomopy/tomopy#265]
hello ! 

I am trying to install tomopy to reconstruct a SPECT image from a sinogram. I installed both dxchange and tomopy from source (git clone) with python2.7. When 

`import tomopy`

I get this warning

```
No handlers could be found for logger "tomopy.io.writer"
WARNING:dxchange.writer:Warning: dxfile module not found
WARNING:dxchange.reader:spefile module not found
WARNING:dxchange.reader:netCDF4 module not found
WARNING:dxchange.reader:EdfFile module not found
WARNING:dxchange.reader:astropy module not found
WARNING:dxchange.reader:olefile module not found
```

and when running _doc/demo/gridrec.ipynb_  at input 7 I get this error message

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-3b27fe0d3af9> in <module>()
----> 1 proj, flat, dark = dxchange.read_aps_32id(fname, sino=(start, end))
      2 print proj

ValueError: too many values to unpack
```

any clue to solve this problem ?

cheers Ian

**Comment by decarlof** [comment]
The second is because the current exchange returns theta. Docs are not update till we roll the new built version. The first are dxchange dependencies I thought doing a conda install they should be solved.

**Comment by dgursoy** [comment]
I think this is not an issue anymore
