### ISSUE TITLE
Problem loading "libtomopy.pyd"

### ISSUE THREAD

**Issue by teracamo** [tomopy/tomopy#271]
Tomopy works fine on Windows 10 ipython. However, when I try to script with pyCharm and run, the code always goes wrong when loading the library. 

`c_shared_library('libtomopy')` always raise error at `ctypes._dlopen(...)`

I tried on iPython, if I directly load "libtomopy.pyd" with `ctypes._dlopen`, it will go wrong unless I 
`import pyffwt` first, which is quite strange. This trick doesn't work in python scripts. In fact this trick only works in iPython and not even in normal python console.

Would love to get this solved.

**Comment by teracamo** [comment]
I forgot to mention, the error was 
```WindowsError [126]: The specified module could not be found.```
I checked online, and tried to install msvc redist c++, doesn't work.

**Comment by teracamo** [comment]
I tested it on linux platform for my build and loading libtomopy.so with ctypes._dlopen() seems normal.

**Comment by newville** [comment]
@teracamo: these should probably be using `ctypes.windll.LoadLibrary()` on windows and `ctypes.cdll.LoadLibrary()` on linux and darwin.

**Comment by teracamo** [comment]
@newville 

> these should probably be using ctypes.windll.LoadLibrary() on windows and ctypes.cdll.LoadLibrary() on linux and darwin.

I have tested both function on the window machine, both doesn't seems to be working, or are they pointing to the same function for windows as an overload?
