### ISSUE TITLE
Reconstruction with tiff_stack

### ISSUE THREAD

**Issue by Bonzey** [tomopy/tomopy#274]
Hello

Let me start by saying I'm new to Tomopy, so if this is simplistic, please forgive me .  I obtained a series of tiff images and am trying to reconstruct the original object using tomopy.io.reader.read_tiff_stack [http://tomopy-dmpelt.readthedocs.io/en/build_without_c/source/api/tomopy.io.reader.html](url).  All images are in a given folder.  However I'm having issues getting the data to reconstruct as a 3D object.  Any help would be appreciated.

**Comment by skylarjhdownes** [comment]
Are you getting an error when you try to read the images, or when you try to reconstruct?  Can you post the output?

**Comment by Bonzey** [comment]
I'm not currently getting error messages, I just know from software reconstruction on the data collection tool that I'm not getting appropriate results.  My goal is to retrieve a 3D object, from which I would then be able to analyze the results (observe sections, rotate/pivot the 3D object, etc).  I understand that ASTRA may be required for some of this additional functionality, so I'm first just trying to get the basic model reconstructed.

Here is a screenshot of the jupyter code and output

![90per_xray_test_screenshot](https://user-images.githubusercontent.com/30665703/28889135-9680d668-77b2-11e7-806d-19028ba0c78f.jpg)

**Comment by dgursoy** [comment]
It seems you are previewing the top reconstructed slice, which may be empty. How about you try:

```plt.imshow(rec[400], cmap='Greys_r)```

I am not sure what ndarray is. If it is a cylinder then the reconstruction looks fine. So, could you print the shape of ndarray and tell us more about which axes is corresponding to slices?

**Comment by decarlof** [comment]
@Bonzey may you you confirm the rotation axis is in the right direction on the projection images (vertical to the image columns)?

**Comment by Bonzey** [comment]
The original object imaged is a rectangular box.  Software from the original tool which performed the scan returned the following results, which I am now trying to replicate (and thereby allow for additional analysis).

![image](https://user-images.githubusercontent.com/30665703/28938726-8de86f64-7854-11e7-932b-2e24df13ef44.png)

Looking through the TIFF files, they appear to be rectangular slices which should be stacked on top of each other to recreate the original object, not necessarily a rotation.  If angle of 0 is entered in input [6] for ang, the output is a plot box.

@dgursoy - putting rec[400] in the plt.imshow command yields an index error, stating "index 400 is out of bounds for axis 0 with size 2."  According to the dxchange.reader.red_tiff_stack documentation, ndarray is the 3D image output.

**Comment by decarlof** [comment]
@Bonzey would be possible for you to share the raw tiff projection data?

**Comment by Bonzey** [comment]
The following is a link to the images I received: [https://drive.google.com/file/d/0B4ZhRKQDsvmFQmVRRDRIdzFMdnc/view?usp=sharing](url)

**Comment by decarlof** [comment]
@Bonzey the images you received are already reconstructed slices. To obtain the 3D rendering you just load them as a stack in a 3D rendering software like [dragonfly](http://www.theobjects.com/dragonfly/).
Loading this stack of images in tomopy then project and reconstruct will bring you back to the same image. In fact this is what I see in the jupyter notebook you sent earlier. Am I missing something?

**Comment by Bonzey** [comment]
Dragonfly is working excellent.  Thank you for the suggestion.
