### ISSUE TITLE
no success building/installing/using tomocuda

### ISSUE THREAD

**Issue by mdrkok** [tomopy/tomopy#328]
Hi,
I've been trying to implement tomocuda to squeeze a little more speed out of some filters as is mentioned in the docs. I've had zero success getting it to function in anyway. Does anyone actually use it and could help me out with installing it?

Thanks,

Matt

**Comment by zronaghi** [comment]
I just tested tomocuda on a Titan X (Pascal). If you're using the latest tomopy with python 3.6.5 you can convert tomocuda from 2 to 3, pip install cython and install tomocuda: python setup.py install
Running python test.py outputs: 
('end cuda filter', 0.767618908546865)
('end cpu median filter', 0.16825182270258665)
('the times gpu over cpu is', 0.2191866573754605)
True
('end cuda outlier removal', 0.031111382879316807)
('end cpu outlier removal', 0.1331795947626233)
('the times gpu over cpu is', 4.2807352948352095)
True

**Comment by dgursoy** [comment]
@mdrkok did it work?
