### ISSUE TITLE
Can't install TomoPy in Enthought Canopy in Windows 10

### ISSUE THREAD

**Issue by salahsabri** [tomopy/tomopy#330]
I couldn't install TomoPy. I tried even with Anaconda and still can't install it.
Could anyone suggest me of a way to install it.

Thanks 

Salah

**Comment by newville** [comment]
@salahsabri Tomopy can be built on Windows, though probably only for Python 3.5 or higher, and probably not with MSVC.  See #310 for a PR that allows Tomopy to be built with MinGWw64 6.3.0 for Anaconda Python.  It may be possible to modify this to build for other versions, though I doubt building for Python 2.7 will be worth the effort required.

There are a few potential challenges with making Windows support better.  First, gridrec was changed to use C99 Complex, which is not supported in MSVC, so MinGW or other compilers must be used. Second, the setting of compiler options to find uninstalled headers and `.lib` files such as `mkl_rt.lib` in setup.py will probably always be fragile and need periodic attention.  PR  #310 follows Anaconda packaging conventions to find the `mkl_rt.lib` file that is needed for the build but not actually installed for Anaconda.

Unfortunately, like @carterbox says, support for Tomopy on Windows is absent.
