### ISSUE TITLE
New release or improved source install instructions?

### ISSUE THREAD

**Issue by chrowe** [tomopy/tomopy#331]
I was trying to follow https://tomopy.readthedocs.io/en/latest/ipynb/vector.html and it seems that `tomopy.project3` does not work in the current release but was added back in April https://github.com/tomopy/tomopy/commit/28a12c25db771efd37ee7b23b9141fc4a030677c

Also, the[ instructions to install from source](https://tomopy.readthedocs.io/en/latest/install.html#id3) are not clear to me so I am stuck on that rout as well. I would be happy to submit a PR to improve these docs if I can figure out how to do it myself.

Thanks

**Comment by carterbox** [comment]
Hi @chrowe, thanks for you patience. I think many key people are on vacation right now. What trouble in particular are you having with the installation from source?

**Comment by chrowe** [comment]
I was stuck on how to install dependencies so https://github.com/carterbox/tomopy/commit/37b1c8f7bbaf90c6fbd2c949a7cd7b6f567117df#diff-f2202167afc438a107cf9f73ac4f9fb1R71 got me over that hump.

But when I run that I get...
```
$ conda install --file requirements.txt
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - futures
  - tomopy
Use "conda info <package>" to see the dependencies for each package.
```

I am running this on and AWS EC2 image based on https://aws.amazon.com/marketplace/pp/B07CNFWMPC with tomopy already installed via `conda install -c conda-forge tomopy`.

**Comment by carterbox** [comment]
If you install TomoPy from using Conda from the `conda-forge` channel, then it installs the dependencies automatically.

If you're building your own copy of TomoPy from source, then you need to uninstall the one from `conda-forge` because it will take precedence over the version that you build.

You're probably getting the `UnsatisfiableError` because `futures` is only needed for `python2.7` and you're running `python3.x`. Sorry, I didn't realize the requirements on `futures` was `python<3`.  You can just remove futures from your copy of `requirements.txt`.

**Comment by chrowe** [comment]
## Requirements
```
conda remove tomopy
conda install --file requirements.txt
conda install mkl-devel
```
Not sure if `mkl-devel` is needed but I installed it since [you mentioned it](https://github.com/carterbox/tomopy/commit/37b1c8f7bbaf90c6fbd2c949a7cd7b6f567117df#diff-f2202167afc438a107cf9f73ac4f9fb1R85).

That seems to have worked, though it just says
`# All requested packages already installed.`

## gcc
Then I get...
```
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
```
So I install `gcc`
```
yum install gcc
```
Maybe this should be listed as a dependency somewhere?

## C_INCLUDE_PATH
Then I get a similar error to the one described in https://github.com/carterbox/tomopy/blob/37b1c8f7bbaf90c6fbd2c949a7cd7b6f567117df/doc/source/install.rst#id5
so I ran...
` export C_INCLUDE_PATH=/opt/conda/include`

## WIN!
And now it seems to have built 👍 
And `tomopy.project3` works 👍

**Comment by carterbox** [comment]
#174
