### ISSUE TITLE
Large unused files in commit history

### ISSUE THREAD

**Issue by newville** [tomopy/tomopy#335]
it looks like the tomopy repository grep by about 200 Mb between 1.1.2 and current master.  

Please remove large files from past commits.

**Comment by carterbox** [comment]
[This bash script] (https://stackoverflow.com/a/42544963) tells you how much space each item in your git history is taking up.

```bash
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

The result for tomopy is here:

```bash
...
215d76149660   11MiB data/large.h5
1807b4ef32f6   19MiB tomopy/data/vector/object_1/M4R1_my.tif
6dde9077c7a4   19MiB tomopy/data/vector/object_1/M4R1_mx.tif
c84c3e8c8b44   19MiB tomopy/data/vector/object_1/M4R1_mz.tif
554a35b7472a   25MiB data/demo.h5
a5c0234b90db   28MiB data.h5
8c9d01432752   91MiB tomopy/data/vector/full_projections_heterostructure/Xt_dNeg_m90-901deg_Tomo.hdf5
8ff0d5a1a872   91MiB tomopy/data/vector/full_projections_heterostructure/Yt_dNeg_m90-901deg_Tomo.hdf5
ae9b4e717657   91MiB tomopy/data/vector/full_projections_heterostructure/Xt_dPos_m90-901deg_Tomo.hdf5
c133bb1d328b   91MiB tomopy/data/vector/full_projections_heterostructure/Yt_dPos_m90-901deg_Tomo.hdf5
```

Apparently at some point, someone commited some 90MiB hdf files, but they aren't in use now.

**Comment by newville** [comment]
@carterbox  Yes, and those large files are still in the repository history even if they are not in any of the current branches. Please remove large unused files from the repository history.

**Comment by carterbox** [comment]
We should probably remove all files larger than 10MiB from the repo, but editing these files out of the git history will disrupt the main branch and cause everyone to need to rebase their work on the edited master branch. We would probably use `git filter-branch` or [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) accomplish this task.

Also, we could prune off `gh-pages` @decarlof and `develop` @dgursoy branches, because those were last used 4 years ago.

**Comment by dgursoy** [comment]
This is after the addition of vector field reconstructions and I believe these files are used for docs and/or testing. I think we can easily remove them.

**Comment by dgursoy** [comment]
Yay!

**Comment by carterbox** [comment]
The alternate history isn't uploaded yet. :stuck_out_tongue:

**Comment by carterbox** [comment]
So basically, I just renamed every commit since 2016, so now everyone has to reclone the repository / rebase in order to get the smaller version of the repository.

**Comment by decarlof** [comment]
nice!

**Comment by newville** [comment]
@carterbox Thanks!
