### ISSUE TITLE
test_distribute_jobs tests fail for python2.7 Windows build

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#340]
@newville, Did you get this error on your builds of tomopy after running `nosetests`?

I think what is happening is that `distribute_jobs` is failing because the workers can't resolve the test module that they are called from, but I'm kinda stumped on what to do about it.
```
Traceback (most recent call last):
ImportError: No module named 'test.test_util'
  File "C:\Users\dchin\Miniconda3\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Users\dchin\Miniconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dchin\Miniconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\dchin\Miniconda3\lib\multiprocessing\queues.py", line 337, in get
    return ForkingPickler.loads(res)
======================================================================
ERROR: test_distribute_jobs (test.test_util.test_mproc.TestDistributeJobs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dchin\Documents\tomopy\test\test_util\test_mproc.py", line 110, in test_distribute_jobs
    axis=0),
  File "C:\Users\dchin\Documents\tomopy\tomopy\util\mproc.py", line 249, in distribute_jobs
    "Child process terminated before finishing")
RuntimeError: Child process terminated before finishing
```

I also have some other errors and warnings, but I can't blame them on changing environments just yet.

**Comment by newville** [comment]
@carterbox  I do not see that. 

I do see 2 failures in `test_recon/test_algorithm.py` for testMethods of `test_grad` and `test_tv`.

**Comment by carterbox** [comment]
@newville Which `python` are you using? `python 3.x | Anaconda,  Inc ` from the `default` channel on `Windows 10 x64`? Maybe I'm missing a dependency or it's a quirk of the version I'm using.

Nice job on this build system BTW, I like how it works.

**Comment by newville** [comment]
I'm using pretty generic python 3.6.6 anaconda python, root environment for
x86_64.     I don't know why multiprocessing fetching of pickled data would
be different on Windows, but I don't have a lot of experience with that.

**Comment by carterbox** [comment]
The error above is only for `python2.7`, so I'd rather just not support that version for Windows.

**Comment by dgursoy** [comment]
+1

**Comment by newville** [comment]
I agree with not bothering with Windows support for Python 2.7.  There are no legacy users to worry about.
