### ISSUE TITLE
ValueError: need more than 3 values to unpack

### ISSUE THREAD

**Issue by georgeha** [tomopy/tomopy#346]
At this file:
```
https://github.com/tomopy/tomopy/blob/master/doc/source/ipynb/tomopy.rst
```

This command does not work:
```
proj, flat, dark, theta = dxchange.read_aps_32id(fname, sino=(start, end))
```

**Comment by dgursoy** [comment]
This is true for older versions of ```dxchange```, where ```theta``` is not included in the outputs. Could you update the package and give it another try (or simply drop ```theta``` from your output list)?

**Comment by georgeha** [comment]
Thanks, both solutions work!
