### ISSUE TITLE
align_seq needs center shift control?

### ISSUE THREAD

**Issue by jefferton-sg** [tomopy/tomopy#351]
Hey all, long time fan, first time caller...

I've been tinkering with the align_seq routine for projection image alignment but I think it needs a control for the center shift. While I've "fixed" this on my end by adding another call to find_center inside the align_seq code, I suppose it would make more sense to have center shift as an optional argument when calling align_seq (so the reconstruction procedure would then only need to do that once). Of course if drifts are REALLY bad, then the center shift finding might need to be done with every iteration of align_seq... in that case, the right place would be inside align_seq itself. 

Any thoughts?

**Comment by carterbox** [comment]
Thanks for you idea! It looks like @dgursoy is the last person to have touched [`align_seq`](https://github.com/tomopy/tomopy/blob/788aaf43ff3db9392629ad0c10f4b29db31063f6/tomopy/prep/alignment.py#L75-L166). He is at a conference this week, but I'll be sure to remind him in person to address this issue when he returns. Thanks for your patience. :smile:
