### ISSUE TITLE
GPU options for align_seq and align_joint (backprojection and forward projection)

### ISSUE THREAD

**Issue by jdgelb** [tomopy/tomopy#358]
Could we get an option for full GPU acceleration in the dataset alignment routines? I think there is progress being made on the backprojector, but it would be great to get this option in the forward projector too. However, I think that means that we need a wrapper for the ASTRA forward projection added as a utility, so that it can be called by align_seq and align_joint... unless I'm missing something, the ASTRA Toolbox is only available for backprojection at the moment?

**Comment by samwelborn** [comment]
I have implemented code for this that requires:
1. Edits to skimage source and 
2. Addition of cupy to requirements list.

The logic is as follows: 
1. Use Astra SIRT_CUDA to reconstruct.
2. Use Astra to reproject.
3. Use pycuda/skimage for ffts.

My code _dramatically_ reduces the iteration time (for tomo_077 on tomobank, my time dropped from something like 8 mins per iteration to about 1 min 25 seconds). I get the same result. I could definitely use some help to make it better, especially with the reprojection part using astra.

How should I upload this? I am new to github, so I do not know how to upload things like changes to dependency packages.

@dgursoy @carterbox
