### ISSUE TITLE
Gridrec zero frequency behavior

### ISSUE THREAD

**Issue by dmpelt** [tomopy/tomopy#362]
For a project we are using the tomopy gridrec `custom` filter option. We noticed that the zero frequency of the projection data is always set to zero, even if the filter component of the zero frequency is nonzero. The easiest way to test this is to 'backproject' a constant sinogram, e.g.:

```
import tomopy
import numpy as np
data = np.ones((64,1,256),dtype=np.float32)
ang = np.linspace(0,np.pi,64,False)
tomopy.recon(data, ang, algorithm='gridrec', filter_name='custom', filter_par=np.ones(257,dtype=np.float32))
```
This returns a zero array. The same also happens if you simply try to reconstruct a constant sinogram using the standard filter.

Is this expected behavior? I can imagine that it is (I've seen other reconstruction codes explicitly set the zero frequency to zero), but it would be good to know!

**Comment by dgursoy** [comment]
This can be related to #395.
