### ISSUE TITLE
Proposal: Reduction of dependencies

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#377]
I propose the following actions in order to reduce the installation footprint of TomoPy:

- [ ] Remove unused dependencies from entire project
- [x] Replace rarely used imports with equivalent functions from frequently used imports
- [x] Separate dependencies which are only used for optional features and testing

Please discuss why or why not these things should be done.

## Unused dependencies
If dependencies are never actually called by functions within the project, they should not be dependencies.

- [ ] Does anyone actually use the FFTW backend anymore? https://github.com/tomopy/tomopy/pull/375#issuecomment-445991938 Probably not. It shall be removed.

## Rarely used imports
Importing an entire library for one function may not be appropriate.
- [x] Drop hard dependency for ```dxchange``` in ```alignment``` and ```recon``` modules. It is used for writing TIFF images only. Use `tifffile` or some other library instead? (#383)
- [x] ~~Drop dependency to ```pywt.dwt2``` and ```pywt.idwt2```  in ```stripe``` module. Use ```from tomopy.util.misc import (fft2, ifft2)``` instead.~~
    - Not valuable since `pywt` is a dependency of `scikit-image`.
-  [x] ~~`scikit-image` is only used for resizing images in `tomopy.misc.phantom`. Perhaps, it's not appropriate to depend on the entirety of `scikit-image` for such a rarely used feature.~~
    - We use the ```register_translation``` in ```skimage.feature``` and ```transform```  in  ```skimage```. The common use is for calculating the rigid registration parameters of two images and auto-centering of the rotation center in tomographic reconstruction.
## Keep testing dependencies separate
Dependencies that are only used for testing should not be included in the final package that is distributed to users.  (e94e4d582503a)

**Comment by dgursoy** [comment]
I think all three points make sense. 

Some notes to remember:
- We use the ```register_translation``` in ```skimage.feature``` and ```transform```  in  ```skimage```. The common use is for calculating the rigid registration parameters of two images and auto-centering of the rotation center in tomographic reconstruction.
- Drop dependency to ```pywt.dwt2``` and ```pywt.idwt2```  in ```stripe``` module. Use ```from tomopy.util.misc import (fft2, ifft2)``` instead.
- Drop dependency to ```dxchange``` in ```alignment``` and ```recon``` modules. It is used for writing TIFF images only.

**Comment by carterbox** [comment]
PyWavelets is also dependency of scikit-image, so it's not really valuable to refactor `stripe` if that won't reduce the dependencies. (Also, I looked at the code, and I wouldn't know how to do what you're suggesting).

**Comment by carterbox** [comment]
This is the approximate list of dependencies which are no longer required by recategorizing `dxchange` as a soft dependency. Some dependency changes may be indirect because of changes to other dependencies.

```
bzip2:            1.0.6-h470a237_2           conda-forge
cftime:           1.0.3.4-py36h7eb728f_0     conda-forge
curl:             7.63.0-h74213dd_0          conda-forge
dxchange:         0.1.5-py36_0               conda-forge
dxfile:           0.5-py_1                   conda-forge
edffile:          5.0.0-py36_0               conda-forge
h5py:             2.8.0-py36he5c79e1_5       conda-forge
hdf4:             4.2.13-h951d187_2          conda-forge
hdf5:             1.10.4-nompi_h5598ddc_1003 conda-forge
krb5:             1.16.2-hbb41f41_0          conda-forge
libcurl:          7.63.0-hbdb9355_0          conda-forge
libedit:          3.1.20170329-haf1bffa_1    conda-forge
libnetcdf:        4.6.2-h85b088c_0           conda-forge
libssh2:          1.8.0-h5b517e9_3           conda-forge
netcdf4:          1.4.2-py36hf4e5497_1       conda-forge
pytz:             2018.7-py_0                conda-forge
spefile:          1.6-py_1                   conda-forge
```
