### ISSUE TITLE
Proposal: Increase the number of build targets

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#378]
With the help of @jrmadsen, we are replacing the current build system with cross-platform make (CMake) and scikit-build (#375). Now is a good time to discuss the platforms, architectures, and compilers that we will support with the new CMake build system.

The current list is:

- MacOS x64
  - Clang (conda) - default
- Linux x64
  - GCC (conda) - default
  - Intel (version 18.0.3)
  - PGI (version 18.4 and 18.10) - for OpenACC 
- Windows 10 x64
   - GCC (conda) - for easier cross platform compatibility

**Comment by jrmadsen** [comment]
So here is a summary of the compilers that I have tested and verified as working using system compilers:

- Linux
  - GCC (`/usr/bin/gcc`)
  - Clang (`/usr/bin/clang`)
  - Intel (version 18.0.3)
    - this requires setting `-fp-model=precise` flag, which I will update in branch
  - PGI (version 18.4 and 18.10)
- macOS
  - GCC (macports)
  - AppleClang (i.e. `/usr/bin/clang`)
  - Clang (macports)

Note: CMake will use whatever compiler is set in env variable `CC`, e.g. `export CC=/usr/bin/gcc`.

**Comment by carterbox** [comment]
@jrmadsen Why test Macports GCC and Clang? Is is because setting up CMake for Linux GCC and Apple Clang is the same?

**Comment by jrmadsen** [comment]
I keep the macports versions around mostly because they are much closer to duplicates of the GCC and Clang provided on Linux because Apple's Clang is somewhat different than the open-source Clang and `/usr/bin/gcc` on macOS is actually LLVM, not GCC.

In general, by using the macports GCC and Clang, it is pretty safe to assume that if it compiles on macOS, it will compile on Linux with those compilers.

**Comment by jrmadsen** [comment]
Well that's the case for TomoPy now but that's not exactly the case for some of the other work -- we are implementing CUDA, OpenMP, and OpenACC for GPU offloading the iterative algorithms (as a study of implementation complexity, performance, and portability) and OpenACC requires PGI or Clang (PGI is far superior to Clang at this point) and GCC for OpenMP. And with the ability to query flags, etc. in CMake it's not that difficult to provide that support in the short term. In the long term, I would agree that explicitly supporting that many compilers is a bit unnecessary.

**Comment by jrmadsen** [comment]
All these compilers + MSVC are supported in 1.5.x
