### ISSUE TITLE
installation problems and solutions on Ubuntu 18.04

### ISSUE THREAD

**Issue by hijizhou** [tomopy/tomopy#385]
_This problem may not be common, but I would like to record it to benefit possibly similar environments._

I am having a new installed Ubuntu 18.04, with Python 3.6.  Following the [instructions](https://tomopy.readthedocs.io/en/latest/install.html) of installing from source with Conda with the latest version. I need to have some changes to successfully built tomopy:

**1.  *dependencies***
`$ conda install --file requirements.txt`
Shows following errors:

> CondaValueError: could not parse 'futures ; python_version < "3"' in: requirements.txt

I understand it, which is a backport of the concurrent.futures standard library module to Python 2, should not be installed on Python 3. I then tried to use `conda env create -f meta.yaml`, 

>  ruamel_yaml.constructor.ConstructorError: while constructing a mapping
      in "<unicode string>", line 16, column 7:
            - {{ compiler('c') }}  # [not win]
              ^ (line: 16)
    found unhashable key
      in "<unicode string>", line 16, column 8:
            - {{ compiler('c') }}  # [not win]
               ^ (line: 16)

 So I fixed it by removing the line `futures ; python_version < "3"`.

**2. *install***
`$ pip install .`
Shows following errors:

>  ../src/gridrec.c:57:14: fatal error: mkl.h: No such file or directory
>  #include "mkl.h"
  Failed building wheel for tomopy

It turns out that this issue can be solved by using `mkl-devel` instead, see #317. Thus,

`$ pip install mkl-devel`
`$ pip install .`

Finally, it shows 
> Successfully built tomopy
Installing collected packages: tomopy
Successfully installed tomopy-1.3.0

In fact, I had these installation errors also in my macOS (10.14.2). These steps seem to work as well.

**Comment by carterbox** [comment]
@hijizhou Sorry! The install documentation for developers is out of date.

You're right. `conda` can't read that syntax in `requirements.txt`, and the reason that `mkl-devel` isn't included in `requirements.txt` is that it was originally meant to specify the runtime requirements, not installation requirements.

I've been working on making it easier to setup a dev environment as part of simplifying our CI infrastructure.

**Comment by hijizhou** [comment]
That's great, @carterbox. Thanks for your work on this useful tool.
