### ISSUE TITLE
NumPy v1.16.1 not compatible with TomoPy

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#392]
numpy/numpy#12769 breaks compatibility with TomoPy because `np.ctypeslib._typecodes` no longer exists. Our fault though because `_typecodes` is a non-public function. The relevant line in TomoPy is below:

https://github.com/tomopy/tomopy/blob/9f9a5410c2bf8879db6b4d9e38f3c823b9e3fd0f/tomopy/util/dtype.py#L145

@michael-sutherland, Do you have any suggestions on how to fix this?

**Comment by jrmadsen** [comment]
This appears to work:

```Python
    tarr = np.empty((1), dtype=arr.dtype)
    ctype = type(np.ctypeslib.as_ctypes(tarr)._type_())
```

**Comment by carterbox** [comment]
Thanks, @jrmadsen
