### ISSUE TITLE
Can tomopy reconstruct SPECT data from an Infinia Hawkeye?

### ISSUE THREAD

**Issue by tiago654321** [tomopy/tomopy#399]
Hello!
Does this software work with SPECT data? I have seen alot of applications for x-ray imaging but what about applications for nuclear medicine like SPECT and PET data?
Thank you,
Tiago Galvão

**Comment by dgursoy** [comment]
You can use all algorithms for any emission tomography with parallel beam acquisitions. I would particularly suggest using MLEM, OSEM or their regularized versions, because of the noisy nature of these datasets.

**Comment by tiago654321** [comment]
We have SPECT raw data in DICOM format. Is it possible to generate a sinogram and reconstruct the data?

**Comment by dgursoy** [comment]
Sure. I believe [PyDICOM](https://pydicom.github.io) can be used to read your files, and a script like [here](https://tomopy.readthedocs.io/en/latest/ipynb/tomopy.html) can be used to reconstruct them.

**Comment by dgursoy** [comment]
@tiago654321 I hope you reconstructed your data. For now I'll close this but we can reopen if you have problems.
