### ISSUE TITLE
docs fails to build

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#401]
Please replace 

> requirements-doc.txt

with 

> envs/requirements-doc.txt

in readthedocs dashboard under Admin/Advanced Settings/Requirement files

This should be [here](https://readthedocs.org/dashboard/tomopy/advanced/) when logged in [readthedocs](https://readthedocs.org/) as tomopy adm

**Comment by dgursoy** [comment]
It passes now. Thanks.
