### ISSUE TITLE
Passing CMake args through pyctest_tomopy.py

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#408]
There are two ways to pass CMake parameters when using `pyctest_tomopy.py`. The first is to use the `--cmake-args` parameter and the second is to put the arguments after a second double-minus i.e. `$ pyctest_tomopy.py -- -- -DCMAKE_ARG=foo`. Both are broken?

In the first method, each character of the argument strings was passed separately as in the example below because the provided string is interpreted as a list of chars:
```
$ ./pyctest_tomopy.py --cmake-args="-DCUDA_TOOLKIT_ROOT_DIR='/local/cuda-10.0' -DCUDA_COMPILER='/local/cuda-10.0/bin/nvcc'" -- -VV
...
# some outputs
...
Run command: "/home/beams/DCHING/miniconda3/envs/tomopy36/bin/python" "setup.py" "--hide-listing" "-q" "install" "--" "-" "D" "C" "U" "D" "A" "_" "T" "O" "O" "L" "K" "I" "T" "_" "R" "O" "O" "T" "_" "D" "I" "R" "=" " / l o c a l / c u d a - 1 0 . 0 " "D" "C" "U" "D" "A" "_" "C" "O" "M" "P" "I" "L" "E" "R" "=" " / l o c a l / c u d a - 1 0 . 0 / b i n / n v c c "
```
This method was patched in the following commits: be6f909b6e7b999dc027b3d00168229edd84d65b f03a126a599bd5fc83f069f01448dd1a1557dd4b by having the user remove the minus sign so the arguments could be collected as inputs for the `--cmake-args` parameter. As below:
```
$ ./pyctest_tomopy.py --cmake-args DCUDA_TOOLKIT_ROOT_DIR='/local/cuda-10.0' DCUDA_COMPILER='/local/cuda-10.0/bin/nvcc' -- -VV
```
In the second method, the CMake parameters are collected but never passed along to the install command.

**Comment by jrmadsen** [comment]
I think importing `pyctest.pycmake` and appending the list `pyctest.pycmake.ARGUMENTS` to the `pyctest.BUILD_COMMAND` Should work. That list is where pyctest stores the arguments.

**Comment by jrmadsen** [comment]
I can't test right now but I'll test it out tomorrow if you don't get to it before I do.
