### ISSUE TITLE
tiff stack reconstruction issue

### ISSUE THREAD

**Issue by tplr** [tomopy/tomopy#413]
Hey, 

I was trying to read projection files as tiff files from a folder and somehow it only reads 2 of them even though there are 141 images inside. I used dxchange.reader.read_tiff_stack, and then tried to transpose matrix to make as in examples but it didn't work out well. Maybe I am missing something but I have checked again and everything seems ok. Any suggestion?

```python
from __future__ import print_function
import tomopy
import dxchange
import numpy as np
import math
import matplotlib.pyplot as plt

if __name__ == '__main__':
    
    # Set path to the micro-CT data to reconstruct.
    fname = '/Users/xx/Desktop/xx/xx_0000.tif'
    
    # Select the sinogram range to reconstruct.
    start = 0
    end = 140
    proj=dxchange.reader.read_tiff_stack(fname, ind=(start,end))
    plt.imshow(proj[:, 0, :], cmap='Greys_r')
    plt.show()
    print("proj: ", len(proj))
    # proj: 2
```

**Comment by carterbox** [comment]
Hi @tplr:

From the docs of [`dxchange.read_tiff_stack`](https://dxchange.readthedocs.io/en/latest/source/api/dxchange.reader.html#dxchange.reader.read_tiff_stack)`:
```
    ind : list of int
        Indices of the files to read.
```
This means you should provide _all_ of the indices of the files. You provided two indices, so you got two images.

P.S. @decarlof, please transfer this issue to the dxchange repository.

**Comment by decarlof** [comment]
what is the size [x, y] of each tiff file?

francesco

**Comment by tplr** [comment]
@carterbox 
Thanks for the prompt reply and solution. And sorry for wasting your time with simple indexing mistake. 

@decarlof 
The image size is 1300x1600.

**Comment by carterbox** [comment]
@tplr, no worries. Brain farts happen! :smile:
