### ISSUE TITLE
New GPU accelerated methods fall-back

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#422]
Presently (v1.5.1), if you try to reconstruct with `'accelerated': True, 'device': 'gpu',` but run out of GPU memory, TomoPy will fall back to the original CPU method on a single thread. Is this the desired behavior? Personally, I think TomoPy should throw an error and quit instead of falling back onto an algorithm that I didn't ask for. This is because I would rather adjust the chunk size that I am providing to TomoPy and use the GPU method instead of waiting for the slower single threaded CPU method to complete.

Jonathan also suggested we could recreate a thread pool, so that the fallback runs on multiple CPU threads.

Does anyone have additional thoughts or arguments the other way?

**Comment by dgursoy** [comment]
Agreed. Also because we don't have yet a good logging/warning schemes implemented in TomoPy, I'd avoid these fallbacks.

**Comment by carterbox** [comment]
How can we make these fallbacks detectable by our testing suite such that automated tests are skipped when CUDA hardware is not available?

**Comment by jrmadsen** [comment]
As in not generate a test in PyCTest at all?

**Comment by carterbox** [comment]
I'm talking about correctness/consistency tests located in `tests/`

https://github.com/tomopy/tomopy/blob/1a5efd87d8af1047cb25a2d5d031e1649597a287/test/test_tomopy/test_recon/test_algorithm.py#L150-L155

I want to be able to automatically test the pre-built w/ CUDA conda distribution for correctness. As far as I know, the `pyctest` script is not implemented with this use case in mind.
