### ISSUE TITLE
Request for x-ray diffraction tomography algorithms

### ISSUE THREAD

**Issue by YoshieraHuang** [tomopy/tomopy#423]
Does `tomopy` implement xray diffraction tomography (XDT) sub-module memtioned at the paper?  I looked at the code roughly but can't find the XDT sub-module.

**Comment by dgursoy** [comment]
Which paper are you referring to?

**Comment by YoshieraHuang** [comment]
> Which paper are you referring to?

[TomoPy: a framework for the analysis of synchrotron tomographic data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4181643/)
this is the part in 3rd section:
>Each module can have a number of different sub-modules specific to targeted application (e.g. XTT, XFM, XDT).

**Comment by carterbox** [comment]
@dgursoy, What about x-ray diffraction tomography?

**Comment by dgursoy** [comment]
Not much yet. Sorry.

**Comment by newville** [comment]
@YoshieraHuang  we have used tomopy for reconstructing both fluorescence and diffraction tomography data.  I would say that for fluorescence tomographic data the results are successful - there can be large attenuation factors but these are mostly smooth.  They inhibit an accurate quantitative analysis of the XRF spectrum to get elemental abundance per voxel.  To first order, these effects can be understood and sort of fixed.  I think some people have done iterative methods to try to improve the reconstructions.  I think this can work if the sample has a pretty uniform total composition and the fluorescing elements are at trace concentrations.  Our approach is generally that rotating a full 360 degrees helps and adds only minutes to the data collection and helps significantly if not perfectly.  Even if not perfectly corrected (especially low Z elements), the imaging aspect to locate the presence of elements works very well.

There are definitely more significant artifacts in the diffraction tomography data.  Unlike absorption, the diffraction signal from a voxel does intrinsically depend on the angular orientation of the sample with respect to the beam.  This results in incomplete or even speckly sine-waves in the diffraction sinogram.  

Our experience is that partial sinograms are not a disaster - the intensity of the reconstructed voxel is not necessarily meaningful, but we can identify spatial location of certain diffraction reflections. What is more problematic is that we'll get occasional very bright peaks or streaks that are not at all sinusoidal in a sinogram.  These are likely from very strong scattering and/or measurements artefacts (camera memory from very bright peaks that persists in time comparable to the frame time), or may even be from non-linear dynamic scattering effects.   We don't have good methods for cleaning these up.  But even without these we can do some phase identification of the almost-powdery incomplete sinusoidal portions of the data. I believe that folks at ESRF have more experience with diffraction tomography than we do. I think they are not using tomopy, but I'm not sure.

Methods to improve these artefacts would be great.
