### ISSUE TITLE
Calcululate the projection from the top of an object

### ISSUE THREAD

**Issue by thorstenwagner** [tomopy/tomopy#433]
I've a 3D volume and want to calculate the projection from top. 
I'm using tomopy.sim.project.project

However, as I can only specify theta  I don't know how to do this.

Any help is appreciated.

Best,
Thorsten

**Comment by thorstenwagner** [comment]
I could use volume3d_rot = scipy.ndimage.rotate(volume3d,45) to rotate the volume in the first place but this seems to be not very efficient...

**Comment by dgursoy** [comment]
I can add projectors along different axes in a new PR. Do you need arbitrary projectors as well, e.g. qt 30 degrees off from rotation axis?

**Comment by thorstenwagner** [comment]
Yes, exactly. Top view was just an example

**Comment by thorstenwagner** [comment]
But as far as I see I cannot calculate a reconstruction based on projection image with rotation using tomopy or astra, right? Both seem to expect that there is only the theta angle...

**Comment by dgursoy** [comment]
Sure, but beware that arbitrary projectors will be much slower than along-axis projectors, because they can’t be written in terms of a series of identical 2D projectors along an axis. Another option is to use ASTRA projectors. For this you need to provide your geometry options as a dict to ASTRA.

**Comment by dgursoy** [comment]
Related to #456 for calling ASTRA projectors on different geometries.
