### ISSUE TITLE
Ring artifact removal shifts part of image

### ISSUE THREAD

**Issue by meetaig** [tomopy/tomopy#437]
**Describe the problem**
When using the ring artifact removal `tomopy.misc.corr.remove_ring`, part of the image gets shifted by a few pixels. This might be due to me not using it correctly, or it might be a bug.

**To Reproduce (if applicable)**
Just use the `remove_ring` as outlined in the documentation.

```python
import tomopy

if __name__ == "__main__":
    center_coord = [75.3, 239.5]
    image_data_corr = tomopy.misc.corr.remove_ring(image_data.T, center_coord[0], center_coord[1], thresh_min=0.25, thresh_max=0.52).T  # image_data is a normalized numpy array with shape  [480, 108]
```

**Expected behavior (if applicable)**
The resulting image should have ring artifacts removed, if possible, but generally be aligned with the input, regardless of the success of the artifact removal.

**Helpful images (if applicable)**
![ring_artifact_removal_shift](https://user-images.githubusercontent.com/18595989/62276691-e7b9cc80-b444-11e9-9b2b-1dc649817f5f.png)
In the figure you can see the uncorrected image and the result of the ring correction with a difference image added to highlight where the shift happens.

**Platform Information:**
 - OS:  LinuxMint 18.1
 - Python Version: Python 3.6.8 :: Anaconda custom (64-bit)
 - TomoPy Version: 1.2.1

**Comment by carterbox** [comment]
@lbluque, Can you help with this?

**Comment by lbluque** [comment]
Sure thing. Once I find a bit of time, I'll have a look.
