### ISSUE TITLE
Error: install from source in macos

### ISSUE THREAD

**Issue by smajee** [tomopy/tomopy#439]
Installation error in mac os when running:
`python setup.py build`
Dependencies have already been installed.

Error happens in the PTL module.

gcc details:
`gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

Error details:
[error_msg.txt](https://github.com/tomopy/tomopy/files/3469448/error_msg.txt)

**Comment by jrmadsen** [comment]
It looks like your Xcode SDK is pretty out of date (v10.11 instead of v10.14) so you've likely got an older compiler without robust C++11 support. Try upgrading Xcode or passing `--disable-tasking` as an extra argument to the `python setup.py install`

**Comment by smajee** [comment]
Passing `--disable-tasking` solved it.
Thanx.
