### ISSUE TITLE
Install error in linux (install from source)

### ISSUE THREAD

**Issue by smajee** [tomopy/tomopy#440]
Error during installation from source in a linux cluster.

Steps performed:
1.   Download: `wget https://github.com/tomopy/tomopy/archive/master.zip`
2.  Unzip and cd to tomopy directory
2.  Create new environment: `conda env create -f envs/linux-36.yml`
4.  Install tomopy: `pip install .`  (ERROR)

Error happens in cmake.

Error details:
[tomopy_install_error.txt](https://github.com/tomopy/tomopy/files/3473427/tomopy_install_error.txt)

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by prjemian** [comment]
Did not see you name the new environment (with -n my_new_envo or 
similar).  Is that in the YAML file?

**Comment by smajee** [comment]
Yes, the environment name is sourced from the linux-36.yml file. 
The name is set to tomopy in the first line of  linux-36.yml.
> Did not see you name the new environment (with -n my_new_envo or similar). Is that in the YAML file?
> […](#)
> On 2019-08-06 12:27 PM, Soumendu Majee wrote: # Create new environment: |conda env create -f envs/linux-36.yml|

**Comment by carterbox** [comment]
You can't build from the github tarball because it doesn't include PTL. Maybe disabling tasking will work? Otherwise, you need to use git to checkout the repository.

**Comment by smajee** [comment]
Is there a way to accomplish this without cloning from git?
I don't have the necessary permissions to do git clone in the machine.

I have tried cloning it in another computer and then transferring the files, but this leads to errors since git clone downloads files specific to the machine os.

**Comment by smajee** [comment]
That worked.
Thanx.
