### ISSUE TITLE
Tiff Stack TomoPy Reconstruction

### ISSUE THREAD

**Issue by oobie2142** [tomopy/tomopy#445]
**Describe the problem**
I am having a problem with reconstruction of a sample using side profiles. Attached is the image of what I want to reconstruct, sample output, and a sample of a projection I have as data. Am I misunderstanding how the algorithms work? Or do I have to alter the way Tomopy understands the axis of rotation for my specific specimen?

Thanks!

**My Code**
```python
import tomopy
import dxchange
import matplotlib.pyplot as plt

fname = '/home/oobie2142/Documents/EDensityTiff/Converted_To_Tiff/'

im_start = 0
im_end = 900
ind_image = range(im_start, im_end)

#Adjusted pixel sizes to match flat and dark panel size
flat = dxchange.read_tiff('/home/oobie2142/Documents/EDensityTiff/lite_1024avg.tif', slc=((150, 150+422, 1),(30,30+876,1)))
dark = dxchange.read_tiff('/home/oobie2142/Documents/EDensityTiff/dark_1024avg.tif', slc=((150, 150+422, 1),(30,30+876,1)))

proj = dxchange.read_tiff_stack(fname + 'Projection0.tif', ind_image)
new_proj = tomopy.normalize(proj, flat, dark)

# This is where I am confused if I am passing the correct center of rotation to the reconstruction function. 
rot_center = tomopy.find_center(new_proj, ang, init=450, ind=51, tol=0.5)
rec = tomopy.recon(new_proj, ang, center=rot_center, algorithm='art') 

plt.imshow(rec[60,:,:])
```
![IMG_0699](https://user-images.githubusercontent.com/7355790/63316704-0c2ef900-c2cd-11e9-9cc8-86eb78e5542f.JPG)
![test_recon](https://user-images.githubusercontent.com/7355790/63316854-bdce2a00-c2cd-11e9-9578-29efd8fa5cfc.png)
![Projection51](https://user-images.githubusercontent.com/7355790/63316961-32a16400-c2ce-11e9-968e-a5b4f5d9a19d.png)
```

**Comment by oobie2142** [comment]
My apologies I forgot to add that I am using a tiff stack for these projections.

**Comment by carterbox** [comment]
It looks to me like you're using the API correctly. What rotation center does `tomopy.find_center(...)` actually return? Optimization methods can be unstable and return something wildly wrong.

The automatic methods may not work for your object. If that's the case, you can use `tomopy.write_center(...)` to manually find the correct rotation center.

**Comment by oobie2142** [comment]
Hey @carterbox thanks for the reply. I got a center of approximately 430. The slice given is the 400th slice of the reconstructed object. The data is 422 X 876, should I trim off the extra white space?

Also are there rules of thumb in determining which algorithm to use?

**Comment by carterbox** [comment]
Yes to trimming vertically. There's no point in reconstructing empty slices! :smile: 

No rules of thumb that I know. If you're super interested, you can read the cited sources in the docs. Otherwise, just work your way down the list? Make sure you're finding the center of a slice that actually has object in it and check that your angles are defined correctly.

Let me know if it works or not.

**Comment by oobie2142** [comment]
I will give it a shot and report back. 

Thanks!

**Comment by oobie2142** [comment]
![sample_crop](https://user-images.githubusercontent.com/7355790/63402901-41554d00-c39a-11e9-89c9-7bf24965c380.png)
![reconstruct](https://user-images.githubusercontent.com/7355790/63402904-43b7a700-c39a-11e9-98f3-67c5221301c4.png)

Hey @carterbox, 
Attached is the sample cropped image of my data and a reconstruction. I used the filter back projection algorithm for this reconstruction. Would the distance between the source and the specimen or detector matter in the reconstruction? Am I using the angle method correctly?

**Comment by carterbox** [comment]
The phase effects from a large detector distance wouldn't appear like this. I don't know if you're using the angle method correctly because you haven't shown me how you're using it.

- [ ] Are you collecting transmission tomography? Linearize the problem by taking the negative log of your projection data (`tomopy.minus_log()` after normalizing for dark and white field)
- [ ] TomoPy only supports parallel beam acquisition geometries
- [ ] Please send a sample of your data

**Comment by oobie2142** [comment]
https://drive.google.com/open?id=1ZnKa7y_iX0F9HT_2G1naUXA-sUMXEcJl
Here is the data I am using. 

I will try with only the vertical crop later today and post results. The data collected was in a parallel beam set up so I don't think there should be a problem in that regard. The way I used the angle method was 
`ang = tomopy.angles(900, ang1=0, ang2=360)`
since I took samples for a full rotation of the object. Is that the correct way to use it?

**Comment by carterbox** [comment]
It seems that your original problem, as I stated earlier, is that you were looking at a slice that did not have any sample. 

The second problem that you were having is that when you trimmed your data horizontally, you removed part of the sample and made a new center of rotation.

Use the manual finding center function. Use a slice that has sample to find the center.

The image below shows a slice that has the sample in it, but it is using the rotation center 430 (430 is probably the wrong center of rotation). I also used `tomopy.circ_mask(recon, axis=0, ratio=0.80)` to flatten the image outside the region of interest.

![reconstruction](https://user-images.githubusercontent.com/9604511/63462024-94251800-c41f-11e9-84be-a387c026fd27.png)

**Comment by oobie2142** [comment]
Oh snap! Thanks a bunch! Which sample image did you specifically use to find the center.
Is the steps for reconstruction as follows? I want to make sure I nail this down before I try other reconstructions. 

1. Normalize against a flat and dark projection
2. Find Center
3. Take the -log() of the normalized projection
4. Reconstruct with center calculated from step (2)

**Comment by carterbox** [comment]
I didn't find the center. I used the center you suggested (430). The image above is of slice 200.

Those steps seem like the correct order, but reconsider step 3. I'm not sure that whatever particle you are using is attenuated following the [Beer-Lambert law.](https://en.wikipedia.org/wiki/Attenuation_length). When I took the -log() of your data there were some negative values. Or maybe the exposure time wasn't long enough so there are some zero counts on the detector? I'm unsure. Talk to an experimentalist familiar with your setup.

**Comment by oobie2142** [comment]
@carterbox I still seemed to not be able to reconstruct the same image as you. I cropped only the vertical space and left the sides. I performed the normalization and reconstructed with an eyeball center of 400. The slice plotted is the 100th slice. I used the gridrec algorithm to reconstruct. Would it be possible to see the script/code you used in replicating the images above?


![Test_Crop](https://user-images.githubusercontent.com/7355790/63569235-cd4fac00-c535-11e9-9277-8305b986a88f.png)
![Recon_Slice_100](https://user-images.githubusercontent.com/7355790/63569238-d04a9c80-c535-11e9-9ee2-bb36943628af.png)

**Comment by carterbox** [comment]
```python
#!/usr/bin/env python
# coding: utf-8

import dxchange
import matplotlib.pyplot as plt
import tomopy

proj = dxchange.read_tiff_stack(
    "./EDensityTiff/Converted_To_Tiff/Scan-8_9_2019 10_45_13 AM000000.tif",
    range(0, 900)
)
proj.shape, proj.min(), proj.max()

# Adjusted pixel sizes to match flat and dark panel size
flat = dxchange.read_tiff(
    './EDensityTiff/lite_1024avg.tif',
    slc=((150, 150+422, 1),(30,30+876,1)),
)
dark = dxchange.read_tiff(
    './EDensityTiff/dark_1024avg.tif',
    slc=((150, 150+422, 1),(30,30+876,1)),
)
flat.shape, dark.shape

proj = tomopy.normalize(proj, flat, dark)
proj.min(), proj.max()

plt.imshow(proj[:, 200, :])
plt.colorbar()
plt.show()

theta = tomopy.angles(proj.shape[0], 0, 360)
recon = tomopy.recon(proj, theta, center=430, algorithm='gridrec')

# Mask each reconstructed slice with a circle.
recon = tomopy.circ_mask(recon, axis=0, ratio=0.80)

plt.figure(dpi=150)
plt.imshow(recon[400, :,:])
plt.colorbar()
plt.show()
```

**Comment by decarlof** [comment]
There are some issue with the normalization as the background is fluctuating  quite a bit during data collecting. This has two effects:

a) normalization with an average white field is not sufficient to compensate as you can see in sinogram horizontal lines:

![image](https://user-images.githubusercontent.com/5884150/63630348-5ec72880-c5df-11e9-82ed-baa4eddd4c90.png)

b) the subtraction of the dark field produces very large area of negative values in particular in the center part of the sample where density in higher and overall transmission is very low.

c) -log() has a lot of nan

b) and c) is much more serious for your sample but replacing the dark field with a constant gives acceptable results:

![image](https://user-images.githubusercontent.com/5884150/63630451-6e933c80-c5e0-11e9-8f86-0a6d8e2277ea.png)

there is still some cupping that can be removed with padding:

![image](https://user-images.githubusercontent.com/5884150/63630483-c5007b00-c5e0-11e9-8f21-96e4d79a8539.png)

Here is the code:

```#!/usr/bin/env python
# coding: utf-8

import dxchange
import matplotlib.pyplot as plt
import tomopy
import numpy as np

proj = dxchange.read_tiff_stack('./Converted_To_Tiff/Scan-8_9_2019 10_45_13 AM000000.tif', range(0, 900))
proj.shape, proj.min(), proj.max()


hshift = 30
vshift = 150

# Adjusted pixel sizes to match flat and dark panel size
flat = dxchange.read_tiff('./Converted_To_Tiff/lite_1024avg.tif', slc=((vshift, vshift+422, 1),(hshift,hshift+876,1)),)
dark = dxchange.read_tiff('./Converted_To_Tiff/dark_1024avg.tif', slc=((vshift, vshift+422, 1),(hshift,hshift+876,1)),)

# force dark to a constant
dark = np.zeros(dark.shape) + 100

data = tomopy.normalize(proj, flat, dark)
print(hshift, vshift, data.min(), data.max())

data = tomopy.minus_log(data)

data = tomopy.remove_nan(data, val=0.0)
data = tomopy.remove_neg(data, val=0.00)
data[np.where(data == np.inf)] = 0.00


plt.imshow(data[:, 200, :])
plt.colorbar()
plt.show()

theta = tomopy.angles(data.shape[0], 0, 360)

rot_center = 424.5

# padding 
N = data.shape[2]
data_pad = np.zeros([data.shape[0],data.shape[1],3*N//2],dtype = "float32")
data_pad[:,:,N//4:5*N//4] = data
data_pad[:,:,0:N//4] = np.reshape(data[:,:,0],[data.shape[0],data.shape[1],1])
data_pad[:,:,5*N//4:] = np.reshape(data[:,:,-1],[data.shape[0],data.shape[1],1])
data = data_pad
rot_center = rot_center + N//4

recon = tomopy.recon(data, theta, center=rot_center, algorithm='gridrec')

# padding 
recon = recon[:,N//4:5*N//4,N//4:5*N//4]

# Mask each reconstructed slice with a circle.
recon = tomopy.circ_mask(recon, axis=0, ratio=0.80)

plt.figure(dpi=150)
plt.imshow(recon[200, :,:])
plt.colorbar()
plt.show()
```
I played a little with hshift, vshift to see if I could get a better normalization for a) but I could not see an major improvement.

**Comment by oobie2142** [comment]
For the write_center does it make a tiff file with the center for each projection? Currently using the write_center method it only produces 20 images with the center as the name for the file.

**Comment by carterbox** [comment]
You provide `write_center` with a range of centers to try, and it reconstructs a single slice with all of the centers in that range. Each of the reconstructions is named by the center that was used to make it. You look at the reconstructed images and choose the one that has the correct center.
