### ISSUE TITLE
Astra CUDA recon with GPU still uses CPU

### ISSUE THREAD

**Issue by canismarko** [tomopy/tomopy#446]
**Describe the problem**
We're trying to do a reconstruction using the astra toolkit through tomopy with CUDA. On a linux machine this works as expected, but on our windows machine the reconstruction uses the CPU, making it considerably slower.

**To Reproduce (if applicable)**
Create a new conda environment and install tomopy and astra-toolbox (1.9dev). Load data using dxchange, do some pre-processing, then run the following reconstruction:

```python
extra_options ={'MinConstraint': 0}
options = {'proj_type': 'cuda', 'method': 'SIRT_CUDA', 'num_iter': 20, 'extra_options': extra_options}
recon = tomopy.recon(prj, theta, center=rot_center, algorithm=tomopy.astra, ncore=1, options=options)
```
The resulting reconstruction is as expected, however the task manager shows 100% CPU usage and no GPU activity, and takes considerably longer than expected for a GPU reconstruction.

``astra.use_cuda()`` returns *True*, indicating that astra is configured for GPU utilization.

Any help you can give us in tracking down this issue would be appreciated.

**Expected behavior (if applicable)**
We expect the reconstruction to be performed on the installed GPU using CUDA. Instead, the reconstruction takes place entirely on the CPU.

**Platform Information:**
 - OS: Windows 10
 - Python Version: 3.7.4.final.0
 - TomoPy Version: 1.6.0

**Additional context**
The latest NVIDIA drivers are installed as well as the latest NVIDIA CUDA runtime. After confirming these were installed we did  ``conda remove astra-toolbox``, ``conda clean -a`` and `` conda install -c astra-toolbox/label/dev astra-toolbox ``.

Conda environment and installed packages can be found in [this gist](https://gist.github.com/canismarko/2243f3bb798d97c46d8d24b49a2ee3c2).

**Comment by carterbox** [comment]
Hey @dmpelt, could you please help debug this? I don't have a Windows machine with CUDA compatible GPU yet.

**Comment by dmpelt** [comment]
I'm not sure we ever tested the ASTRA integration using CUDA on Windows, although I don't really see an immediate reason why it wouldn't work... Have you tried running the ASTRA examples on GPU and seeing whether the GPU is indeed used then?

**Comment by canismarko** [comment]
@dmpelt You mean the pure astra examples [here](https://github.com/astra-toolbox/astra-toolbox/tree/master/samples/python)? I have not tried those, no, so I'll see if that runs on the GPU or CPU and report back.

**Comment by jrmadsen** [comment]
Whether or not ASTRA is using the CPU vs. GPU on Windows would definitely seem like either an ASTRA issue. Or possibly just an ASTRA configuration issue. But, based on my experience, I would be more likely to believe this is an ASTRA issue, not a tomopy issue. 

If the ASTRA examples do not run on the GPU and Windows, the answer is obvious but if they do run on the GPU on Windows, you should just take a peek at where tomopy is wrapping the ASTRA calls and if there is not something like `if platform.system() == "Windows"`, I believe that would suggest it is just an ASTRA config issue.

**Comment by canismarko** [comment]
Ok so I went back to try some of the things that were recommended here, and now it uses the GPU as expected. No idea what changed.

I'm closing this issue, and thanks for your suggestions.
