### ISSUE TITLE
Modularize reconstruction algorithms using entry points

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#449]
There has been much discussion about reducing dependency lists recently, and this is because all of the built-in TomoPy algorithms are compiled into a single binary. With this structure, it is impossible to offer TomoPy with less dependencies without rebuilding it. Here, I am proposing to separate all of the compiled (non-python) algorithms into separate _plug-ins_ which could each be built once, packaged, and installed separately in any combination. This approach could also allow us to move the code in the `wrappers` module into the home project of the code being wrapped.

There already exists a built-in mechanism called "entry points" through which a Python package will automatically search for other installed Packages that advertise having an entry point of a certain name. For TomoPy, this could be something called 'tomopy-recon'. We would then break the reconstruction algorithms into separate python packages which all advertise this entry point.

### Additional Reading
https://amir.rachum.com/blog/2017/07/28/python-entry-points/
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points
https://medium.com/@jherreras/python-microlibs-5be9461ad979

**Comment by carterbox** [comment]
This could also lead to the TomoPy core package becoming `noarch` (platform and architecture agnostic).

**Comment by newville** [comment]
@carterbox  Which reconstruction methods would be available in a python-only version of tomopy?  

Personally, I would be OK with Python + Gridrec.  I might even be OK with Python + Gridrec using just the FFT methods guaranteed to be available with numpy (not MKL or FFTW).  Currently, that is significantly slower than MKL, but my understanding (no direct personal experience) is that the FFT to be used in upcoming numpy is only around a factor of 2 slower than MKL.

**Comment by carterbox** [comment]
@newville None. There are no python-only reconstruction methods, but users that I have met at conferences are only interested in TomoPy for its distortion correction methods because they do not have a parallel beam geometry.

**Comment by dgursoy** [comment]
+1 to Python + Gridrec
