### ISSUE TITLE
2020.04.26 Intern - SULI

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#452]
I am [writing a project proposal](https://docs.google.com/document/d/1fYKdYe_87yAkXHk-QgIB0YxkD3v6H1d4V29qO-LakZc/edit?usp=sharing) for an undergraduate intern to refactor TomoPy. My current proposal addresses the following issues: #428, #449, #448, #422

Since, this is a very public project, I am posting the proposal for public feedback, and so no one is surprised in a few months when code is moved around. Basically, if you have an idle branch that you are planning to merge, please open a pull-request before **March 1, 2020**. This project may include API breaking changes in the Python layer, and it will definitely have API breaking changes for the C layer.

If anyone knows any undergrads who may be particularly suited to this project, please contact me via email. My contact information is available on the Argonne National Laboratory public website. I'm not going to link it directly because I don't want spam.

**Comment by carterbox** [comment]
Only some extension functions find their wrapper simplified by switching to pybind11. These are functions such as downsample/upsample which are have three layers: `python -> python + ctypes -> c`. Other functions, such as the reconstruction algorithms, do not obviously benefit from having their ctypes interfaces replaced with something else. We should just re-purpose the existing ctypes interfaces.

It seems that the only benefit of using pybind11 is that the compiled extension module is self-contained (it is imported directly), maybe that any interface changes will cause problems at compile time instead of at run time, and it allows wrapping of C++ classes.

**Comment by jrmadsen** [comment]
@carterbox I would expect that _everything_ in `tomopy/util/extern.py` and `tomopy/util/mproc.py` would be simplified. And adding extensions to call compiled work would be greatly simplified too.

Also, the backend support for FFT stuff for the gridrec would probably be easier too bc you would make that decision at compile time instead of trying to figure out from Python whether the module was compiled with MKL or not:

```cpp
#if defined(TOMOPY_USE_MKL)
gridrec(...)
#else
auto numpy = py::module::import("numpy");
// implement gridrec using numpy FFT
#endif
```

**Comment by carterbox** [comment]
Francesco also suggested that we do something like the [areaDetector](https://github.com/areaDetector/areaDetector) repo. Where each of the new namespace-packages has its own repo which is linked to the main repo. However, I'm uncertain about this approach because it means all of the source-code is not included in the release tarball, and it may make issue tracking more complicated.

**Comment by jrmadsen** [comment]
Yea git submodules are great with the sole exception of that release tarball. The only work-around I can think of for that is to basically generate a metadata file for each submodule that encodes the repo url and revision and putting something into CMake that reads that file and clones/checks out the submodules when the `.gitmodules` file is not present (such as when in a release).

**Comment by carterbox** [comment]
If we do use pybind11, we must remember to [release the GIL](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil). Ctypes does this, so we must also do this in order to not break anything.
