### ISSUE TITLE
Gridrec: padding isn't applied for a specific size of the sinogram & an issue with smooth filters

### ISSUE THREAD

**Issue by nghia-vo** [tomopy/tomopy#453]
Problem 1:
   When reconstructing a sinogram with the size of 1024 x 1024, gridrec doesn't apply padding. This results artifacts. I guess this may relate to how padding is used to optimize the performance of the fft.
   If the size of the sinogram is changed to 1024 x 1025, padding is applied and the reconstructed image looks good.
![Compare](https://user-images.githubusercontent.com/12136997/69359046-c98c0c80-0c7f-11ea-97c7-f9695ad16269.png)
Problem 2:
   When a smooth filter such as "hann" is used, the reconstructed image shows some strange artifacts. I've implemented direct Fourier method myself and didn't see that type of artifacts. 
![Grid_rec_with_Hann_filter](https://user-images.githubusercontent.com/12136997/69359477-8da57700-0c80-11ea-9c59-1cd6d724745a.png)

Codes for reproducing the problems:
[sinogram for test](https://drive.google.com/open?id=14c_nlQSSMC0rcGZvv_9pj6Bv17ffuwHm)

```
import tomopy
import numpy as np
from PIL import  Image

def load_image(file_path):
    try:
        mat = np.asarray(Image.open(file_path), dtype=np.float32)
    except IOError:
        print(("No such file or directory: {}").format(file_path))
        raise
    if len(mat.shape) > 2:
        axis_m = np.argmin(mat.shape)
        mat = np.mean(mat, axis=axis_m)
    return mat

def save_image(file_path, mat):
    image = Image.fromarray(mat)
    try:
        image.save(file_path)
    except IOError:
        print(("Couldn't write to file {}").format(file_path))
        raise
    return file_path

# Main
# Load sinogram with a size of 1024 x 1024
sinogram = load_image("C:/Sino180_01024.tif")
center = tomopy.find_center_vo(np.expand_dims(sinogram, 1))
print("Center is {}".format(center))
(nrow, _) = sinogram.shape
angles = np.linspace(0.0, 180.0, nrow) * np.pi / 180.0
rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec")
rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
save_image("C:/rec_image_1024_1024.tif", rec_image)
print("Done! Image size 1024 x 1024")

# Modify size of the sinogram to 1024 x 1025
sinogram = np.pad(sinogram, ((0, 0), (0, 1)), mode="edge")
rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec")
rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
save_image("C:/rec_image_1025_1025.tif", rec_image)
print("Done! Image size 1025 x 1025")

# Use the smooth filter
rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", filter_name = "hann")
rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
save_image("C:/rec_image_1025_1025_hann.tif", rec_image)
```

**Comment by carterbox** [comment]
Thanks for reporting this bug. I'm don't have a full understanding of direct Fourier methods yet, so I'm not sure I would be able to help with this, but maybe @oleksandr-pavlyk has time for a quick patch or can explain if this is related to performance optimization?

**Comment by nghia-vo** [comment]
I think the problem 1 comes from these lines:
 ```
   // Compute pdim = next power of 2 >= dx
    for(pdim = 16; pdim < dx; pdim *= 2)
        ;
```
of this file: https://github.com/tomopy/tomopy/blob/193151fd5ddb35f4523d975b12cf448a6b55c2fe/source/cxx/gridrec.cc 

If dx = 1024, then pdim stops at 1024 which means there's no padding. Change condition to
`for(pdim = 16; pdim <= dx; pdim *= 2);`
should fix the problem.

**Comment by carterbox** [comment]
We're actually still shipping the C version of gridrec not the CXX version, but it should be updated in both places. I don't know why @jrmadsen created a CXX version of gridrec or what the status of it is.

@nghia-vo, Can you build, test, and open a pull request for this proposed change?

**Comment by jrmadsen** [comment]
If I remember correctly, the CXX version is required for MSVC. I remember there being some reason we kept both but for the life of me, I cannot remember why.

**Comment by carterbox** [comment]
It probably has something to do with complex types because CXX defines a cross-plaform complex type.

**Comment by nghia-vo** [comment]
@carterbox, @dgursoy , @decarlof : The problem (artifacts) remains if the sinogram width is 2000. This means that it will be padded to the size of 2048. Padding of 48 pixel is not enough. In direct Fourier method (DFM), padding is critical to improve the accuracy of the interpolation in the Fourier domain. More padding, more accurate, less artifacts (page 11 [here](https://pdfs.semanticscholar.org/c8be/6c8fd675c98133acc04b0c6cc58b7bc1e9cf.pdf))
I'm not sure if tomopy using fftw or not? if yes the restriction of using 2^n size to gain performance is lifted (http://www.fftw.org/). So we can pad the array to some thing 2*original_width to make sure DFM work well.

**Comment by newville** [comment]
@nghia-vo FWIW, zero-padding really doesn't improve the accuracy of a discrete Fourier transform so much as it imposes smoothness.  It is (quite literally) asserting that you know the values beyond the supplied data range are zero (and have no noise).  Without zero-padding you are saying that the values are unknown.  In the sense of ignoring the noise, zero-padding might reduce the fidelity of the result as the price of more and predictable smoothness.  

Still, I agree that more zero-padding would be good here.  It seems reasonable to say that the values outside the supplied data range are known to be "not the object". 

Perhaps something like: 

     #include <math>
     pdim = pow(2, (int)(log(pdim)/log(2.0) + 1.5) ); 

     # import math
     # pdim = 2**(int(math.log2(pdim) + 1.5))

which would give `pdim` that is a power of 2 that is between sqrt(2) and 2*sqrt(2) larger than the input value for `pdim`. 

I would really encourage converting gridrec to use the new-ish pocketfft from the most recent versions of numpy (https://github.com/numpy/numpy/tree/master/numpy/fft).   It seems pretty fast and will be much easier to port and maintain.

**Comment by nghia-vo** [comment]
@newville : I mean that padding improves 'the accuracy of the interpolator' in the Fourier space, not about the accuracy of the discrete Fourier transform. As we known padding improves the smoothness, so it helps to reduce the interpolation error.

**Comment by dgursoy** [comment]
[Here](https://dsp.stackexchange.com/questions/741/why-should-i-zero-pad-a-signal-before-taking-the-fourier-transform) is a nice discussion about padding.

Extra zero-padding was removed in the past to save some computation time, but maybe we should make it optional. So instead of doing: 
```
prj = np.pad(prj, ((0, 0), (10, 10)), mode='constant')
rec = tomopy.recon(prj, ...
```
we can have something like:
```
rec = tomopy.recon(prj, pad=True, ...
```
I suggest we have this padding option in the Python level before we call Gridrec. Also I remember that the performance of the FFT doesn't really change if powers of 2 aren't used with the new libraries. We should check this.

@nghia-vo Regarding the Hann filtering, the default parameter is 0.5. Have you tried larger parameters close to 1?
```
rec = tomopy.recon(..., filter_name="hann", filter_par=0.9)
```

**Comment by nghia-vo** [comment]
@dgursoy If the performance of fft no longer depends on the size of power of 2 then making padding optional is the right choice. 
- I've tried filter_par=0.9, the artifacts gone. Tried with others window too and saw that the Hamming window also gives extra artifacts if using the default value. Maybe we should update these default values.

**Comment by newville** [comment]
@nghia-vo  zero-padding does not improve the accuracy and it does not reduce interpolation error.  It *causes* interpolation where there was none before. That is, it gives a smooth interpolation between points that would be undefined in a non-zero-padded signal.   If you are going to interpolate, zero-padding with a DFT is an efficient way to do that and gives predictable smoothing.  It's a very common thing to do -- I agree that it would wise to do this for Gridrec.  

If accuracy is the concern, using double instead of single precision would probably be the most important way to improve the accuracy of the DFT, as accumulation of precision errors can definitely happen.

**Comment by nghia-vo** [comment]
@newville : I believe we're talking about two different things here. In direct Fourier methods (DFM) for tomography, one has to convert measured data, in the Fourier domain, from polar grid to the Cartesion grid. This is the interpolation I'm talking about. 
This [presentation](https://pdfs.semanticscholar.org/c8be/6c8fd675c98133acc04b0c6cc58b7bc1e9cf.pdf) reviews nicely about different ways of doing that.

**Comment by decarlof** [comment]
We apply padding in our [reconstruction script](https://github.com/decarlof/tomopy-cli/blob/6fd87b4c3023364bfe506446eac0d5c540cc5c53/tomopy_cli/recon.py#L113).

**Comment by nghia-vo** [comment]
@decarlof : we can adapt them to tomopy. Remove the padding step in the C code and do it in python code instead. @dgursoy , @carterbox : Shall I do that or would you like to do that instead to make sure nothing gonna break?

**Comment by nghia-vo** [comment]
Close for now. Padding can be done without changing C code.

**Comment by mahayusuf** [comment]
Has this issue been fixed? 

Can I use gridrec+hann using this: algotom.rec.reconstruction.gridrec_reconstruction(sinogram, center, angles=None, ratio=1.0, filter_name='shepp', apply_log=True, pad=100, ncore=1) ? 

Please let me know if this does not result in added artifacts in the data.
