### ISSUE TITLE
DockerHub Account

### ISSUE THREAD

**Issue by jrmadsen** [tomopy/tomopy#455]
@carterbox @dgursoy 

Is the name `tomopy` taken as a username or listed as an organization on hub.docker.com? I can't find any public docker images so I think, at some point, we may have created this and never set it up or something. I don't have a login stored in my keychain anywhere it seems. Could y'all search y'all's email for anything from docker hub related to this? Or try logging into your account and see if y'all have a tomopy account or your login is part of the tomopy DockerHub organization?

I am trying to create a Jupyter notebook for Dula to use with shifter at NERSC and it seemed like creating a `tomopy/jupyter:nersc` image was the best way to make it available instead of something like `jrmadsen/tomopy-jupyter:nersc`

**Comment by jrmadsen** [comment]
Oh and also, what do y'all think about creating a tomopy/docker repo? This would help enabling the automation of the docker builds. If so could y'all create it and give me write access? Or maybe just add me to the tomopy organization here on github and I will take care of that stuff.

**Comment by carterbox** [comment]
I do not control any DockerHub accounts. If Doga hasn't responded to this issue by Thursday night, I will track him down in person on Friday.

**Comment by jrmadsen** [comment]
Ok thanks

**Comment by carterbox** [comment]
TomoPy is not an organization (it's a regular user account), and I don't have access to the account anymore. Maybe it should be converted to an organization. I'll ask about that too.

**Comment by dgursoy** [comment]
I have the Docker account for tomopy. We had it set up in the past for Win users. I will add you as admins.

**Comment by dgursoy** [comment]
@jrmadsen please send me your Docker ID through e-mail.
