### ISSUE TITLE
Enable GPU support on Windows computer

### ISSUE THREAD

**Issue by RealPolitiX** [tomopy/tomopy#459]
I tried building tomopy 1.70 on a Windows 10 computer to enable CUDA support (python version 3.6.8, conda version 4.8.1). I got the following error,
"error: pathspec 'source/PTL' did not match any file(s) known to git"

I tried building PTL locally using CMake, which worked, but then the above error still exists and affects the building of tomopy. What should I do?

**Comment by carterbox** [comment]
Check your source directory. If the `tomopy/source/PTL` directory is empty, then you didn't checkout the [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) before trying to build tomopy.

**Comment by RealPolitiX** [comment]
Yes, the PTL folder is empty. What files should I put in there, all of PTL? Do I basically need to git-clone the PTL into this folder?

According to the .gitmodules under the tomopy folder, the program is supposed to fetch from https://github.com/jrmadsen/PTL.git

**Comment by carterbox** [comment]
You don't put anything in there. Git does it. Initialize and update the PTL submodule using:
```bash
git submodule update source/PTL/ --init
```
This will checkout PTL at the appropriate commit inside the `source/PTL` folder.

**Comment by RealPolitiX** [comment]
OK, thanks, just saw it. I did the following to clone to recursively clone the latest repo
`git clone --recurse-submodules -j8 https://github.com/tomopy/tomopy.git`
and built tomopy again, it also worked

**Comment by carterbox** [comment]
Good. Thanks for your patience; I thought git submodules were easier to set up.
