### ISSUE TITLE
CT reconstruction from tiff stack

### ISSUE THREAD

**Issue by CTPassion** [tomopy/tomopy#463]
**Describe the problem**
We have the following code using skimage that works fine to reconstruct slices of a pencil.

**To Reproduce (if applicable)**

```python
 #Acquires object from user and creates black object for filtered back projection
    obj_stack,str_object = get_image(window)
    dim_stack = obj_stack.shape
    obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the same
    obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))
    #Gets save location
    dir_save = dir_save_path()
    str_imname = file_name(str_object)
    str_save = os.path.join(dir_save, str_imname)

    #Creates theta array (in degrees)
    dtheta = 1
    theta = np.arange(0, dim_stack[0],dtheta)

    #Redefining dot calls
    iradon = skt.iradon
    rotate = ndi.rotate

    #Obtains reconstruction using filtered back projection
    for i in range(0,dim_stack[1]):
        #Updates progress bar
        percentage = int(100*i/dim_stack[1]+1)
        bar['value'] = percentage
        window.update()

        #Performs filtered back projection on each y slice
        obj_fbp[i,:,:] = iradon(rotate(obj_stack[:,i,:],90),theta=theta,circle=True)
```
This is the tiff stack of Flat Field Corrected images of the pencil.
<img width="269" alt="Screenshot 2020-02-11 at 15 45 13" src="https://user-images.githubusercontent.com/60933427/74252599-d0a64200-4ce5-11ea-87e8-4a9999fa9c1f.png">
This is a slice of the pencil from the above code.
<img width="260" alt="Screenshot 2020-02-11 at 15 46 20" src="https://user-images.githubusercontent.com/60933427/74252604-d3089c00-4ce5-11ea-98cb-e8ab5dbd0b18.png">

**Tomopy**
We are looking for other methods and we are trying to use Tomopy. 

```python

   #Acquires object from user and creates black object for filtered back projection
    obj_stack,str_object = get_image(window)
    dim_stack = obj_stack.shape
    obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the 
     same
    obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))

    #Gets save location
    dir_save = dir_save_path()
    str_imname = file_name(str_object)
    str_save = os.path.join(dir_save, str_imname)

    #Creates theta array (in degrees)
    dtheta = 1
    theta = np.arange(0, dim_stack[0],dtheta)

    rot_center = tomopy.find_center(obj_stack,theta,init=120,tol=0.5)
    proj = tomopy.minus_log(obj_stack)
    
    recon = tomopy.recon(proj,theta,algorithm='gridrec',sinogram_order=False)
    recon = tomopy.circ_mask(recon, axis=0, ratio=0.95)
```
This produces a cross section with many empty slices and the pencil is unclear:
<img width="275" alt="Screenshot 2020-02-11 at 15 53 49" src="https://user-images.githubusercontent.com/60933427/74253243-c20c5a80-4ce6-11ea-815b-0e670dfeed3d.png">
<img width="287" alt="Screenshot 2020-02-11 at 15 53 54" src="https://user-images.githubusercontent.com/60933427/74253258-c46eb480-4ce6-11ea-95b2-d409ec83d939.png">

**Platform Information:**
 - OS: [macOS]
 - Python Version [e.g. 3.7.4]

What are we doing wrong? What would be the best method for this case?

Here is the link to the tif file:
[https://1drv.ms/u/s!ApMx4837PKEQohtnSHwri9THt9gP?e=422eea](url)

**Comment by dgursoy** [comment]
We use radians for theta, not degrees. Could you give it a try with ```theta * np.pi / 180```?

**Comment by CTPassion** [comment]
<img width="296" alt="Screenshot 2020-02-11 at 16 08 32" src="https://user-images.githubusercontent.com/60933427/74254751-c9ccfe80-4ce8-11ea-920f-8803cb6dc8d5.png">

This is the new slice, but there are still many in the stack which are blank as before.

**Comment by dgursoy** [comment]
The link to the file doesn't seem to work. Do you have any other option to share the data?

**Comment by CTPassion** [comment]
I've changed the link, if you copy and paste it it should work

**Comment by dgursoy** [comment]
This should fix your problem:
```
prj /= 150. # normalize data to 0 and 1
prj[prj == 0]= 0.1 # remove the dead pixels
```
Add these lines before the ```minus_log``` to remove effect of dead detector pixels. I believe it should be fine afterwards.

**Comment by CTPassion** [comment]
Does 'prj' mean 'proj'? Since 'proj' is defined in the `minus_log`

**Comment by dgursoy** [comment]
Sorry, like this then:
```
obj_stack /= 150. # normalize data to 0 and 1
obj_stack[obj_stack == 0]= 0.1 # remove the dead pixels
```

**Comment by CTPassion** [comment]
Get the following error:

`File "ct_reconstruction.py", line 140, in main
    obj_stack /= 150. # normalize data to 0 and 1
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''`

**Comment by dgursoy** [comment]
This is easy. Please convert your data to ```np.float32``` after you read it.

**Comment by CTPassion** [comment]
Great, when I save it I get a tiff file thats completely black however, is this right?

`    io.imsave(str_save,recon.astype('uint32'),plugin='tifffile') `

**Comment by dgursoy** [comment]
If you want to save int32, you should first scale the data between 0 and 255:
```
recon = (recon / recon.max() * 255).astype('uint32')
```

**Comment by prjemian** [comment]
puzzling, [given](https://docs.scipy.org/doc/numpy/user/basics.types.html):


Numpy type | C type | Description
-- | -- | --
np.int32 | int32_t | Integer (-2147483648 to 2147483647)

Is this a tomopy restriction to range 0 .. 255?

**Comment by prjemian** [comment]
Now my coment looks silly.  Until you see the email to which I thought I was replying:

![Clipboard01](https://user-images.githubusercontent.com/2279984/74260873-e43eb200-4cbf-11ea-8c79-f4ee49a68610.jpg)

**Comment by dgursoy** [comment]
Sorry, I also realized and fixed just after I hit the comment button...

**Comment by CTPassion** [comment]
Thanks guys, the image looks better already than my FBP using skimage.
<img width="276" alt="Screenshot 2020-02-11 at 17 28 10" src="https://user-images.githubusercontent.com/60933427/74262067-19fd8e00-4cf4-11ea-894b-8505df326083.png">
<img width="496" alt="Screenshot 2020-02-11 at 17 28 56" src="https://user-images.githubusercontent.com/60933427/74262078-1d911500-4cf4-11ea-964c-5c55eaddb3b9.png">

would you have any suggestions for improvements? Does it come down to trialling different filters and algorithms

**Comment by dgursoy** [comment]
Yes, it's a great pen! :-)

You can try other algorithms and pick the one you like. ```mlem``` or ```tv``` can give you a nice reconstruction but they might be a bit slow. Try it on a single slice and when you like the result, use the whole data maybe to speed up. Also you need to tune the regularization parameter for ```tv``` and some other algorithms. Good luck!

**Comment by dgursoy** [comment]
Before I forget.. I just realized that your rotation center is off. Please try this center instead:
```
cen = np.linspace(138, 134, 256)
```

**Comment by CTPassion** [comment]
Done, what does this do and how did you figure it out? Is this preferable to the `tomopy.findcenter`?

**Comment by dgursoy** [comment]
This assigns a different center for each slice. Just by looking at your data I realized that your rotation axis is a little tilted from the vertical axis, so the slices at the top have different centers (138) than the one at the bottom (134). You can apply ```find_center``` to one of the top slices and another ```find_center ``` to one of the bottom slices and use interpolated values between these two for all the slices.

**Comment by CTPassion** [comment]
I see, that's useful thank you. I'm sure I'll have questions about artefact removal and getting a better image.

**Comment by dgursoy** [comment]
Glad that it worked out. Cheers!

**Comment by CTPassion** [comment]
> Before I forget.. I just realized that your rotation center is off. Please try this center instead:
> 
> ```
> cen = np.linspace(138, 134, 256)
> ```
I've got a different stack now and I'm coming back to ask how you know the rotation centre for the individual images? When applying tomopy.find_center  the function needs to be passed the _stack_ of images and so I can't get the rotation center for each slice?

**Comment by carterbox** [comment]
Find the center for the first, last, and some middle slices by calling `tomopy.find_center` multiple times with different values of `ind`. Then we usually assume the centers are a linear function of `ind`, and interpolate what the centers should be fore the rest of the slices.

**Comment by matangpanchal** [comment]
> **Describe the problem** We have the following code using skimage that works fine to reconstruct slices of a pencil.
> 
> **To Reproduce (if applicable)**
> 
> ```python
>  #Acquires object from user and creates black object for filtered back projection
>     obj_stack,str_object = get_image(window)
>     dim_stack = obj_stack.shape
>     obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the same
>     obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))
>     #Gets save location
>     dir_save = dir_save_path()
>     str_imname = file_name(str_object)
>     str_save = os.path.join(dir_save, str_imname)
> 
>     #Creates theta array (in degrees)
>     dtheta = 1
>     theta = np.arange(0, dim_stack[0],dtheta)
> 
>     #Redefining dot calls
>     iradon = skt.iradon
>     rotate = ndi.rotate
> 
>     #Obtains reconstruction using filtered back projection
>     for i in range(0,dim_stack[1]):
>         #Updates progress bar
>         percentage = int(100*i/dim_stack[1]+1)
>         bar['value'] = percentage
>         window.update()
> 
>         #Performs filtered back projection on each y slice
>         obj_fbp[i,:,:] = iradon(rotate(obj_stack[:,i,:],90),theta=theta,circle=True)
> ```
> 
> This is the tiff stack of Flat Field Corrected images of the pencil. <img alt="Screenshot 2020-02-11 at 15 45 13" width="269" src="https://user-images.githubusercontent.com/60933427/74252599-d0a64200-4ce5-11ea-87e8-4a9999fa9c1f.png"> This is a slice of the pencil from the above code. <img alt="Screenshot 2020-02-11 at 15 46 20" width="260" src="https://user-images.githubusercontent.com/60933427/74252604-d3089c00-4ce5-11ea-98cb-e8ab5dbd0b18.png">
> 
> **Tomopy** We are looking for other methods and we are trying to use Tomopy.
> 
> ```python
>    #Acquires object from user and creates black object for filtered back projection
>     obj_stack,str_object = get_image(window)
>     dim_stack = obj_stack.shape
>     obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the 
>      same
>     obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))
> 
>     #Gets save location
>     dir_save = dir_save_path()
>     str_imname = file_name(str_object)
>     str_save = os.path.join(dir_save, str_imname)
> 
>     #Creates theta array (in degrees)
>     dtheta = 1
>     theta = np.arange(0, dim_stack[0],dtheta)
> 
>     rot_center = tomopy.find_center(obj_stack,theta,init=120,tol=0.5)
>     proj = tomopy.minus_log(obj_stack)
>     
>     recon = tomopy.recon(proj,theta,algorithm='gridrec',sinogram_order=False)
>     recon = tomopy.circ_mask(recon, axis=0, ratio=0.95)
> ```
> 
> This produces a cross section with many empty slices and the pencil is unclear: <img alt="Screenshot 2020-02-11 at 15 53 49" width="275" src="https://user-images.githubusercontent.com/60933427/74253243-c20c5a80-4ce6-11ea-815b-0e670dfeed3d.png"> <img alt="Screenshot 2020-02-11 at 15 53 54" width="287" src="https://user-images.githubusercontent.com/60933427/74253258-c46eb480-4ce6-11ea-95b2-d409ec83d939.png">
> 
> **Platform Information:**
> 
> * OS: [macOS]
> * Python Version [e.g. 3.7.4]
> 
> What are we doing wrong? What would be the best method for this case?
> 
> Here is the link to the tif file: [https://1drv.ms/u/s!ApMx4837PKEQohtnSHwri9THt9gP?e=422eea](url)

Hi, Do you still have these images ? Can you give me, I want to try certain things with it.

> I've changed the link, if you copy and paste it it should work

Hi, Do you still have these images ? Can you give me, I want to try certain things with it.

**Comment by matangpanchal** [comment]
> I've changed the link, if you copy and paste it it should work
Hi, Do you still have this dataset, I want to try certain things with it. Can you please give me ?

**Comment by matangpanchal** [comment]
> Sorry, like this then:
> 
> ```
> obj_stack /= 150. # normalize data to 0 and 1
> obj_stack[obj_stack == 0]= 0.1 # remove the dead pixels
> ```

Hello Sir,
Since few days I am going through all issues listed on github, to learn more about tomopy. 
And I must say that the way you are taking interest in everyones problems and how you reply them is remarkable.

Here I want to know about the selection of the divisor 150, I mean how you selected 150 ? Is there any thumb of rule or its remains the same for any dataset. 
My point on asking this is that this parameter makes huge difference in reconstruction.

Hope to hear soon from you.
