### ISSUE TITLE
Removing Artifacts

### ISSUE THREAD

**Issue by CTPassion** [tomopy/tomopy#465]
**Describe the problem**
We have artifacts in our image (straight dark lines coming off the edge of the pencil). 

<img width="220" alt="Screenshot 2020-02-12 at 15 17 30" src="https://user-images.githubusercontent.com/60933427/74437908-e12ef780-4e60-11ea-92c9-4e04ba6a45c7.png">

How can we use TomoPy to remove aritfacts?
```python
obj_stack=np.float32(obj_stack) #Change data type of stack

    rot_center = tomopy.find_center(obj_stack,theta,init=120,tol=0.5)
    obj_stack /= 150. # normalize data to 0 and 1
    obj_stack[obj_stack == 0]= 0.1 # remove the dead pixels
    proj = tomopy.minus_log(obj_stack)

    cen = np.linspace(138, 134, 256)
    
    recon = tomopy.recon(proj,theta*np.pi/180,center=cen,algorithm='gridrec',sinogram_order=False,filter_name='hamming')
    recon = tomopy.circ_mask(recon, axis=0, ratio=0.65)
    #recon = tomopy.misc.corr.gaussian_filter(recon,sigma=1)
    recon = (recon / recon.max() * 2147483646).astype('uint32') #scale the data between 0 and 2147483646
```

**Platform Information:**
 - macOS
 - Python Version 3.7.4

**Comment by carterbox** [comment]
I assume you are using a multi-energy x-ray source. In that case, those artifacts are [beam-hardening](https://radiopaedia.org/articles/beam-hardening?lang=us). While we don't have any algorithms specifically for beam-hardening, you will get a less noisy reconstruction using an iterative algorithm.

**Comment by CTPassion** [comment]
Which algorithms on Tomopy should we use?

**Comment by decarlof** [comment]
How many projections did you collected and what is the detector size? I think there also some angular under sampling.  I agree with @carterbox beam hardening is the major artifacts. We have implemented beam hardening correction for synchrotron bending magnet sources in the [tomopy-cli](https://github.com/tomography/tomopy-cli) see [beam-hardening](https://github.com/tomography/tomopy-cli/blob/master/tomopy_cli/beamhardening.py), if you are not using a BM source perhaps we can customize this function for your needs.

**Comment by CTPassion** [comment]
There are 360 projections so must be 1per degree. We are using a Medipix 2 and a X-ray generator:
![87295759_277323119911515_1963762719651790848_n](https://user-images.githubusercontent.com/60933427/74732431-23ca4880-5242-11ea-9272-406be18f9a11.jpg)
![86788707_883863658694560_3747506746994720768_n](https://user-images.githubusercontent.com/60933427/74732435-25940c00-5242-11ea-86bc-e24649382611.jpg)
The raw data:
https://drive.google.com/open?id=1-n69xn0RAeRt5BYY6IyCKbk_8wUjb59E
and the stack with FFC applied:
https://drive.google.com/open?id=1JUNuxwhuLXUwz09rKFVPWB1HSso7R9r0

The code:
`#Acquires object from user and creates black object for reconstruction
    obj_stack,str_object = get_image(window)
    dim_stack = obj_stack.shape
    obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the same
    obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))

    #Gets save location
    dir_save = dir_save_path()
    str_imname = file_name(str_object)
    str_save = os.path.join(dir_save, str_imname)

    #Creates theta array (in degrees)
    dtheta = 1
    theta = np.arange(0, dim_stack[0],dtheta)


    obj_stack=np.float32(obj_stack) #Change data type of stack

    rot_center = tomopy.find_center(obj_stack,theta,init=120,tol=0.5)
    obj_stack /= 150. # normalize data to 0 and 1
    obj_stack[obj_stack == 0]= 0.1 # remove the dead pixels
    proj = tomopy.minus_log(obj_stack)

    cen = np.linspace(138, 134, 256)
    
    recon = tomopy.recon(proj,theta*np.pi/180,center=cen,algorithm='art',sinogram_order=False)
    recon = tomopy.circ_mask(recon, axis=0, ratio=0.65)
    recon = tomopy.misc.corr.gaussian_filter(recon,sigma=1)
    #recon = tomopy.misc.corr.remove_ring(recon)
    recon = (recon / recon.max() * 2147483646).astype('uint32') #scale the data between 0 and 2147483646`

**Comment by ydeno** [comment]
Try to make 360 projections per 180 degree. It is sufficient for the reconstruction algorithm and may be the quality will be better.

**Comment by CTPassion** [comment]
> How many projections did you collected and what is the detector size? I think there also some angular under sampling. I agree with @carterbox beam hardening is the major artifacts. We have implemented beam hardening correction for synchrotron bending magnet sources in the [tomopy-cli](https://github.com/tomography/tomopy-cli) see [beam-hardening](https://github.com/tomography/tomopy-cli/blob/master/tomopy_cli/beamhardening.py), if you are not using a BM source perhaps we can customize this function for your needs.

How do I create the text files it mentions here for beam hardening correction?

**Comment by ydeno** [comment]
optimal number of projections is given (Pi/2)*number of pixels in the horizontal line of the detector. I see that this is medipix with 55 micron pixel size with 256 pixels in the row. No=402 projections...I recomended each projection at 0.4 degree.... 450 projections/180 degree

**Comment by CTPassion** [comment]
> optimal number of projections is given (Pi/2)*number of pixels in the horizontal line of the detector. I see that this is medipix with 55 micron pixel size with 256 pixels in the row. No=402 projections...I recomended each projection at 0.4 degree.... 450 projections/180 degree

Great, where does this optimum calculation come from?

**Comment by ydeno** [comment]
https://www.sciencedirect.com/science/article/pii/S0378437104003681
