### ISSUE TITLE
Which algorithm/software to use?

### ISSUE THREAD

**Issue by CTPassion** [tomopy/tomopy#466]
**Describe the problem**
We have tried all the tomopy.recon algorithms on a pencil and found gridrec works best

Gridrec w/ cosine filter:
<img width="504" alt="Screenshot 2020-02-16 at 16 43 30" src="https://user-images.githubusercontent.com/60933427/74609228-04b3a580-50e0-11ea-9b52-dc9c75b896e6.png">

We used imageJ volume viewer to produce the volume from the stack. This involves manually moving the alpha graph to get a clear picture:

<img width="276" alt="Screenshot 2020-02-16 at 17 18 00" src="https://user-images.githubusercontent.com/60933427/74609257-58be8a00-50e0-11ea-9f00-b6d3852852f5.png">

1) Is there any way a program can do this or is it just trial and error?
2) Why does gridrec seem to be the only algorithm which allows us to see the "cone" of the pencil?
e.g art algorithm:
<img width="489" alt="Screenshot 2020-02-16 at 17 20 39" src="https://user-images.githubusercontent.com/60933427/74609301-c965a680-50e0-11ea-9ff1-afa5da6f0dad.png">
All the other methods do this.  Why does this happen?

**Comment by decarlof** [comment]
@CTPassion can you share the raw data? and more details about the instrument?

**Comment by CTPassion** [comment]
Using medipix 2 and X-ray tube:
![87295759_277323119911515_1963762719651790848_n](https://user-images.githubusercontent.com/60933427/74733553-786ec300-5244-11ea-99b7-589b58c4a003.jpg)
![86788707_883863658694560_3747506746994720768_n](https://user-images.githubusercontent.com/60933427/74733555-79075980-5244-11ea-9271-6ba075c88b6f.jpg)

Raw Data:
The raw data:
https://drive.google.com/open?id=1-n69xn0RAeRt5BYY6IyCKbk_8wUjb59E
and the stack with FFC applied:
https://drive.google.com/open?id=1JUNuxwhuLXUwz09rKFVPWB1HSso7R9r0

The code:
`#Acquires object from user and creates black object for reconstruction
    obj_stack,str_object = get_image(window)
    dim_stack = obj_stack.shape
    obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the same
    obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))

    #Gets save location
    dir_save = dir_save_path()
    str_imname = file_name(str_object)
    str_save = os.path.join(dir_save, str_imname)

    #Creates theta array (in degrees)
    dtheta = 1
    theta = np.arange(0, dim_stack[0],dtheta)


    obj_stack=np.float32(obj_stack) #Change data type of stack

    rot_center = tomopy.find_center(obj_stack,theta,init=120,tol=0.5)
    obj_stack /= 150. # normalize data to 0 and 1
    obj_stack[obj_stack == 0]= 0.1 # remove the dead pixels
    proj = tomopy.minus_log(obj_stack)

    cen = np.linspace(138, 134, 256)
    
    recon = tomopy.recon(proj,theta*np.pi/180,center=cen,algorithm='art',sinogram_order=False)
    recon = tomopy.circ_mask(recon, axis=0, ratio=0.65)
    recon = tomopy.misc.corr.gaussian_filter(recon,sigma=1)
    #recon = tomopy.misc.corr.remove_ring(recon)
    recon = (recon / recon.max() * 2147483646).astype('uint32') #scale the data between 0 and 2147483646`
