### ISSUE TITLE
Continually changing rotation center 

### ISSUE THREAD

**Issue by CTPassion** [tomopy/tomopy#469]
**Describe the problem**
I have a stack of 450 images of 360degree rotation of a pen. I've been told to take the rotation centre of the first and last slice and interpolate but the first and last slice are at the same angle. The object tilts outward, then tilts back and out and back as it does the 360 degrees:

How can I best contstruct a center of rotation array for these images? I have been messing around and getting it so wrong that sometimes the reconstruction has a double image of the pen. If i put ind in the argument for find rot center at anything near 450, which is the last image, I get a value error. 

**To Reproduce (if applicable)**
Reconstruction of the pen top. 
<img width="192" alt="Screenshot 2020-03-05 at 19 26 31" src="https://user-images.githubusercontent.com/60933427/76017894-47b2ad00-5f17-11ea-9027-211cfa5e06e7.png">
<img width="656" alt="Screenshot 2020-03-05 at 19 28 20" src="https://user-images.githubusercontent.com/60933427/76019253-513d1480-5f19-11ea-98b7-bfb75a59cb50.png">
This is about the best I can manage using gridrec, the OLEM and iterative algorithms dont seem any better?

```
#Acquires object from user and creates black object for filtered back projection
    obj_stack,str_object = get_image(window)
    dim_stack = obj_stack.shape
    obj_fbp= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1])) #As image is square dimensions are the same
    obj_fbp_2= np.zeros((dim_stack[1],dim_stack[1],dim_stack[1]))

    #Gets save location
    dir_save = dir_save_path()
    str_imname = file_name(str_object)
    str_save = os.path.join(dir_save, str_imname)

    #Creates theta array (in degrees)
    dtheta = 1
    theta = np.arange(0, dim_stack[0],dtheta)


    obj_stack=np.float32(obj_stack) #Change data type of stack
    rot_center=np.arange(0, dim_stack[0],dtheta)

    obj_stack /= 150. # normalize data to 0 and 1
    obj_stack[obj_stack == 0]= 0.1 # remove the dead pixels
    proj = tomopy.minus_log(obj_stack)

    rot_center_start = tomopy.find_center(proj,theta,init=130,ind=0,mask=True,tol=0.5)
    rot_center_end = tomopy.find_center(proj,theta,init=130,ind=180,mask=True,tol=0.5)

    cen = np.linspace(rot_center_start, rot_center_end, 256)

    recon = tomopy.recon(proj,theta*np.pi/180,center=cen,algorithm='gridrec')
    #recon = tomopy.recon(proj,theta*np.pi/180,center=cen,algorithm='osem', init_recon=recon_guess)

    recon = tomopy.circ_mask(recon, axis=0, ratio=0.95)
    recon = tomopy.misc.corr.gaussian_filter(recon,sigma=1)
    #recon = tomopy.misc.corr.remove_ring(recon)
    recon = (recon / recon.max() * 2147483646).astype('uint32') #scale the data between 0 and 2147483646
```

**Comment by decarlof** [comment]
@CTPassion can you describe in more details you experimental set up? In particular why is the rotation axis moved during data collection? is the motion known or is this to keep the sample in the field of view (and not know for each projection)? If this last is true there best interpolation is to use the images themselves.

**Comment by CTPassion** [comment]
It is a medipix2 detector and a miniX cone beam Xray generator. The sample is rotated in front of the detector. I take the centres of the first and last but it clearly gets them wrong as the final result is producing mirrored parts of the pen:
<img width="171" alt="Screenshot 2020-03-08 at 17 53 58" src="https://user-images.githubusercontent.com/60933427/76168278-37444180-6166-11ea-9b34-50661d9c4b92.png">
<img width="177" alt="Screenshot 2020-03-08 at 17 55 17" src="https://user-images.githubusercontent.com/60933427/76168279-37dcd800-6166-11ea-8781-248b7beb9115.png">

**Comment by CTPassion** [comment]
Managed to fix this but just had to trial and error initial guess for centre until it worked!
