### ISSUE TITLE
An interesting example to show a difference in using gridrec and fbp method

### ISSUE THREAD

**Issue by nghia-vo** [tomopy/tomopy#472]
One of users sent me an interesting neutron sinogram image for testing ring removal methods.
![sinogram_360_neutron_image](https://user-images.githubusercontent.com/12136997/79596027-c171b500-80d7-11ea-8965-5db6459fbb43.jpg)
[Raw sinogram](https://github.com/nghia-vo/sarepy/blob/master/data/sinogram_360_neutron_image.tif)
Before ring artifact removal is used:
     If use gridrec:         
![rec_gridrec_before_sinogram_360_neutron_image](https://user-images.githubusercontent.com/12136997/79596224-16adc680-80d8-11ea-8d07-36082e9fb73e.jpg)
     If use fbp:      
![rec_fbp_before_sinogram_360_neutron_image](https://user-images.githubusercontent.com/12136997/79596264-29c09680-80d8-11ea-8810-e4434a8b8db7.jpg)
After ring artifacts are [removed,](https://github.com/nghia-vo/sarepy/blob/master/examples/example2.py) two methods perform the same.
![rec_after_sinogram_360_neutron_image](https://user-images.githubusercontent.com/12136997/79596478-9045b480-80d8-11ea-8c0f-5d70542a4c9b.jpg)

**Comment by carterbox** [comment]
Thanks, @nghia-vo, I'll have our summer student try to incorporate this into the documentation.
