### ISSUE TITLE
Binder: Link to data file does not work

### ISSUE THREAD

**Issue by habi** [tomopy/tomopy#477]
The link to the `tooth.h5` dataset does not work when starting the notebook in Binder from here: https://mybinder.org/v2/gh/tomopy/tomopy/master

I had to change the path, and managed to load the dataset by going up a folder more, as seen in the attached screenshot.
I would have liked to submit a PR, but don't know how it's best to do this for a Jupyter notebook :)

<img width="1198" alt="Screenshot 2020-05-12 at 15 09 46" src="https://user-images.githubusercontent.com/1651235/81695486-fd8fff80-9462-11ea-9737-8a1427968b01.png">

**Comment by carterbox** [comment]
Thanks for reporting @habi. This issue is closed by #476.

**Comment by carterbox** [comment]
To answer your other question, GitHub has pretty good support for editing files online. For small changes like this, you can navigate to a file in any repository and click the edit button to make small changes. I use this feature to correct spelling and other small things all the time! Cheers! :beer:

**Comment by habi** [comment]
> To answer your other question, GitHub has pretty good support for editing files online.
> 

I’m also using that feature all the time, but this won’t work well with the JSON in a Jupyter file ;)
Also because the way I did it uses a new import (`import os`), so I just submitted the error as an issue and not a PR with a fix...
