### ISSUE TITLE
update documetation of the entropy based centering

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#480]
Include in the docs @MarkRivers findings on entropy based centering (#479)

**Comment by MarkRivers** [comment]
I am still working on this.  I have established that the entropy based centering using Gridrec/tomoRecon with the IDL front-end is working very well.  I am trying to figure out why tomopy is not currently giving the same results.  I am in the process of writing a Python program that is as similar as possible to the IDL test program.
