### ISSUE TITLE
tomopy gridrec reconstructions differ from those in tomoRecon

### ISSUE THREAD

**Issue by MarkRivers** [tomopy/tomopy#481]
The tomography reconstruction code in use at APS sector 13 is called tomoRecon: https://github.com/cars-uchicago/tomorecon

It was the first implementation of a thread-safe version of Gridrec that could thus be used to reconstruct multiple slices in parallel.  At sector 13 we use an IDL front-end to tomoRecon. https://github.com/CARS-UChicago/tomoRecon/tree/master/IDL

The reconstructions produced by tomoRecon are signficantly different from those produced by the gridrec algorithm in tomopy.  The tomopy reconstructions appear to be 1.5-2X noisier.  Entropy based center that works well in IDL with no masking fails in tomopy.  Even with masking the tomopy find_center() function does not perform as well as tomoRecon reconstructions with no masking.

In order to track this down we need to determine how the tomopy gridrec code differs from tomoRecon.

The first question I have is which gridrec code in tomopy is actually being used?  There are two versions that are quite similar but not identical.  One is written in C and the other in C++.
```
/tomopy/source/c/gridrec.c
/tomopy/source/cxx/gridrec.cc
```

How do I determine which of these is actually being called from Python?

**Comment by carterbox** [comment]
It looks like the CXX gridrec implementation is only the default for the Windows build.

https://github.com/tomopy/tomopy/blob/193151fd5ddb35f4523d975b12cf448a6b55c2fe/cmake/Modules/Options.cmake#L13-L18

**Comment by MarkRivers** [comment]
I have written 2 test routines, one in IDL and one in Python.  They are as identical as possible, and are written for clarity rather than to use optimized idioms of each language.  Each program does the following:
- Reads 2 TIFF files whose paths are passed as arguments.  These are intended to be 2 slices from the same dataset.
- Does any specified air normalization or extra padding.
- Reconstucts each slice at each of 320 different rotation centers, plus or minus 40 pixels from the initial guess of the center in 0.25 pixel steps.
- This reconstruction is done by copying these slices to alternate slices in a 3-D array with 640 slices, Slices 0, 2, 4, .. are the first TIFF file, slices 1, 3, 5, ... are the second TIFF file.  This takes advantage of the fact that Gridrec reconstructs 2 slices at once, each with the same center.
- Creates an array of center positions with 640 center values.  center[N] and [N+1] are the same, where N is an even integer from 0 to 639.
- When the reconstruction is done it computes the entropy of each reconstruction using a histogram with 10000 bins.
- Plots the entropy as a function of center position.  Writes the plot to a png file.
- Prints the best center position for each slice, i.e. the one with the lowest entropy.
- Writes the "best" reconstruction for each slice (the one with the lowest entropy) to a TIFF file so the IDL and tomopy reconstructions can be compared in ImageJ.

This is the IDL routine:
```
pro log_info, message
    print, systime() + '  INFO: ' + message
end

pro compute_center_entropy, file1, file2, center_guess

    ; This routine computes the entropy as a function of center position using
    ; Gridrec (tomoRecon version) in IDL
    
    center_range = 40.
    center_step = 0.25
    filter_name = 'hann'
    air_pixels = 10
    ring_width = 0
    padding_average = 0
    padded_width = 0
    tiff_scale = 1e6
    
    num_center = fix(center_range*2/center_step)
    center = (center_guess - center_range) + findgen(num_center) * center_step
    
    log_info, 'Reading TIFF slices ...'
    slice1 = read_tiff(file1+'.tiff')
    slice2 = read_tiff(file2+'.tiff')
    s = size(slice1, /dimensions)
    num_pixels = s[0]
    num_projections = s[1]
    
    log_info, 'Creating projection and center arrays ...'
    proj = fltarr(num_pixels, num_center*2, num_projections, /nozero)
    ctr = fltarr(num_center*2)
    for i=0, num_center-1 do begin
        ctr[i*2] = center[i]
        ctr[i*2+1] = center[i]
        proj[*, i*2, *] = slice1
        proj[*, i*2+1, *] = slice2
    endfor
    
    log_info, 'Initializing tomo_params ...'
    tomo_params = tomo_params_init(proj, airPixels=air_pixels, ringWidth=ring_width, gr_filtername=filter_name, $
                                   paddedSinogramWidth=padded_width, paddingAverage=padding_average, $
                                   sinoScale=1., reconScale=1.)
    
    log_info, 'Reconstructing two slices with ' + strtrim(num_center,2) + ' different centers ...'
    tomo_recon, tomo_params, proj, recon, center=ctr
    
    log_info, 'Computing entropy...'
    hmin = fltarr(2)
    hmax = fltarr(2)
    for i=0,1 do begin
        hmin[i] = min(recon[num_center, *, *])
        if hmin[i] lt 0 then begin
            hmin[i] *= 2.0
        endif else begin
            hmin[i] *= 0.5
        endelse
        hmax[i] = max(recon[num_center, *, *])
        if hmax[i] lt 0 then begin
            hmax[i] *= 0.5
        endif else begin
            hmax[i] *= 2.0
        endelse
    endfor
    
    entropy = dblarr(num_center, 2)
     for i=0, num_center-1 do begin
        for j=0, 1 do begin
            rec = recon[*, *, i*2+j]
            hist = histogram(rec, min=hmin[j], max=hmax[j], nbins=10000)
            hist = hist > 1
            hist = float(hist) / n_elements(rec)
            entropy[i,j] = -total(hist * alog(hist))
        endfor
        log_info, 'center=' + strtrim(center[i],2) + ' entropy[0,1]= ' +strtrim(entropy[i, 0],2) + ', ' + strtrim(entropy[i, 1],2)
    endfor
    
    min_value = fltarr(2)
    min_index = intarr(2)
    for i=0,1 do begin
        min_value[i] = min(entropy[*, i], minpos)
        min_index[i] = minpos
    endfor
    min_diff = min_value[0] - min_value[1]
    log_info, 'Center for slice 1: ' + string(center[min_index[0]])
    log_info, 'Center for slice 2: ' + string(center[min_index[1]])
    log_info, 'Plotting results ...'
    title='filter='+filter_name+', air_pixels='+strtrim(air_pixels,2)+', padded_width='+strtrim(padded_width,2)
    p1 = plot(center, entropy[*,0], color='red', name='Slice 1', title='IDL '+title)
    p2 = plot(overplot=p1, center, entropy[*,1]+min_diff, color='blue', name='Slice 2')
    leg = legend(target=[p1,p2], position=[.9,.87], /normal)
    
    p1.save, file1+'_idl_entropy_'+title+'.png'
    write_tiff, /float, file1+'_idl_recon_'+title+'.tif', xresol=1, yresol=1, units=1, tiff_scale*recon[*, *, 2*min_index[0]]
    write_tiff, /float, file2+'_idl_recon_'+title+'.tif', xresol=1, yresol=1, units=1, tiff_scale*recon[*, *, 2*min_index[0]+1]

end
```

This is the Python routine:

```
import tomopy
import numpy as np
import logging
import sys
import tifffile
import matplotlib.pyplot as plt

def compute_center_entropy(file1, file2, center_guess):

    center_range = 40.
    center_step = 0.25
    filter_name = 'hann'
    air_pixels = 10
    padded_width = 0
    tiff_scale = 1e6
    mask = False
    
    logging.basicConfig(
        format='%(asctime)s %(levelname)-8s %(message)s',
        level=logging.INFO,
        datefmt='%Y-%m-%d %H:%M:%S')
    
    num_center = int(center_range*2/center_step)
    center = (center_guess - center_range) + np.arange(num_center) * center_step
    
    logging.info('Reading TIFF slices ...')
    slice1 = tifffile.imread(file1+'.tiff')
    slice2 = tifffile.imread(file2+'.tiff')
    s = slice1.shape
    num_pixels = s[1]
    num_projections = s[0]
    if (air_pixels != 0):
        slice1 =slice1.reshape(num_projections, 1, num_pixels)
        slice2 = slice2.reshape(num_projections, 1, num_pixels)
        slice1 = tomopy.normalize_bg(slice1, air=air_pixels)
        slice2 = tomopy.normalize_bg(slice2, air=air_pixels)
        slice1 =slice1.reshape(num_projections, num_pixels)
        slice2 = slice2.reshape(num_projections, num_pixels)
    if (padded_width != 0):
        npad = int((padded_width - num_pixels)/2)
        slice1 = tomopy.misc.morph.pad(slice1, axis = 1, npad =npad, mode = 'edge')
        slice2 = tomopy.misc.morph.pad(slice2, axis = 1, npad =npad, mode = 'edge')
    else:
        npad = 0
    
    padded_width = slice1.shape[1]
    slice1 = tomopy.minus_log(slice1)
    slice2 = tomopy.minus_log(slice2)
    
    logging.info('Creating projection and center arrays ...')
    proj = np.empty((num_projections, num_center*2, padded_width))
    ctr = np.empty(num_center*2)
    for i in range(num_center):
        ctr[i*2] = center[i] + npad
        ctr[i*2+1] = center[i] + npad
        proj[:, i*2, :] = slice1
        proj[:, i*2+1, :] = slice2
    
    theta = np.arange(num_projections) * (np.pi / num_projections)
    
    logging.info('Reconstructing two slices with %d different centers ...', num_center)
    recon = tomopy.recon(proj, theta, ctr, algorithm='gridrec',
                         filter_name=filter_name, sinogram_order=False)
    
    if (npad != 0):
        logging.info('Removing padding ...')
        recon = recon[:, npad:npad+num_pixels, npad:npad+num_pixels]
        logging.info('Removed padding, shape=%s', recon.shape)
    logging.info('Computing entropy ...')
    hmin = np.empty(2)
    hmax = np.empty(2)
    for i in range(2):
        hmin[i] = recon[num_center, :, :].min()
        if hmin[i] < 0:
            hmin[i] *= 2.0
        else:
            hmin[i] *= 0.5
        hmax[i] = recon[num_center, :, :].max()
        if hmax[i] < 0:
            hmax[i] *= 0.5
        else:
            hmax[i] *= 2.0
    
    entropy = np.empty((2, num_center))
    if mask is True:
        recon = tomopy.circ_mask(recon, axis=0)
    for i in range(num_center):
        for j in range(2):
            rec = recon[2*i+j, :, :]
            hist, e = np.histogram(rec, bins=10000, range=[hmin[j], hmax[j]])
            hist = np.clip(hist, 1, None)
            hist = hist.astype('float32') / rec.size
            entropy[j, i] = -(hist * np.log2(hist)).sum()
        logging.info('center=%f, entropy[0,1]=%f, %f', center[i], entropy[0, i], entropy[1, i])
    
    min_value = np.empty(2)
    min_index = np.empty(2, np.int)
    for i in range(2):
        min_index[i] = np.argmin(entropy[i, :])
        min_value[i] = entropy[i, min_index[i]]
    
    logging.info('Center for slice 1: %f', center[min_index[0]])
    logging.info('Center for slice 2: %f', center[min_index[1]])
    
    min_diff = min_value[0] - min_value[1]
    plt.plot(center, entropy[0, :], 'r-', linewidth=.5)
    plt.plot(center, entropy[1, :]+min_diff, 'b-', linewidth=.5)
    title = 'filter=%s, air_pixels=%d, padded_width=%d, mask=%s' % (filter_name, air_pixels, padded_width, mask)
    plt.title('TomoPy ' + title)
    plt.show(block=False)
    plt.savefig(file1+'_tomopy_entropy_'+title+'.png')
    
    # Reconstructions of the two slices at the location of the minimum in entropy
    r1 = recon[2*min_index[0], :, :]
    r2 = recon[2*min_index[1], :, :]
    # IDL and TomoPy reconstructions are rotated 270 degrees.  Why?
    r1 = np.rot90(r1, 3)
    r2 = np.rot90(r2, 3)
    tifffile.imwrite(file1+'_tomopy_recon_'+title+'.tif', tiff_scale*r1)
    tifffile.imwrite(file2+'_tomopy_recon_'+title+'.tif', tiff_scale*r2)
    
if __name__ == "__main__":
    if len(sys.argv) != 4:
        print('Usage: python compute_center_entropy.py file1 file2 center_guess')
    else:
        compute_center_entropy(sys.argv[1], sys.argv[2], int(sys.argv[3]))
```

Each routine is passed the names of the 2 files and the center guess.

There are some variables at the start of each routine to set things like air padding, padded width, filter_name, etc.  These can be edited and the current values are shown in the plots and are contained in the TIFF output file names.

**Comment by MarkRivers** [comment]
The first dataset I tested was the "tomo_00001" dataset that Francesco provided.  It is 2048 wide and 1501 projections.  I used slice 00000 and slice 00009.

These tests were done with the Hann filter, with 10 air pixel normalization, and with no extra padding, since the 2028 width is a power of 2 and there is plenty of air around the sample.

This is the IDL output when running the program on that dataset:
```
IDL> compute_center_entropy, 'Francesco/tomo_00001_sino_00000', 'Francesco/tomo_00001_sino_00009', 1024
Tue May 26 16:33:18 2020  INFO: Reading TIFF slices ...
Tue May 26 16:33:18 2020  INFO: Creating projection and center arrays ...
Tue May 26 16:33:25 2020  INFO: Initializing tomo_params ...
Tue May 26 16:33:25 2020  INFO: Reconstructing two slices with 320 different centers ...
tomo_recon: time to convert to float:   4.1961670e-05
                 time to reconstruct:       23.556308
                          total time:       23.556350
Tue May 26 16:33:48 2020  INFO: Computing entropy...
Tue May 26 16:33:49 2020  INFO: center=984.000 entropy[0,1]= 6.8099236, 6.8190737
Tue May 26 16:33:49 2020  INFO: center=984.250 entropy[0,1]= 6.8096447, 6.8188410
Tue May 26 16:33:49 2020  INFO: center=984.500 entropy[0,1]= 6.8093872, 6.8186507
...
Tue May 26 16:33:58 2020  INFO: center=1063.50 entropy[0,1]= 6.8068638, 6.8173747
Tue May 26 16:33:58 2020  INFO: center=1063.75 entropy[0,1]= 6.8070383, 6.8175526
Tue May 26 16:33:58 2020  INFO: Center for slice 1:       1023.50
Tue May 26 16:33:58 2020  INFO: Center for slice 2:       1023.25
Tue May 26 16:33:58 2020  INFO: Plotting results ...
```
So it found the centers at 1023.50 and 1023.25 respectively.

This is a plot of the entropy.  Note that it is very smooth, with a very well-defined minimum for each slice.

![tomo_00001_sino_00000_idl_entropy_filter=hann, air_pixels=10, padded_width=2048](https://user-images.githubusercontent.com/6115534/82954186-d876b300-9f71-11ea-83fb-223056d3f4b3.png)

This is the output of the Python program:

```
corvette:~/scratch/tomo_data>python -i compute_center_entropy.py Francesco/tomo_00001_sino_00000 Francesco/tomo_00001_sino_00009 1024
2020-05-26 15:23:40 INFO     Reading TIFF slices ...
2020-05-26 15:23:41 INFO     Creating projection and center arrays ...
2020-05-26 15:23:48 INFO     Reconstructing two slices with 320 different centers ...
2020-05-26 15:24:17 INFO     Computing entropy ...
2020-05-26 15:24:18 INFO     center=984.000000, entropy[0,1]=8.309275, 8.313168
2020-05-26 15:24:18 INFO     center=984.250000, entropy[0,1]=8.308990, 8.313540
...
2020-05-26 15:24:50 INFO     center=1063.250000, entropy[0,1]=8.312890, 8.316789
2020-05-26 15:24:50 INFO     center=1063.500000, entropy[0,1]=8.313113, 8.316582
2020-05-26 15:24:50 INFO     center=1063.750000, entropy[0,1]=8.313040, 8.317449
2020-05-26 15:24:50 INFO     Center for slice 1: 1023.250000
2020-05-26 15:24:50 INFO     Center for slice 2: 1023.250000
```

It found the center for each slice at 1023.25.

This is a plot of the entropy.  It is significantly noisier that the entropy in the IDL program, but does have a well-defined minimum at the correct center.

![tomo_00001_sino_00000_tomopy_entropy_filter=hann, air_pixels=10, padded_width=2048, mask=False](https://user-images.githubusercontent.com/6115534/82954346-2986a700-9f72-11ea-82a8-1942555c21ec.png)

This is the ImageJ display of the slice 00000 from the IDL reconstruction.  It is displayed on a gray scale from -1000 to +2500 units.

![image](https://user-images.githubusercontent.com/6115534/82954845-263feb00-9f73-11ea-82c3-7dd42527f086.png)

This is the same slice from the tomopy reconstruction displayed on the same gray scale.

![image](https://user-images.githubusercontent.com/6115534/82954856-2fc95300-9f73-11ea-819b-a8012c6d9028.png)

The tomopy reconstruction has significantly more noise.  This is particularly apparent in the air.

The differences in the reconstructions are even more apparent when zooming in with ImageJ.  This is a 400% zoom of the IDL reconstruction centered in the upper right of the sample:

![image](https://user-images.githubusercontent.com/6115534/82955078-a7977d80-9f73-11ea-8b87-af88adca4c0e.png)

This is that same area in the tomopy reconstruction:

![image](https://user-images.githubusercontent.com/6115534/82955123-c138c500-9f73-11ea-8b4e-b3d2da4594dc.png)

It appears that there is systematic/periodic noise in the tomopy reconstruction that is not present in the IDL reconstruction.

**Comment by MarkRivers** [comment]
I repeated the above but changed both Python and IDL to use air_pixels=0 rather than 10, and to use the "shepp" filter, rather than "hann".

IDL found the centers at 1023.25 for both slices.  This is the plot of the entropy from IDL:

![tomo_00001_sino_00000_idl_entropy_filter=shepp, air_pixels=0, padded_width=2048](https://user-images.githubusercontent.com/6115534/82956117-b7b05c80-9f75-11ea-91eb-c060039b17c1.png)

tomopy found the center for both slices at 1023.50.  This is the plot of the entropy from tomopy.

![tomo_00001_sino_00000_tomopy_entropy_filter=shepp, air_pixels=0, padded_width=2048, mask=False](https://user-images.githubusercontent.com/6115534/82956161-d6aeee80-9f75-11ea-914c-c564ec48b2e6.png)

Again tomopy's entropy is significantly noisier, particularly far from the correct center.  But both have well-defined minima.

This is the IDL reconstruction, displayed on the same -1000 to +2500 gray scale as before:

![image](https://user-images.githubusercontent.com/6115534/82956283-170e6c80-9f76-11ea-8ae3-b917663f0617.png)

This is the tomopy reconstruction.

![image](https://user-images.githubusercontent.com/6115534/82956302-2392c500-9f76-11ea-9d53-8ad3b0d2bc08.png)

Again the tomopy reconstruction is noisier, and this is particularly evident in the air.

This is the same zoom-in region as before from the IDL reconstruction:

![image](https://user-images.githubusercontent.com/6115534/82956513-8be1a680-9f76-11ea-914c-c339b7033060.png)

This is the same region from the tomopy reconstruction:

![image](https://user-images.githubusercontent.com/6115534/82956535-9ac85900-9f76-11ea-837a-d9217979f6ab.png)

They look very similar, except that tomopy is noisier especially in the air.  I don't see any degradation in resolution in IDL in spite of the lower noise.

This is a comparison of the statistics in the entire reconstructed slice.  IDL is the first row, tomopy is the second row.

![image](https://user-images.githubusercontent.com/6115534/82956907-791ba180-9f77-11ea-9685-4e399585b81b.png)

So the tomopy standard deviation is more than 3X that of IDL.  The darkest pixel has a value of -40159 in tomography, but only -3666 in IDL.

These are the statistics for the largest inscribed circle entirely within the sample.  IDL is the first row:

![image](https://user-images.githubusercontent.com/6115534/82957313-4e7e1880-9f78-11ea-9cad-aa37adcb5878.png)

So the mean, standard deviation, and median are all about 33% larger for tomopy than IDL.

**Comment by nikitinvv** [comment]
@MarkRivers I have good results for the parzen filter. Maybe the hann filter is defined incorrectly in tomopy?
![Screen Shot 2020-05-26 at 6 00 21 PM](https://user-images.githubusercontent.com/3603885/82958591-4ecbe300-9f7b-11ea-9c0a-8445377fbb9f.png)
![Screen Shot 2020-05-26 at 6 00 08 PM](https://user-images.githubusercontent.com/3603885/82958594-512e3d00-9f7b-11ea-9121-ee05e40e59d2.png)

**Comment by nikitinvv** [comment]
@MarkRivers as I mentioned before, something wrong with the range of x for defining filters. And I think the problem is in tomopy. There is a parameter pars[0] which scales this range x like here:

```
// Hann filter
float
filter_hann(float x, int i, int j, int fwidth, const float* pars)
{
    return fabsf(2 * x) * 0.5 * (1. + cosf(2 * M_PI * x / pars[0]));
}
```

It is defined in source/tomopy/recon/algorithm.py line 419:

```
'filter_par': np.array([0.5, 8], dtype='float32'),
```

I switched it to 
```
'filter_par': np.array([1, 8], dtype='float32'),
```

After recompiling tomopy and running your test for hann and shepp filters I got:
hann:
![Screen Shot 2020-05-26 at 6 47 41 PM](https://user-images.githubusercontent.com/3603885/82961115-0106a900-9f82-11ea-9f99-19c82069dcb1.png)
![Screen Shot 2020-05-26 at 6 51 15 PM](https://user-images.githubusercontent.com/3603885/82961124-06fc8a00-9f82-11ea-834c-7b4a702d3560.png)

shepp:
![Screen Shot 2020-05-26 at 6 55 55 PM](https://user-images.githubusercontent.com/3603885/82961321-9e61dd00-9f82-11ea-952a-92b95a951416.png)
![Screen Shot 2020-05-26 at 6 56 04 PM](https://user-images.githubusercontent.com/3603885/82961330-a7eb4500-9f82-11ea-9948-91b73e586a38.png)

**Comment by MarkRivers** [comment]
@nikitinvv thanks.  I was able to reproduce your results.  Indeed the entropy is much smoother, and the periodic noise when zooming in is gone.

However, I believe the tomopy reconstruction is still significantly worse than the IDL reconstruction.  This is with air_pixels=10 and hann filter.

This is a horizontal profile through the center of slice 00000 with the IDL reconstuction:

![image](https://user-images.githubusercontent.com/6115534/83029516-5f6e6e80-9ff8-11ea-8f38-1a86ac5cf845.png)

This is the same horizontal profile in the tomopy reconstruction.

![image](https://user-images.githubusercontent.com/6115534/83029581-6e552100-9ff8-11ea-9fe8-5f6b567609ad.png)

Note that with IDL the intensity in the air is quite constant, and is near the correct value of 0.  It decreases slightly to about -200 at the edge of the slice.  However, in the tomopy reconstruction the air intensity is significantly less than the correct value of 0, and it decreases to less than -1000 towards the edges of the image. 

The tomopy reconstruction is also significantly noisier, which is especially obvious in the air.

**Comment by decarlof** [comment]
Is the above cupping related to missing padding in tomopy implementation of gridrec? In tomopy-cli we apply padding before using grid rec to address this. 
Let me run&post this recon with air=10 and hann filter

**Comment by nikitinvv** [comment]
@MarkRivers as I remember, in tomopy there is no oversampling factor for computing FFTs. Instead, they simply pad the data to the next power of 2. I always think this is not good, and now you are rising the same problem. I hope IDL has oversampling 2 for computing FFTs. 

Simple test: in your code set the padded size to 2050. In this case, tomopy will pad it to 4096 giving oversampling 2. These are results for me:

size 2050:
![Screen Shot 2020-05-27 at 9 34 55 AM](https://user-images.githubusercontent.com/3603885/83034817-48327f80-9ffe-11ea-91b1-1926140e6cfe.png)

size 2048:
![Screen Shot 2020-05-27 at 9 35 00 AM](https://user-images.githubusercontent.com/3603885/83034836-4f598d80-9ffe-11ea-8744-f7d3b609e00a.png)

One can see overlapping regions on borders for the case size=2048.

@MarkRivers I would suggest turn off filters and compare results from pure backprojection.

**Comment by decarlof** [comment]
![Screen Shot 2020-05-27 at 3 53 36 PM](https://user-images.githubusercontent.com/5884150/83071235-674b0480-a032-11ea-8041-ce029d46ee87.png)
![Screen Shot 2020-05-27 at 3 53 51 PM](https://user-images.githubusercontent.com/5884150/83071263-703bd600-a032-11ea-8083-bca3a474f691.png)
All turned off, difference is in applying padding before running gridrec. Images are scaled to the same palette.

**Comment by nghia-vo** [comment]
Similar issues related to the padding and the filter used shown here #453

**Comment by nikitinvv** [comment]
@MarkRivers let me also share some of my reconstruction quality tests. To analyze the accuracy of the back-projection operator <img src="https://render.githubusercontent.com/render/math?math=R^*"> used for reconstruction by the filtered backprojection formula I analyze the difference <img src="https://render.githubusercontent.com/render/math?math=W_{2D}f -R^*Wg">, where <img src="https://render.githubusercontent.com/render/math?math=g"> is data, <img src="https://render.githubusercontent.com/render/math?math=W"> is a filter defined in the frequency domain (ramp * w) where w is chosen with respect to the filter shape, and <img src="https://render.githubusercontent.com/render/math?math=W_{2D}"> is the corresponding filter defined in 2D and built upon w.  

So if we use the ramp filter, then <img src="https://render.githubusercontent.com/render/math?math=W_{2D}"> is represented by ones in the frequency domain, if we use the hann filter then W_{2D} is represented by a function containing ones in the middle and slowly decreasing values on the border  (according to the hann filter).

Now, the shepp-logan phantom can be defined for each pixel explicitly by using a sum of ellipses, we can also find explicit projections of these ellipses. So we have f and g explicitly. Next, we can also accurately apply filters like hann by using a huge oversampling in the frequency domain (I used oversampling 4). In conclusion, we have all the components to check accuracy of the back-projection operator by considering the difference <img src="https://render.githubusercontent.com/render/math?math=W_{2D}f -R^*Wg">.

I checked this difference for many methods 4 years ago, except gridrec since I didnt know about it. The following figure shows the error for different methods, including a Fourier-based method Niftyrec (analog of gridrec).
<img width="508" alt="Screen Shot 2020-06-30 at 8 48 57 PM" src="https://user-images.githubusercontent.com/3603885/86197264-a4ffe900-bb1a-11ea-9ed4-67e3246cbdbf.png">
You see the errors are 1e-2 - 1e-4..
The initial phantom function is in the color range [0,1] looks like this:
<img width="537" alt="Screen Shot 2020-06-30 at 9 45 19 PM" src="https://user-images.githubusercontent.com/3603885/86197463-0a53da00-bb1b-11ea-8a47-5e6421f79d53.png">

Now it is interesting to see this error for reconstruction by gridrec.
I considered 2 sizes: 512 and 514 to address the problem of insufficient oversampling for powers of 2. 
1) 512, color range [-0.5,0.5]
<img width="532" alt="Screen Shot 2020-06-30 at 9 50 56 PM" src="https://user-images.githubusercontent.com/3603885/86197830-d62ce900-bb1b-11ea-99f5-ef7256cc752c.png">

2) 514, color range [-0.1 0.1]
<img width="549" alt="Screen Shot 2020-06-30 at 9 49 16 PM" src="https://user-images.githubusercontent.com/3603885/86197858-e644c880-bb1b-11ea-9cdf-4fc8f9352dbf.png">

I assume there are errors in gridrec even for low-frequency components. It would be very interesting to perform the same test for IDL. I have prepared <img src="https://render.githubusercontent.com/render/math?math=W_{2D}f"> and <img src="https://render.githubusercontent.com/render/math?math=Wg"> components: [https://anl.box.com/s/waml34z6ajso6mwonzdrw8f2s3fs837n](url), (f512.tiff is filtered object and R512.tiff is filtered data).  So it is enough just to apply back-projection without filters. The code in tomopy is simple, although you may have to adjust the IDL code by transposing reconstruction or changing the rotation center by 0.5. 

```
import tomopy
import dxchange
import numpy as np

for N in [512, 514]:
    Nproj = 3*N//2

    # hamming filtered object
    f = dxchange.read_tiff('f'+str(N)+'.tiff')
    # hamming filtered data
    R = dxchange.read_tiff('R'+str(N)+'.tiff')
    
    theta = np.linspace(0, np.pi, Nproj, endpoint=False).astype('float32')

    # apply back-projection without filter
    frec = tomopy.recon(R, theta, N/2, algorithm='gridrec',
                        filter_name='none', ncore=1, sinogram_order=True)

    dxchange.write_tiff(frec, 'frec'+str(N), overwrite=True)
    dxchange.write_tiff(frec-f, 'diff'+str(N), overwrite=True)

```

**Comment by MarkRivers** [comment]
Are you aware of this paper that I think does a good job of evaluating the accuracy of Gridrec?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3480277/

**Comment by nikitinvv** [comment]
@MarkRivers sure, I know this paper. They consider different zero padding and check different line plots through reconstruction as the accuracy comparison. They don't show the actual difference to the ground truth object though, because for the unfiltered shepp-logan phantom the difference could be very huge since it contains high frequencies. We cannot use this strategy to compare accuracy with high precision. However, with filtering both the object and data we decrease high frequencies and get reconstructions that can be compared for different methods up to computational precision. 

This way we could compare the back-projection operator in IDL and in Tomopy for different filters computed externally, and understand where tomopy has problems in low frequencies. I hope this test should work well for IDL.
