### ISSUE TITLE
Question : directly access a projection matrix ? 

### ISSUE THREAD

**Issue by s-sajid-ali** [tomopy/tomopy#510]
**Describe the problem**
Is there a way to obtain the projection matrix for 2D parallel beam geometry similar to the W matrix in [this example](https://github.com/astra-toolbox/astra-toolbox/blob/10d87f45bc9311c0408e4cacdec587eff8bc37f8/samples/python/s009_projection_matrix.py) from astra ?

I didn't find an example for the same in `TomoPy` and it wasn't clear if there is a similar function exists from the API reference. Thanks in advance !

**Comment by carterbox** [comment]
No. We don't use matrix multiplications (sparse or otherwise) internally to represent the tomography operator. We have three types of projection operators and only Siddon's method has weights. However, the weights are not easily accessible. Sorry!
