### ISSUE TITLE
Can't import tomopy in Spyder4

### ISSUE THREAD

**Issue by GuibinZan** [tomopy/tomopy#515]
**Describe the problem**
I can install the tomopy sucessfully with Anaconda powershell Prompt(Anaconda3) , but I can't import the tomopy in Spyder.  The Spyder4 was installed with Anaconda. I failed on two computers which are windows 10 systm.  I tried to install an old anaconda, I also couldn't import tomopy in Spyder3.  Could you please help me find the reasons. Thanks.

![sp20200809_153119](https://user-images.githubusercontent.com/32512895/89743183-65031e80-da55-11ea-9ba0-a3c0b6e42234.png)

**Comment by GuibinZan** [comment]
When I installed the tomopy in Anaconda Powershell Prompt(Anaconda3) and activated tomopy, I can import tomopy in this situation.
![sp20200809_154937](https://user-images.githubusercontent.com/32512895/89743424-f4113600-da57-11ea-8dec-b54fe021d2ab.png)

**Comment by carterbox** [comment]
Have you installed `spyder` and `tomopy` into the same Anaconda environment?

**Comment by GuibinZan** [comment]
Firstly, I installed the lastest anaconda, the I installed the tomopy following the guideline 
 web of 'https://tomopy.readthedocs.io/en/latest/install.html' . when I finished the installation, I found there are two environments. one is base, one is tomopy. I didn't know how to install the tomopy in the environment of base. 
![image](https://user-images.githubusercontent.com/32512895/89807704-e0b0aa00-daed-11ea-8baf-93a36d758fb5.png)

**Comment by carterbox** [comment]
You can activate the base environment and install TomoPy like you would any other package from the conda-forge channel.

**Comment by GuibinZan** [comment]
He Daniel, thanks for respose. I tried in the base environment. But it failed from the conda-forge channel. I think there are some conflicts happend.
![image](https://user-images.githubusercontent.com/32512895/89940657-b8e54300-dbce-11ea-9ab6-d5a9ebd07b6d.png)

**Comment by carterbox** [comment]
Make a new environment with only Spyder and TomoPy.

**Comment by GuibinZan** [comment]
Thanks. I worked when I returned back to old version of  anacnoda. Maybe some conficts originated  from the update of Anaconda.

**Comment by neuphyte** [comment]
same problem。 I use the following steps. 1. conda activate base; 2. conda install --channel  conda-forge tomopy. It works, and I can import tomopy.
