### ISSUE TITLE
Questions about alignment procedure

### ISSUE THREAD

**Issue by s-sajid-ali** [tomopy/tomopy#516]
Hi tomopy-developers, 

I'm trying to use the `align_seq` and `align_joint` functions to reconstruct a sinogram while correcting for drifts. While the alignment routines work as expected (sinogram quality improves), the reconstruction itself doesn't change much. 

Here is the improvement in sinograms : 
![image](https://user-images.githubusercontent.com/30510036/92044879-ce203e00-ed44-11ea-96fc-dcc2c4359bf7.png)

And here is the reconstruction for the above sinograms using 50 iterations of `sirt` : 
![image](https://user-images.githubusercontent.com/30510036/92044913-ded0b400-ed44-11ea-9344-a47fdc26b6d0.png)

(For reference, here is a copy of the ipynb notebook : [temp.pdf](https://github.com/tomopy/tomopy/files/5165162/temp.pdf))

As can be seen, the sinograms improve but the reconstruction quality doesn't change. Could someone tell me what I'm missing here ?

PS :  Why does tomopy use only 1 core despite passing `ncore=12` ? 

PPS : Since there is no `ncore` argument for `align_seq/joint`, is it always run with 1 core ? 

Thank you!

**Comment by nghia-vo** [comment]
The sinogram is a 360-degree sinogram. You need to pass the angles to tomopy.recon:
angles360 = np.linspace(0.0, 360.0, height_of_sinogram) * np.pi / 180.0
rec_image = tomopy.recon(sinogram, angles=angles360, center=center, algorithm='gridrec')

**Comment by s-sajid-ali** [comment]
Thanks for the explanation @nghia-vo, I was passing the angles as degrees instead of radians. The results make sense now :
![image](https://user-images.githubusercontent.com/30510036/92664657-31244e80-f2ca-11ea-90cd-c9fb8196f03b.png)


As for the second set of questions, does `tomopy` always use only one thread for reconstructing one slice ?

**Comment by nghia-vo** [comment]
I guess you run your codes on WinOS. tomopy uses multi-threading in Linux. For WinOS the memory is not shared so only one thread model works. @carterbox may explain this better.

**Comment by s-sajid-ali** [comment]
I'm using tomopy on linux (installed from conda) with the following linking : 
```
(tomopy) [sajid@xrm-backup ~]$ conda list | grep tomopy
# packages in environment at /home/sajid/miniconda3/envs/tomopy:
tomopy                    1.7.1           py38hc4caabd_100    conda-forge
(tomopy) [sajid@xrm-backup ~]$ ldd miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/libtomopy.so
        linux-vdso.so.1 (0x00007ffc3def1000)
        libmkl_rt.so => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../libmkl_rt.so (0x00007f9a1f650000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9a1f2ce000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9a1f0ca000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9a1eeaa000)
        libopencv_imgproc.so.4.2 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../libopencv_imgproc.so.4.2 (0x00007f9a1d7c2000)
        libopencv_core.so.4.2 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../libopencv_core.so.4.2 (0x00007f9a1c6f4000)
        libstdc++.so.6 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../libstdc++.so.6 (0x00007f9a1fd76000)
        libgcc_s.so.1 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../libgcc_s.so.1 (0x00007f9a1c6e0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9a1c31d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9a1fd3b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9a1c114000)
        libz.so.1 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../.././libz.so.1 (0x00007f9a1c0f2000)
        liblapack.so.3 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../.././liblapack.so.3 (0x00007f9a1a49b000)        libgomp.so.1 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../.././libgomp.so.1 (0x00007f9a1a46e000)
        libgfortran.so.4 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../././libgfortran.so.4 (0x00007f9a1a33f000)
        libquadmath.so.0 => /home/sajid/miniconda3/envs/tomopy/lib/python3.8/site-packages/tomopy/sharedlibs/../../../../././libquadmath.so.0 (0x00007f9a1a305000)
(tomopy) [sajid@xrm-backup ~]$
```

**Comment by carterbox** [comment]
@nghia-vo, Thanks for you help finding the answer to this question! :+1: 

@s-sajid-ali, Thanks for your patience!

>does tomopy always use only one thread for reconstructing one slice ?

Except for the accelerated methods, each slice gets one thread.
