### ISSUE TITLE
Reconstruction for helical/double-helical scan trajectory

### ISSUE THREAD

**Issue by ankitaeclipse** [tomopy/tomopy#526]
Hello TomoPy Team,

Does TomoPy allow reconstruction for x-ray images that were scanned using helical/double-helical scan trajectories?

Kind Regards,
Ankita Singh

**Comment by carterbox** [comment]
Hi @ankitaeclipse, Not natively; you will have to write a function which shifts/reorders the projections such that corresponding rows of the object are in the same sinogram. If you write a function that does this helical-to-non-helical conversion, I'd be happy to accept a PR!

**Comment by ankitaeclipse** [comment]
Hi @carterbox thank you for the idea! I am new to the area of reconstruction of micro-CT images. I will first try to complete a reconstruction using TomoPy for a circular scan and then, look into writing the function you mentioned above. 
It would help me better understand how to write code for helical to non-helical conversion.

Can we keep this issue for some time? I will get working on this early next week.

Thank you.
Kind Regards,
Ankita Singh

**Comment by carterbox** [comment]
We have a bot that closes issues which are inactive for 60 days. To keep the issue open, you just have to post something.
