### ISSUE TITLE
change verbosity?

### ISSUE THREAD

**Issue by effepivi** [tomopy/tomopy#527]
**Describe the problem**
I would like to stop displaying things like:

Reconstructing 1 slice groups with 1 master threads...

over and over. There must be an option but I can't find it.

**Comment by carterbox** [comment]
Hi @effepivi,

This message is hardcoded using `print()`. However, I would happily accept a PR that changes these print statements to using the [warnings and logging](https://docs.python.org/3/howto/logging.html#logging-basic-tutorial) modules respectively.

https://github.com/tomopy/tomopy/blob/6b053f31b7c3923602ae2709e7cf54e46addbf1e/source/tomopy/recon/algorithm.py#L381-L385

**Comment by effepivi** [comment]
Hi @carterbox,

thanks for the reply. I am using Tomopy (good package BTW) in an optimisation loop, it is therefore called many, many times. I would not mind if I used it in a typical Python script, but I am using it in a Jupyter notebook. The solution you suggest will be ace to make my output neater. In the meantime I'll comment the `print` in my local file.
