### ISSUE TITLE
Reconstruction Ring Glitch

### ISSUE THREAD

**Issue by WilliamJudge94** [tomopy/tomopy#529]
**Describe the problem**
If one scales the projections files up to only contain positive values, this creates a ring glitch in the reconstruction. 

**Basic Reproduce**

Before `tomopy.recon()` one can choose to apply a mathematical operation that removes the negative values in the projections. (For me, it is necessary for the projections to only contain positive values.)

One can either use 

`tomopy.misc.corr.remove_neg()` 

OR one can use the following:

```
# Add the absolute value of the lowest value in the projections
prjs += np.abs(np.min(prjs))

# Add a scalar value to the projections so there are no pixels
# equal to zero (User doesn't have to do this to get the same effect)
prjs += 0.0001
```

**Note** 
These were applied after `prj = tomopy.minus_log(prj)`

**Linked Files Reproduce**
There are two linked files. One which contains the Ring Glitch and one that does not contain the Ring Glitch. These are numpyz files that have variables of reconstructions, prjs, theta, and rot_center. 

reconstructions are the reconstructed set of 10 slices through `tomopy.recon()` using the gridrec algorithm. prjs and theta are the projection data and theta data given to `tomopy.recon()`. rot_center is the rotation center given to `tomopy.recon()`

# No Ring Glitch Sinogram + Recon Images

The Sinogram corresponding with the reconstructed image
<img width="556" alt="Screen Shot 2021-02-10 at 11 55 23 AM" src="https://user-images.githubusercontent.com/37912237/107560850-79aaa580-6ba3-11eb-8b6b-7e653fefdefa.png">

<img width="569" alt="Screen Shot 2021-02-10 at 1 08 55 PM" src="https://user-images.githubusercontent.com/37912237/107560863-7ca59600-6ba3-11eb-9379-1f430f52c2ba.png">

# Ring Glitch Sinogram + Recon Images

The Sinogram corresponding with the reconstructed image. The only difference between these images and the ones above is that I forced the projection values to be >0 (as shown by the min and max values displayed in the sinogram images)
<img width="557" alt="Screen Shot 2021-02-10 at 11 55 49 AM" src="https://user-images.githubusercontent.com/37912237/107560917-89c28500-6ba3-11eb-9e8b-1991f4d4ad0e.png">

<img width="569" alt="Screen Shot 2021-02-10 at 1 09 08 PM" src="https://user-images.githubusercontent.com/37912237/107560926-8b8c4880-6ba3-11eb-81dd-7552e13dc533.png">

**Data Files**
https://drive.google.com/drive/folders/1Zf9x_No_s7IaHBMHmRN_B8n9K5d4Dv6m?usp=sharing

**Expected behavior**
I would assume that scaling the projection files to be greater than 0 wouldn't create artifacts during the reconstruction. And there is no indication of a streak in the Sinogram which would cause the Ring Glitch. 

**Platform Information:**
 - OS: RedHat 7.8
 - Python Version 3.8.5
 - TomoPy Version 1.8.1

**Comment by carterbox** [comment]
Why do you expect the dynamic range of the reconstruction to remain [0, 1.2e-03] after you shifted (added a constant) to the sinogram?

**Comment by WilliamJudge94** [comment]
I can blow out the dynamic range of the non-shifted reconstruction and that ring still does not appear. 

<img width="572" alt="Screen Shot 2021-02-10 at 4 30 48 PM" src="https://user-images.githubusercontent.com/37912237/107581308-80461680-6bbd-11eb-9997-e16fd499095d.png">

**Comment by carterbox** [comment]
Could you please post a python script and downsampled (probably the effect still occurs with at 750 x 1024p) sinogram which reproduces this effect?

**Comment by WilliamJudge94** [comment]
I added a ring_glitch_tutorial.npz file to the Google Drive link. This contains a downsampled dataset of the above images. I have only added 10  Below is a python script that allows you to reproduce the effects. 


```
loaded_data = np.load('/path/to/ring_glitch_tutorial.npz')

prj_tut = loaded_data['prjs'].copy()
theta_tut = loaded_data['theta'].copy()
rot_center_tut = loaded_data['rot_center']

# Attempt to force projections to be positive values
# Uncomment this line out when you want to force the Ring Glitch

#prj_tut += np.abs(np.min(prj_tut))

recon = tomopy.recon(prj_tut, theta_tut,
                    center=rot_center_tut,
                    algorithm='gridrec',
                    ncore=8, )

plt.imshow(recon[0])
```

The Ring Glitch also happens if you call `prj_tut = tomopy.misc.corr.remove_neg(prj_tut, val=neg_remove_value)` instead of `prj_tut += np.abs(np.min(prj_tut))`

Running `plt.imshow(prj_tut[:, 0, :])` displays the sinogram. I have only added 10 sinograms to this dataset to keep the filesize small

**Comment by carterbox** [comment]
The ring effect is occurring because gridrec automatically pads your sinograms with zeros in order to speed up the computation (FFTs of power of 2 array lengths are faster). It can also improve the [quality of the reconstruction](https://github.com/tomopy/tomopy/issues/453), but we don't pad for that reason.

When you alter your sinograms such that the values at the edge are no longer zero, when gridrec pads the sinogram a discontinuity appears as a ring in the reconstructed image.

To avoid this artefact, ensure the edge values of your sinogram are zero or pad in `edge` mode to the nearest power of 2.

```python
import tomopy
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':

    loaded_data = np.load('ring_glitch_tutorial.npz')

    prj_tut = loaded_data['prjs'].copy()
    theta_tut = loaded_data['theta'].copy()
    rot_center_tut = loaded_data['rot_center']

    # sinograms edge is probably zero
    recon = tomopy.recon(
        prj_tut,
        theta_tut,
        center=rot_center_tut,
        algorithm='gridrec',
        ncore=8,
    )
    plt.figure()
    plt.title('original reconstruction')
    plt.imshow(recon[0])

    # remove_neg without a constant value makes negative edge values zero
    recon_remove_neg = tomopy.recon(
        tomopy.remove_neg(prj_tut.copy()),
        theta_tut,
        center=rot_center_tut,
        algorithm='gridrec',
        ncore=8,
    )
    plt.figure()
    plt.title('remove_neg reconstruction')
    plt.imshow(recon_remove_neg[0])

    # Forces edge values to be positive values
    prj_tut += np.abs(np.min(prj_tut))
    recon_ringed = tomopy.recon(
        prj_tut,
        theta_tut,
        center=rot_center_tut,
        algorithm='gridrec',
        ncore=8,
    )
    plt.figure()
    plt.title('shifted reconstruciton')
    plt.imshow(recon_ringed[0])

    # Pad the sinogram with edge values to nearest power of 2
    # gridrec will not add additional padding
    pad = (2048 - prj_tut.shape[-1]) // 2
    pad1 = 2048 - prj_tut.shape[-1] - pad
    prj_tut = np.pad(
        prj_tut,
        pad_width=((0, 0), (0, 0), (pad, pad1)),
        mode='edge',  # Pad with constant zero instead to get ring back
    )
    plt.figure()
    plt.title('padded sinogram')
    plt.imshow(prj_tut[:, 0, :])

    recon_padded = tomopy.recon(
        prj_tut,
        theta_tut,
        center=rot_center_tut + pad,
        algorithm='gridrec',
        ncore=8,
    )
    plt.figure()
    plt.title('padded reconstruction')
    plt.imshow(recon_padded[0, pad:-pad1, pad:-pad1])

    plt.show()
```

**Comment by WilliamJudge94** [comment]
You are a genius! Thank you so much!!!
