### ISSUE TITLE
I can't install tomopy into spyder env

### ISSUE THREAD

**Issue by Beunives** [tomopy/tomopy#536]
I tried to install tomopy using conda. The package is actually installed with its dependencies.
However when I use Spyder I can't import Tomopy.

Any solution?
Thanks

**Comment by carterbox** [comment]
Hi @Beunives, sorry you're having trouble. Unfortunately, you haven't provided very much information.

It sounds like you can import TomoPy outside of Spyder, but not inside of Spyder. If that is the case, then please do some Googling to figure out how to use Spyder with Conda environments.
