### ISSUE TITLE
Fan-beam projections?

### ISSUE THREAD

**Issue by heringerp** [tomopy/tomopy#538]
Hi all,

is it possible to simulate fan-beam projections? If I get it correctly from the documentation, the `tomopy.sim.project.project` function is used for parallel-beam projections. Is there any way to get instead fan-beam projections?

Thank you!

**Comment by carterbox** [comment]
It is possible to simulate fan-beam projections, but TomoPy does not provide this functionality because our reconstruction methods do not handle fan-beam natively. Pull requests are welcome.
