### ISSUE TITLE
What dose `tomopy.project()` do? What's the difference from `skimage.transform.radon()`

### ISSUE THREAD

**Issue by PingHGao** [tomopy/tomopy#541]
Hi, all. I am learning ART algorithms in CT. And I find this wonderful tool.I am using `tomopy.project()` to generate projections for shepp_logan 2d image.  

**The image I use was generated through below code:**
```python
size = 128
shepp2d = tmp.shepp2d(size, np.float32)
```
![shepp](https://user-images.githubusercontent.com/19465753/113998958-25166480-988c-11eb-8a0c-6280fb6ae078.png)

**The projections computed by `tomopy.project()` is as below:** 
```python
n_prj = 150
thetas = np.linspace(0, 180, n_prj + 1)[:-1]

prjs_tomo = tomopy.project(shepp2d, thetas)
```
![prjs_tomo](https://user-images.githubusercontent.com/19465753/113999417-9c4bf880-988c-11eb-8358-3ca39f7a56c6.png)

**The projections computed by `skimage.transform.radon()` is as below:**
```python
prjs_sci = radon(shepp2d[0], thetas)
```
![prjs_radon](https://user-images.githubusercontent.com/19465753/113999582-bf76a800-988c-11eb-8805-0550615dfb46.png)

**I wonder why they are different and why the result of `tomopy.project()` is like that?**

**Comment by carterbox** [comment]
`tomopy.project()` accepts angles in radians not in degrees.

**Comment by PingHGao** [comment]
> `tomopy.project()` accepts angles in radians not in degrees. Please read our API documentation! https://tomopy.readthedocs.io

Thanks for help. Its my fault being careless >_>
