### ISSUE TITLE
Dependencies not installed with tomopy

### ISSUE THREAD

**Issue by srraju** [tomopy/tomopy#542]
![image](https://user-images.githubusercontent.com/29395354/114093544-968efb00-98fe-11eb-945b-11cdefda0a5a.png)
![image](https://user-images.githubusercontent.com/29395354/114093573-a1499000-98fe-11eb-8613-afaa0fd34b62.png)

**Comment by carterbox** [comment]
Please follow the install directions on our docs page! https://tomopy.readthedocs.io/en/latest/install.html

**Comment by srraju** [comment]
I followed the same instructions for installation. When I tried repeating the same steps, it says it is already installed.

**Comment by srraju** [comment]
https://anaconda.org/conda-forge/tomopy

It only worked after following the instructions from anaconda.org. 

conda install -c conda-forge tomopy
conda install -c conda-forge/label/cf201901 tomopy
conda install -c conda-forge/label/cf202003 tomopy

**Comment by carterbox** [comment]
> I followed the same instructions for installation. When I tried repeating the same steps, it says it is already installed.

Yes. Your error messages say that `skimage.registration` and `dxchange` are missing from your conda environment not that `tomopy` is missing.

By following our instructions, you would have created a new conda environment which you would activate with the `conda activate` command, but your screenshot shows that you are using the `base` environment. Installing everything in the `base` environment make life difficult if you are working on many projects with different package requirements.

https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html

**Comment by srraju** [comment]
Hi Daniel,  thanks for the response. Very useful.
