### ISSUE TITLE
how use tomopy toolbox to reconstruct the image of the sinogram prepared from the device to access to a high quality image

### ISSUE THREAD

**Issue by Mohammad-Mgh** [tomopy/tomopy#553]
**Describe the problem**
I used the tomopy toolbox to reconstruct the scanner sinogram. The sinogram is for the cardiac SPECT. The reconstructed image does not have the desired quality. How can I use tomopy features to improve image quality?
My Python code, which is based on the tomopy toolbox, with an output image of one of its slices is given below.

**Python**
```python
import tomopy
import matplotlib.pyplot as plt
import numpy as np


def main():
    obj = np.load('E:\heart tracking & masking\sino1st.npy')
    proj = obj.swapaxes(0, 1).swapaxes(1,2)
    ang = tomopy.angles(proj.shape[0])
    rot_center = proj.shape[2]/2
    rec = tomopy.recon(proj, ang, center=rot_center, algorithm='osem', num_iter=10)
    plt.imshow(rec[24,:,:], cmap = 'hot')
    plt.show()


if __name__ == '__main__':
    main()
```

![cardiac](https://user-images.githubusercontent.com/66469383/125399403-c9490380-e3c5-11eb-91ba-252e7d70c5e3.PNG)

sinogram numpy file is attach below

[sino1st.zip](https://github.com/tomopy/tomopy/files/6806275/sino1st.zip)

**Comment by carterbox** [comment]
Hi @Mohammad-Mgh, the developers of TomoPy are mostly x-ray imaging people, so we may not be familiar with phenomenon that cause imaging artifacts for SPECT. We have a few functions for specific problems such as ring removal and zingers. What specifically are you trying to correct/improve?

**Comment by Mohammad-Mgh** [comment]
Hi @carterbox
In the coronal plane of reconstructed images, there are high-intensity tapes that are artifacts and are not seen in images reconstructed with Cedars software.
This is a problem that is created in images reconstructed with tomopy toolbox.
How can I fix this problem?

![coro](https://user-images.githubusercontent.com/66469383/126635777-9c712693-f3b5-4f63-9d61-a91b405e20d7.PNG)
Reconstructed image with tomopy toolbox in coronal plane



![Cedars](https://user-images.githubusercontent.com/66469383/126635820-900ac26c-0db5-488f-92ee-0ec348410945.PNG)
Reconstructed image with Cedars software in coronal plane
