### ISSUE TITLE
Module missing, version conflicts in benchmarking (following /benchmarking)

### ISSUE THREAD

**Issue by lipigupta** [tomopy/tomopy#560]
**Describe the problem**
Due to the requirement that python version = 3.6 in order to run pyctest, a module 'skbuild' is missing. This bug is known and noted in another issue (https://github.com/tomopy/tomopy/issues/534), but the solution is to use python > 3.8. If these versions cannot be reconciled, how can this benchmarking be run?

**To Reproduce (if applicable)**
Running the "example" code in the `/benchmarking` folder exactly. 

Note: `conda install -n <>...` requires the env already exists, so the instructions should be updated to `conda create -n...`

**Platform Information:**
 - OS: Linux (NERSC, Cori)
 - 
**Additional context**
I attempted this a few different ways, making different environments and trying to select the versions and load modules as needed/upgrade GCC version, but in general I could not find a configuration that ran.

**Comment by jrmadsen** [comment]
Yeah so pyctest uses a deprecated call which queries the Linux OS which was removed in 3.8 so the conda-forge packages are built. But scikit-build (which is the package for skbuild) is available in python 3.6

**Comment by carterbox** [comment]
As Jonathan mentioned, scikit-build is the name of the missing package. The updated example in `benchmarking/README.md` should be somehting like

```shell
export PYTHON_VERSION=3.6

export CONDA_ENV="tomopy-pyctest"

conda create -n ${CONDA_ENV} -c conda-forge -c jrmadsen python=${PYTHON_VERSION} nose numpy h5py scipy scikit-image pywavelets mkl-devel mkl_fft python-coveralls dxchange numexpr coverage timemory pyctest scikit-build

conda activate ${CONDA_ENV}

./pyctest_tomopy.py --globus-path=${HOME}/devel/globus --num-iter=10 --pyctest-site="Cori-Haswell" --pyctest-token-file="${HOME}/.tokens/nersc-cdash"
```

**Comment by lipigupta** [comment]
Thank you @carterbox and @jrmadsen.

I think now I am able to get the benchmarking code to run, but the reason I say "think" is because after executing the updated commands, now I only see: 

```
#############################################
#  ____  _  _  ___  ____  ____  ____  ____  #
# (  _ \( \/ )/ __)(_  _)(  __)/ ___)(_  _) #
#  ) __/ )  /( (__   )(   ) _) \___ \  )(   #
# (__)  (__/  \___) (__) (____)(____/ (__)  #
#                                           #
#############################################

PyCTest args: ['--globus-path=/global/homes/l/lgupta/devel/globus', '--num-iter=10', '--pyctest-site=Cori-GPU', '--pyctest-token-file=/global/homes/l/lgupta/.tokens/nersc-cdash']
  CTest args: []
  CMake args: []
CTest arguments (default): '-V -DSTAGES=Start;Update;Configure;Build;Test;Coverage;MemCheck -S Stages.cmake -j1'
```

and no errors or other messages (or any indication if something is running or not...). Is there a way to check?

**Comment by lipigupta** [comment]
Another question for @carterbox @jrmadsen:

Apparently the CDash is broken? I get an error when I try to view the benchmarking results from the link provided. 

Is there a way to produce a log file or some other way to view the results while the dashboard is down? Thanks!

**Comment by jrmadsen** [comment]
Add `-- -V` to the end of the command to get more verbose output. And I fixed the cdash and recreated the tomopy project so you should be able to submit to it now

**Comment by jrmadsen** [comment]
Oh sorry, `-- -VV`
