### ISSUE TITLE
Tomopy conda install not working?

### ISSUE THREAD

**Issue by lipigupta** [tomopy/tomopy#562]
**Describe the problem**
The benchmarking as described does not work (many depreciated packages, warnings, compile errors), so I am attempting a fresh install of tomopy and build some simple benchmarks myself. 

I am installing tomopy via conda, using the instructions here: https://tomopy.readthedocs.io/en/latest/install.html

**Expected behavior**
Have the env set up, with the github repo. Attempting to run tests via `py.test test/test_tomopy/test_recon` and get the following errors. 

**Helpful images (if applicable)**
`conda create --name tomopy --channel conda-forge tomopy`

results in: 
![image](https://user-images.githubusercontent.com/52291168/134578863-6699286c-be1b-449d-8501-15d6fd4ba754.png)

![image](https://user-images.githubusercontent.com/52291168/134578451-a09de336-30cc-4f88-8623-7e23d9e4e0f6.png)

**Platform Information:**
 - OS: macOS

**Additional context**

**Comment by jrmadsen** [comment]
Easiest way to figure out how to run the testing of any project is to locate the CI script(s). For tomopy, this is [azure-pipelines.yml](https://github.com/tomopy/tomopy/blob/master/azure-pipelines.yml).

**Comment by lipigupta** [comment]
I don't think the issue how to run the test, but why is the install not resulting in the tomopy module being correctly available?

**Comment by carterbox** [comment]
I'm not exactly familiar with how environments on CORI are setup, but I would not expect `which tomopy` to work. `tomopy` is not a binary; it is a python module. To test whether a python module is installed you need to open the python interpreter in your environment and try to `import tomopy`.

**Comment by lipigupta** [comment]
@carterbox yes, I did try that and it does import (as far as I can tell).

**Comment by jrmadsen** [comment]
As I said, look to the CI script. Based on what you posted, you did the equivalent of this:

https://github.com/tomopy/tomopy/blob/bf34307f0482ebda8b0877231c67baea84db6175/azure-pipelines.yml#L81

and

https://github.com/tomopy/tomopy/blob/bf34307f0482ebda8b0877231c67baea84db6175/azure-pipelines.yml#L86

but not this:

https://github.com/tomopy/tomopy/blob/bf34307f0482ebda8b0877231c67baea84db6175/azure-pipelines.yml#L87

**Comment by lipigupta** [comment]
Ok, perhaps this needs to be updated:
![image](https://user-images.githubusercontent.com/52291168/134584714-def30fef-6e88-40f9-be9f-39caab6e6e6d.png)

**Comment by carterbox** [comment]
@lipigupta. Check that pytest is running in the same environment that tomopy is installed. i.e. py.test is a binary which could be in any environment. The safer way would be to run `python -m pytest test/`

**Comment by jrmadsen** [comment]
Why do you have the source code checked out if you are installing tomopy from conda?

**Comment by lipigupta** [comment]
So I have access to testing materials - I am not using tomopy for my own data, so I want access to pre-written scripts/data for testing.

**Comment by jrmadsen** [comment]
But you have an `_skbuild` folder... meaning at some point you ran `python setup.py install`... Did you abort that build? If so, it's possible that there is an empty folder or partial build left over that is getting picked up as the path to tomopy (instead of the one in the conda install folder) and it is causing a failed import.

**Comment by lipigupta** [comment]
@jrmadsen Yes I see your point - and I think I got some local help to fix the issues I was having. Sorry for all the screenshots and confusion, I think I got it! 
Thanks again!
