### ISSUE TITLE
single tiff image for dark or reference: problem with normalization

### ISSUE THREAD

**Issue by samwelborn** [tomopy/tomopy#568]
Normalization does not occur correctly when a single tiff is loaded into tomopy using dxchange.reader.read_tiff.

Load in a single tiff image (of size (X,Y)) using dxchange.reader.read_tiff for your dark and reference image.

Upon normalization,
```python
tomopy.prep.normalize.normalize(arr, flat, dark, cutoff=None, ncore=None, out=None)
```
the background is not properly subtracted. This is because tomopy.prep.normalize.normalize takes the mean value on axis 0.
```python
    arr = dtype.as_float32(arr)
    l = np.float32(1e-6)
    flat = np.mean(flat, axis=0, dtype=np.float32)
    dark = np.mean(dark, axis=0, dtype=np.float32)
```

If the length of the imported tiff np.array.shape is 2 (i.e. (number of X pixels, number of Y pixels)), you should not be normalizing on the first axis. This will result in improper background subtraction. 

I fixed this by adding an axis to the np array of the tiff before normalization.
```python
if len(flat.shape) == 2:
    flat = flat[np.newaxis,:,:]
```

**Comment by carterbox** [comment]
Hi @samwelborn, thanks for your concern. However, the [documentation](https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.normalize.html#tomopy.prep.normalize.normalize) clearly states that `flat` is expected to be a 3D array.

> arr (ndarray) – 3D stack of projections.
> 
> flat (ndarray) – 3D flat field data.
> 
> dark (ndarray) – 3D dark field data.

If you would like to open a pull request which implements automatically converting 2D flat/dark parameters to 3D flat/dark for all functions or raises an error when these arrays are missing a dimension, then I would happily review it.
