### ISSUE TITLE
Installation on Windows 7

### ISSUE THREAD

**Issue by mlerotic** [tomopy/tomopy#57]
Hi,
Do you have instructions for installing tomopy on Windows 7 machine? I have tried manually installing boost and fftw and running 
python setup.py install 
using Python 2.7.9 but I keep getting an error:

tomopy/tools/fftw.cpp(3) : fatal error C1083: Cannot open include file: 'fftw3.h': No such file or directory

Thank you.
Mirna Lerotic

**Comment by dgursoy** [comment]
Hi Mirna, did you set your environment variables? Please try setting ```C_INCLUDE_PATH ``` and ```LD_LIBRARY_PATH ``` to the folders where boost and fftw header and library files are located. I haven't used Win 7 but I guess you should be able to set them somewhere from settings.

**Comment by mlerotic** [comment]
Hi,
Thank you for your quick reply. I defined both C_INCLUDE_PATH and LD_LIBRARY_PATH to point to the folders where boost and fftw header and library files are located, but I still get the same error:
tomopy/tools/fftw.cpp(3) : fatal error C1083: Cannot open include file: 'fftw3.h': No such file or directory

The missing file fftw3.h is in the specified folder.

Thank you,
Mirna

**Comment by dgursoy** [comment]
Could you provide the full traceback when you try to build?

**Comment by mlerotic** [comment]
Hi,
Here is the full traceback:


D:\mirna\Phyton\tomopy\v003>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to tomopy.egg-info\requires.txt
writing tomopy.egg-info\PKG-INFO
writing top-level names to tomopy.egg-info\top_level.txt
writing dependency_links to tomopy.egg-info\dependency_links.txt
reading manifest file 'tomopy.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tomopy.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'tomopy.lib.libfftw' extension
C:\Users\Mirna Lerotic\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC -I\boost_1
_57_0;C -I\fftw; -ID:\mirna\Phyton\tomopy\v003\tomopy\algorithms\recon\gridrec -
IC:\Python27\include -IC:\Python27\PC /Tptomopy/tools/fftw.cpp /Fobuild\temp.win
-amd64-2.7\Release\tomopy/tools/fftw.obj
fftw.cpp
C:\Users\Mirna Lerotic\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, bu
t unwind semantics are not enabled. Specify /EHsc
tomopy/tools/fftw.cpp(3) : fatal error C1083: Cannot open include file: 'fftw3.h
': No such file or directory
error: command 'C:\\Users\\Mirna Lerotic\\AppData\\Local\\Programs\\Common\\Micr
osoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit stat
us 2

**Comment by aglowacki** [comment]
How did you define  C_INCLUDE_PATH and LD_LIBRARY_PATH?
Did you try opening command prompt and doing:
c:\> cd tomopy-0.0.3 
c:\tomopy-0.0.3> set  C_INCLUDE_PATH=c:\libFFTW3\include
c:\tomopy-0.0.3> set  LD_LIBRARY_PATH=c:\libFFTW3\lib
c:\tomopy-0.0.3> pyhton setup.py install

you may need to put quotes around the path if there are spaces ex:
> set  C_INCLUDE_PATH="c:\My Libs\libFFTW3\include"

**Comment by mlerotic** [comment]
I defined environment variables. I have also tried using set but it still fails:

D:\mirna\Phyton\tomopy\v003>set C_INCLUDE_PATH=C:\fftw

D:\mirna\Phyton\tomopy\v003>set LD_LIBRARY_PATH=C:\fftw

D:\mirna\Phyton\tomopy\v003>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to tomopy.egg-info\requires.txt
writing tomopy.egg-info\PKG-INFO
writing top-level names to tomopy.egg-info\top_level.txt
writing dependency_links to tomopy.egg-info\dependency_links.txt
reading manifest file 'tomopy.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tomopy.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'tomopy.lib.libfftw' extension
C:\Users\Mirna Lerotic\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC -I\fftw -I
D:\mirna\Phyton\tomopy\v003\tomopy\algorithms\recon\gridrec -IC:\Python27\includ
e -IC:\Python27\PC /Tptomopy/tools/fftw.cpp /Fobuild\temp.win-amd64-2.7\Release\
tomopy/tools/fftw.obj
fftw.cpp
C:\Users\Mirna Lerotic\AppData\Local\Programs\Common\Microsoft\Visual C++ for Py
thon\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, bu
t unwind semantics are not enabled. Specify /EHsc
tomopy/tools/fftw.cpp(3) : fatal error C1083: Cannot open include file: 'fftw3.h
': No such file or directory
error: command 'C:\\Users\\Mirna Lerotic\\AppData\\Local\\Programs\\Common\\Micr
osoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit stat
us 2

-----------
I have also checked that fftw3.h is in C:\fftw.

Thanks!
Mirna

**Comment by aglowacki** [comment]
I just noticed you are using MSVC for Python compiler. The windows env variables are INCLUDE and LIB.
Try 
c:\tomopy-0.0.3> set INCLUDE=%INCLUDE%;c:\fftw
c:\tomopy-0.0.3> set LIB=%LIB%;c:\fftw
c:\tomopy-0.0.3> pyhton setup.py install

This should append c:\fftw to the current include and lib env vars.

**Comment by dgursoy** [comment]
If this is the case you may want to change C_INCLUDE_PATH and LD_LIBRARY_PATH with INCLUDE and LIB in setup.py file as well.

**Comment by decarlof** [comment]
This has been addressed (thank you Arthur!). Please clone the latest version of tomopy (clone the tomopy repository git clone https://github.com/tomopy/tomopy.git tomopy) and follow instructions at:
http://tomopy.github.io/tomopy/install.html#windows-installation
