### ISSUE TITLE
information about h5 files

### ISSUE THREAD

**Issue by tae7841** [tomopy/tomopy#580]
**Platform Information:**
 - OS: Windows 10
 - Python Version : 3.9
 - TomoPy Version 1.11

I am interested in the process of making 'tooth.h5' and 'reader.h5' files.
Is there a python code or other way to make those two h5 files?

Thank you.

**Comment by decarlof** [comment]
please have a look [here](https://dxfile.readthedocs.io/en/latest/source/api/dxfile.html) and at [these examples ](https://dxfile.readthedocs.io/en/latest/source/demo/doc.python.html) on how to generate a [simple](https://dxfile.readthedocs.io/en/latest/_downloads/db2553c62bcbc3a79a9da851a16a7726/simple.py) and [full](https://dxfile.readthedocs.io/en/latest/_downloads/730da4dd532aacb4bc347386ae8ffe49/full.py) dxfile.

**Comment by tae7841** [comment]
Thanks, but I'd like to know how to make the "tooth.h5" and "reader.h5" files.

**Comment by decarlof** [comment]
The original data stored in tooth.h5 were collected at a synchrotron facility as a stack of tiff projections. tooth.h5 was created using [simple](https://dxfile.readthedocs.io/en/latest/_downloads/db2553c62bcbc3a79a9da851a16a7726/simple.py) writer example. To access more tomographic data please have a look at [tomoBank](https://tomobank.readthedocs.io/en/latest/index.html)
