### ISSUE TITLE
Which tomopy algorithms do you typically use?

### ISSUE THREAD

**Issue by perlmutter** [tomopy/tomopy#582]
Hi,

I've recently tried all the available tomopy algorithms on phantom data and had mixed success. A couple algorithms don't seem to give unusable results. Specifically,
--fbp looks more like simple back projection with no ramp filter
--quad produces all zeros
--quad_pm: unclear if changing "reg_par" affects reconstruction? 
--astra ART produces constant image when called through tomopy wrapper (fine when called via native astra) 

Is this behavior consistent with other's experience? If not perhaps I am calling them inccorectly (I can provide code of my tests). 

More importantly, In general, which tomopy/astra algorithms do you typically use for your reconstructions (for both CPU and GPU)? 

Thanks

**Comment by carterbox** [comment]
FBP is actually not filtered; it is only plain back projection. See https://github.com/tomopy/tomopy/issues/421

A comparison of various algorithms and their expected results on simulated data is published here: https://tomopy.github.io/

**Comment by perlmutter** [comment]
Thanks Daniel, that's a great site. It looks like some of the algorithms indeed don't produce any output, though the names don't quite match up to what's in the tomopy readthedocs. Maybe "grad" is the same as "quad" and 'tikh" the same as "quad_pm"? 

I'd recommend updating the tomopy readthedocs with accurate names of all the algorithms, including if they should not be expected to work, currently. Would also be great if you linked that site to the docs as well, probably in the algorithms page.

**Comment by carterbox** [comment]
>  It looks like some of the algorithms indeed don't produce any output, though the names don't quite match up to what's in the tomopy readthedocs. Maybe "grad" is the same as "quad" and 'tikh" the same as "quad_pm"?

No. "grad" is "grad" and "tikh" is "tikh". There is no "quad_pm" or "quad".

https://tomopy.readthedocs.io/en/latest/api/tomopy.recon.algorithm.html#tomopy.recon.algorithm.recon
