### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by zhangy6x** [tomopy/tomopy#588]
After following the installation guide ([here](https://tomopy.readthedocs.io/en/latest/install.html)), I got an error (screenshot attached) when importing `tomopy`.

tomopy 1.12.1
python 3.10.5
Windows 10

<img width="807" alt="screenshot" src="https://user-images.githubusercontent.com/29611336/182446863-735aa10b-87c5-4278-8927-543f4c14bb53.png">

**Comment by carterbox** [comment]
Works for me. There should be a package called `libtomo` installed in your conda environment. Could you please check whether it is installed.

**Comment by zhangy6x** [comment]
> Works for me. There should be a package called `libtomo` installed in your conda environment. Could you please check whether it is installed.

Yes, `libtomo 1.12.1` is installed in my conda env.

**Comment by carterbox** [comment]
Please share an export of your conda-environment.

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment

**Comment by zhangy6x** [comment]
[env.zip](https://github.com/tomopy/tomopy/files/9284506/env.zip)

**Comment by carterbox** [comment]
Still works for me.

What is the output of ctypes find_library?

```
python -c "from ctypes.util import find_library; print(find_library('tomo-recon'))"
```

**Comment by zhangy6x** [comment]
It found tomo-recon.dll when my tomopy conda env is activated, but found none when the base conda env is activated. 
I think I found the issue, I only had jupyter notebook installed in my base env and used ipykernel to install kernels of my tomopy env. I just installed jupyter notebook in my tomopy env and launched from there. Tomopy is imported successfully now. Thanks for your help!

I have another quick question regarding the unit of the recon output, are the value attenuation coefficients in "/cm", "/mm", or "/pixel"? Maybe I was looking at the wrong place. I was not able to find this in the documentation.

**Comment by carterbox** [comment]
Per pixel.

**Comment by zhangy6x** [comment]
thank you!

**Comment by mobinmadani** [comment]
> It found tomo-recon.dll when my tomopy conda env is activated, but found none when the base conda env is activated. I think I found the issue, I only had jupyter notebook installed in my base env and used ipykernel to install kernels of my tomopy env. I just installed jupyter notebook in my tomopy env and launched from there. Tomopy is imported successfully now. Thanks for your help!
> 
> I have another quick question regarding the unit of the recon output, are the value attenuation coefficients in "/cm", "/mm", or "/pixel"? Maybe I was looking at the wrong place. I was not able to find this in the documentation.

Hi,
I have the same problem. Would you please explain exactly how you addressed the issue

**Comment by mobinmadani** [comment]
> 

Hi,
I am using colab and have the same problem. Would you please explain how exactly you addressed the issue?
Thank you in advance.

**Comment by mobinmadani** [comment]
> It found tomo-recon.dll when my tomopy conda env is activated, but found none when the base conda env is activated. I think I found the issue, I only had jupyter notebook installed in my base env and used ipykernel to install kernels of my tomopy env. I just installed jupyter notebook in my tomopy env and launched from there. Tomopy is imported successfully now. Thanks for your help!
> 
> I have another quick question regarding the unit of the recon output, are the value attenuation coefficients in "/cm", "/mm", or "/pixel"? Maybe I was looking at the wrong place. I was not able to find this in the documentation.

Hi,
I am using colab and have the same problem. Would you please explain how exactly you addressed the issue?
Thank you in advance.

**Comment by zhangy6x** [comment]
> 

Sorry, I only used jupyter notebook in my case. No experience with colab.
