### ISSUE TITLE
ModuleNotFoundError: TomoPy links to compiled components which are installed separately and loaded using ctypes.util.find_library(). A required library, tomo-recon, was not found.

### ISSUE THREAD

**Issue by Madani-Irsa** [tomopy/tomopy#590]
I just created tomopy env successfully in "colab" (Using condacolab for that) but condacolab cannot activate it  and when I import tomopy this error comes up. any solutions?

**Comment by matangpanchal** [comment]
I also had same problem 2 days back, after checking the code of find_library() I found that it only looks in the location specified in path variables, so either "C:\Users\[yourusernamehere]\.conda\pkgs\libtomo-1.12.1-h1234567_0\Library\bin" to the path or copy the contents of above path and paste to any location which is included in path like "C:\ProgramData\Anaconda3\Library\bin". I would prefer the first method

**Comment by falkmielke** [comment]
I experience the same issue on (arch) linux. Admittedly, it is the latest python and everything up to date; no conda, but I made sure to have all the requirements. I have compiled tomopy from the git source as described in the dev docs: first the python part, then the cmake. Booth seemed fine. I have even appended the $PATH with the tomopy base directory.

- Any hints on how to make "find_library()" find the "tomo-recon"?
- Maybe this hints at a more general problem with recent installations?

Thank you for your advice!

**Comment by carterbox** [comment]
> no conda,

You if you are build from source, then you can choose where the shared libraries are installed. Install to the place that [find_library()](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries) looks. This function is from the standard library.

**Comment by falkmielke** [comment]
Thank you for this initial pointer! But there must be more to it, maybe something stupid I miss:
I can import ctypes.util.find_library and it will find 'tomo-recon'!
However, tomopy does not import...

```
user@hostname ~> python
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('tomo-recon')
'libtomo-recon.so'
>>> import tomopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/tomopy/__init__.py", line 68, in <module>
    from tomopy.misc.corr import *
  File "/usr/lib/python3.10/site-packages/tomopy/misc/corr.py", line 59, in <module>
    import tomopy.util.extern as extern
  File "/usr/lib/python3.10/site-packages/tomopy/util/extern/__init__.py", line 92, in <module>
    from tomopy.util.extern.recon import *
  File "/usr/lib/python3.10/site-packages/tomopy/util/extern/recon.py", line 83, in <module>
    LIB_TOMOPY_RECON = c_shared_lib("tomo-recon")
  File "/usr/lib/python3.10/site-packages/tomopy/util/extern/__init__.py", line 76, in c_shared_lib
    raise ModuleNotFoundError(
ModuleNotFoundError: TomoPy links to compiled components which are installed separately and loaded using ctypes.util.find_library(). A required library, tomo-recon, was not found.
>>> exit()
```
... except if I `cd` to the directory where the ".so" files are located.

```
user@hostname ~> cd /usr/lib
user@hostname /u/lib> python
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('tomo-recon')
'libtomo-recon.so'
>>> import tomopy
>>> exit()
```

(sidenote: I used `-DCMAKE_INSTALL_LIBDIR=/usr/lib`)

Thanks for further help!

**Comment by falkmielke** [comment]
I think I got it: the `os.path.exists` in `util/extern/__init__.py:c_shared_lib` does not find the file because 'find_library` does not return the full path!

**Comment by carterbox** [comment]
I think I added the call to `os.path.exists()` because `ctypes.cdll.LoadLibrary()` needs a full path and not just a filename.

What happens when you run this?
```
>>> from ctypes.util import find_library
>>> from ctypes.cdll import LoadLibrary
>>> ctypes.cdll.LoadLibrary(find_library('tomo-recon'))
```

**Comment by falkmielke** [comment]
confirmed, the following works for me on (almost) plain vanilla `5.19.8-arch1-1`, `Python 3.10.7`, `linux posix`:
```
print (sys.platform, os.name)
[...]
    sharedlib = ctypes.util.find_library(lib_name)
    print (lib_name, ctypes.util.find_library('tomo-recon'))
    ctypes.cdll.LoadLibrary(ctypes.util.find_library('tomo-recon'))
    return
```
which results in all libs loading:
```
>>> import tomopy
linux posix
tomo-accel libtomo-recon.so
tomo-recon libtomo-recon.so
tomo-gridrec libtomo-recon.so
tomo-prep libtomo-recon.so
tomo-misc libtomo-recon.so
```

So the ctypes library functions seem to be compatible: neither returns or requires the full path; i presume "LoadLibrary" knows where to look from my system $PATH.

In contrast, `os.path.exists` is a different library, checks absolute path, and thus breaks the condition with the shortened `find_library` output. 
... at least on linux. In the documentation you linked above, they explicitly mention that behavior is OS-dependent. 
Probably best solution is to move the library loading to the "switch"-like OS conditionals you have just before the lib loading?

**Comment by falkmielke** [comment]
here and attempt to solve it, yet I cannot test other OS:

```
def c_shared_lib(lib_name, error=True):
    """Get the path and import the C-shared library.

    The ctypes.util.find_library function preprends "lib" to the name.
    """
    load_dll = ctypes.cdll.LoadLibrary # default library loading function
    ext = '.so' # derault extension
    msg = '' # a debugging message

    # change platform-specific library conventions:
    if sys.platform == 'darwin':
        ext = '.dylib'
    if os.name == 'nt':
        ext = '.dll'
        load_dll = ctypes.windll.LoadLibrary

    # find the library
    sharedlib = ctypes.util.find_library(lib_name)

    if sharedlib:
        try:
            return load_dll(sharedlib)
        except OSError as oserr:
            # the module was found, but the file was wrong
            msg = f'(looked at the path "{sharedlib}" but did not find it, please check your $PATH, working directory, and library directory!)'

    # explanation for debugging
    explanation = (
        'TomoPy links to compiled components which are installed separately'
        ' and loaded using ctypes.util.find_library().'
    )
    if error:
        # the module was not found
        raise ModuleNotFoundError(
            explanation +
            f' A required library, {lib_name}, was not found. {msg}')
    # warn if errors are disabled
    warnings.warn(
        explanation +
        'Some functionality is unavailable because an optional shared'
        f' library, {sharedlib}, is missing. {msg}', ImportWarning)

```
