### ISSUE TITLE
How to output the 3 D visualization results

### ISSUE THREAD

**Issue by fsqvictor** [tomopy/tomopy#592]
By learning the examples, I know that the image results can be displayed in two dimensions. However, I still don't understand whether the program can do 3 D visualization？

**Comment by matangpanchal** [comment]
> By learning the examples, I know that the image results can be displayed in two dimensions. However, I still don't understand whether the program can do 3 D visualization？

Look at the simple itk library, it has several output options, which will save volume data to mhd or other formats and then you can open it in volume viewer softwares.
