### ISSUE TITLE
Trying 3D Reconstructruction of Metal foam from 2D Projections (X-ray images) but facing issue using Tomopy

### ISSUE THREAD

**Issue by indrajeettambe** [tomopy/tomopy#602]
#I have parallel beam synchrotron tomographic data of a sample- metallic foam. I have collected 3600 projection data (3600 2D images from synchrotron) with a step size of 0.1 degree. I want to reconstruct that data into a 3D image. I am trying to use tomopy for that but facing some issue.

A piece of sample from this-
![metallschaum-klein](https://user-images.githubusercontent.com/119943034/218775861-2735453e-0c82-4e63-b613-a3e9ffbd9990.jpg)

some projection tiff files-
![Screenshot_43](https://user-images.githubusercontent.com/119943034/218773608-d55b7da2-8613-46fb-958d-9f3bb1946a79.jpg)
![Screenshot_44](https://user-images.githubusercontent.com/119943034/218773662-781ed39f-1bf9-47c7-be29-901d1ac8f7b4.jpg)

**Some part of the code**
![Screenshot_41](https://user-images.githubusercontent.com/119943034/218773884-8e5fa38f-e893-423a-998a-e7ad2aa9525b.jpg)
![Screenshot_42](https://user-images.githubusercontent.com/119943034/218773914-448fb34d-8b20-4002-81bc-489e44650134.jpg)

rc= 634  #631.638#1318//2
print('Reconstructing using the following settings:')
for key,val in pars['recon_options'].items():
    print('{}: {}'.format(key,val))

recon = rec.reconstruct(dc,theta,center=rc, **pars['recon_options'])
#recon[recon < 0] = 0

pars['circular_mask'] = False
pars['mask_options']['ratio']=0.9
    
if pars['circular_mask']:
        recon = tomopy.circ_mask(recon, **pars['mask_options'])
s1,s2,s3 = recon.shape        
fig,ax = plt.subplots(3,1,figsize=(12,12))
ax[0].imshow(recon[s1//2],aspect='equal',cmap=cm.gray)
ax[1].imshow(recon[:,s2//2,:],aspect='equal',cmap=cm.gray)
[ax[2].imshow(recon[:,:,s3//2],aspect='equal',cmap=cm.gray)]

output- its blurry.
![Screenshot_40](https://user-images.githubusercontent.com/119943034/218774028-b8a9734c-2b0d-4f41-b6a1-5827ff4c1970.jpg)

Also note that tomopy is not able to find center for this. its giving some strange value.

@AdvancedPhotonSource

**Comment by carterbox** [comment]
> Also note that tomopy is not able to find center for this. its giving some strange value.

You suspect that the automatic center finding function is not working for you dataset, so use the [manual finding center function](https://tomopy.readthedocs.io/en/stable/api/tomopy.recon.rotation.html#tomopy.recon.rotation.write_center).

**Comment by lucifer-dev-cyber** [comment]
![Screenshot_45](https://user-images.githubusercontent.com/119943034/218848808-2e5f6beb-697c-46e4-ab67-2396735745a3.jpg)

Tried this but no reconstruction was saved in the respective folder. Anything more is suppose to be done?

**Comment by carterbox** [comment]
Look in `./file_name`?

**Comment by lucifer-dev-cyber** [comment]
Here is the folder.... its empty.

![Screenshot_46](https://user-images.githubusercontent.com/119943034/218998122-258a0087-de37-4429-8971-1ecb3e45c184.jpg)

**Comment by lucifer-dev-cyber** [comment]
Another issue here is center of rotation may be tilted along a line. so it is not really fixed for all slices.

**Comment by carterbox** [comment]
In the example you provided, you assign dpath to the literal string `'file_name'` not the variable `file_name`. Look in the working directory of your jupyter notebook, not `'/asap3/petra/[other paths]/recon_center`. Or fix your code.

**Comment by lucifer-dev-cyber** [comment]
I got you point. but that would not solve the issue which I mentioned earlier. "Another issue here is center of rotation may be tilted along a line. so it is not really fixed for all slices."

Is it possible for you to share your mail or discord or any other communication channel. Because the issue with tilted axis seems a bit complex but when it is fixed, it would give some amazing reconstruction.

**Comment by carterbox** [comment]
Manually find the center for 5 points along the volume (top, middles, bottom), then fit the centers to a line as a function of slice index. Use interpolation to estimate the centers for slices between the ones you manually found.

**Comment by lucifer-dev-cyber** [comment]
I will make a google drive with some part data and share the ipynb file. May be you can spot a issue in finding the center and fitting the center. Actually manually doing it is not the most relevant option as I need to do the same for wide rage of samples and wide range of scans.

**Comment by lucifer-dev-cyber** [comment]
Here is the drive link.

https://drive.google.com/drive/folders/1qvPyHyhwxzFQYujDmVutBhl2H42tqb5_?usp=sharing

Data seems bit big, so i have croped it and generated npy array. Please request you to have a look.

Thanks in advance :)

**Comment by lucifer-dev-cyber** [comment]
Any updates?

**Comment by carterbox** [comment]
Sorry, but I don't have the bandwidth to debug your entire reconstruction workflow. If you have a small, specific, self-contained code example of something that is not working, I can take a look.

Also, we have multiple different algorithms for automatically estimating the rotation center. Perhaps, one of the others works better for your dataset.

**Comment by nghia-vo** [comment]
I can help Daniel here. Note that the sinogram is 360-degree sinogram, so to use find_center_vo we have to pass a half of the sinogram.

```python
import tomopy
import numpy as np
from PIL import Image
import multiprocessing as mp
import algotom.prep.correction as corr

def load_image(file_path):
    try:
        mat = np.asarray(Image.open(file_path), dtype=np.float32)
    except IOError:
        print(("No such file or directory: {}").format(file_path))
        raise
    if len(mat.shape) > 2:
        axis_m = np.argmin(mat.shape)
        mat = np.mean(mat, axis=axis_m)
    return mat

def save_image(file_path, mat):
    image = Image.fromarray(mat)
    try:
        image.save(file_path)
    except IOError:
        print(("Couldn't write to file {}").format(file_path))
        raise
    return file_path


if __name__ == '__main__':
    print("Start......")
    # Load data, note that the projections are in the range of 0-360 degree
    proj = np.load("E:/Tomo_data/tomo/proj.npy")
    flat = np.mean(np.load("E:/Tomo_data/tomo/flat.npy"), axis=0)
    dark = np.mean(np.load("E:/Tomo_data/tomo/dark.npy"), axis=0)
    ncore = mp.cpu_count() - 1
    (depth, height, width) = proj.shape
    angles = np.linspace(0.0, 360.0, depth) * np.pi / 180.0

    idx = 30
    # Before tilted correction
    sinogram = (proj[:, idx] - dark[idx]) / (flat[idx] - dark[idx])
    # Find center of rotation:
    # Reduce number of projections as 3600 projections are more than enough
    # for finding the center. Note that we need to pass 180-degree sinogram
    # for the finding method.
    center = tomopy.find_center_vo(
        np.expand_dims(sinogram[0:depth // 2 + 1: 5], 1), ncore=ncore)
    sinogram = -np.log(sinogram)
    rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", ncore=ncore)
    rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
    save_image("E:/Tomo_data/tomo/rec_image_before.tif", rec_image)

    # Find center at different height for calculating the tilt angle
    list_center = []
    for i in range(0, height, height // 2 - 1):
        print("Find center at slice {}".format(i))
        sinogram = (proj[0:depth // 2 + 1:5, i] - dark[i]) / (flat[i] - dark[i])
        center = tomopy.find_center_vo(np.expand_dims(sinogram, 1), ncore=ncore)
        print("Center is {}".format(center))
        list_center.append([i, center])
    list_center = np.asarray(list_center)
    # Find the tilt angle using linear fit
    tilt_angle = -np.rad2deg(np.arctan(np.polyfit(list_center[:, 0], list_center[:, 1], 1)[0]))
    print("Tilt angle: {}".format(tilt_angle))
    # tilt_angle = -0.5729386976835696

    # Generate tilted sinogram using algotom
    sino_tilted = corr.generate_tilted_sinogram(proj, idx, tilt_angle)
    flat_line = corr.generate_tilted_profile_line(flat, idx, tilt_angle)
    dark_line = corr.generate_tilted_profile_line(dark, idx, tilt_angle)
    sinogram = corr.flat_field_correction(sino_tilted, flat_line, dark_line)
    center = tomopy.find_center_vo(np.expand_dims(sinogram, 1), ncore=ncore)
    print("Center after tilt correction is {}".format(center))
    # save_image("E:/Tomo_data/tomo/sino_image.tif", sinogram)
    sinogram = -np.log(sinogram)
    rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", ncore=ncore)
    rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
    save_image("E:/Tomo_data/tomo/rec_image_after.tif", rec_image)
    print("Done!")
```
![before_after](https://user-images.githubusercontent.com/12136997/220759935-70a1480c-2126-45a8-a96d-f57814a25786.png)
This is just for the data you sent. To process original datasets (hdf format) in automated fashion you may want to refer an example [here](https://github.com/algotom/algotom/blob/master/examples/example_09_generate_tilted_sinogram.py).

**Comment by lucifer-dev-cyber** [comment]
Thank You @nghia-vo for you time and really thankfull and appricaite that you gave you precious time to fix my problem. Also Thanks @carterbox for your help.

@nghia-vo I don't have data in hdf format. My data is 3600 projecting tiff's and its huge (aroung 40 GB) do you have a way that I can share that.

**Comment by lucifer-dev-cyber** [comment]
@nghia-vo When I tried it with my data, this is what happens.

rec_image_before-
![Screenshot_48](https://user-images.githubusercontent.com/119943034/220955866-05848076-d21e-4c39-bd2b-2a392b53a4d6.jpg)


rec_image_after-
![Screenshot_49](https://user-images.githubusercontent.com/119943034/220956148-89e9e82d-9711-42f1-886d-ca870f18f0ce.jpg)

**Comment by nghia-vo** [comment]
You're welcome. Convert tifs to hdf make it easy to process sinogram-by-sinogram and allow to process large data using a small RAM computer. Check examples [here](https://algotom.readthedocs.io/en/latest/toc/section4/section4_4.html#for-cone-beam-tomography) and [here](https://algotom.readthedocs.io/en/latest/toc/section4/section4_4.html#for-cone-beam-tomography) to know how. 
From the data you sent, look like the tilt angle is incorrectly determined. What value did you get? Did you resize the data you sent (npy) compared to tif images? What is the original size of tif image (height x width)?. If you resize your data, you have to recalculate the tilt angle. Send me sinograms at the top, middle, and bottom to double check.

**Comment by lucifer-dev-cyber** [comment]
This is what I got.... it finds center as 632, 632 and 634. But after tited correction its says 658.

![Screenshot_50](https://user-images.githubusercontent.com/119943034/221197667-80141fc1-c204-4d4e-be31-3d3357ea5c12.jpg)

**Comment by nghia-vo** [comment]
Try by reversing the sign of the angle:
tilt_angle = -tilt_angle

**Comment by lucifer-dev-cyber** [comment]
Tried it... still the same.

![Screenshot_51](https://user-images.githubusercontent.com/119943034/221208192-65cede3f-b16d-4cc3-b299-5d639df74373.jpg)

**Comment by nghia-vo** [comment]
Hm, could you upload the sinograms before and after corrections to the same google drive above? I'll have a look.

**Comment by lucifer-dev-cyber** [comment]
Hi,

I am also trying the same with other sample which does'nt seem to work at all. I have shared npy array of that sample in my drive folder name 'al_sample'. I tried your code loading with this sample but does not give any reconstruction.

Also about your previous coment about sharing sinograms, I have shared the sinogrambefore and sinogramafter numpy array in the drive link above in tomo folder.

Thank You.

**Comment by nghia-vo** [comment]
I don't know what between your codes can cause the problem, but I got good results using the sinogram you sent:
---
Start......
Center of rotation before 632.25
Center of rotation after 633.0
Done!
---
```python
def load_image(file_path):
    try:
        mat = np.asarray(Image.open(file_path), dtype=np.float32)
    except IOError:
        print(("No such file or directory: {}").format(file_path))
        raise
    if len(mat.shape) > 2:
        axis_m = np.argmin(mat.shape)
        mat = np.mean(mat, axis=axis_m)
    return mat

def save_image(file_path, mat):
    image = Image.fromarray(mat)
    try:
        image.save(file_path)
    except IOError:
        print(("Couldn't write to file {}").format(file_path))
        raise
    return file_path


if __name__ == '__main__':
    print("Start......")
    sinogram = np.load("E:/Tomo_data/tomo/sinogrambefore.npy")
    ncore = mp.cpu_count() - 1
    (height, width) = sinogram.shape
    angles = np.linspace(0.0, 360.0, height) * np.pi / 180.0
    center = tomopy.find_center_vo(
        np.expand_dims(sinogram[0:height // 2 + 1: 5], 1), ncore=ncore)
    save_image("E:/Tomo_data/tomo/sino_before.tif", sinogram)
    print("Center of rotation before {}".format(center))
    nmean = np.mean(sinogram)
    sinogram[sinogram <=0.0] = nmean
    # sinogram = -np.log(sinogram)
    rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", ncore=ncore)
    rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
    save_image("E:/Tomo_data/tomo/rec_image_before.tif", rec_image)

    # After correction

    sinogram = np.load("E:/Tomo_data/tomo/sinogramafter.npy")
    save_image("E:/Tomo_data/tomo/sino_after.tif", sinogram)
    center = tomopy.find_center_vo(
        np.expand_dims(sinogram[0:height // 2 + 1: 5], 1), ncore=ncore)
    print("Center of rotation after {}".format(center))
    nmean = np.mean(sinogram)
    sinogram[sinogram <=0.0] = nmean
    # sinogram = -np.log(sinogram)
    rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", ncore=ncore)
    rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
    save_image("E:/Tomo_data/tomo/rec_image_after.tif", rec_image)
    print("Done!")
```
![Compare](https://user-images.githubusercontent.com/12136997/221652560-a4079aa4-c819-4a01-b081-a9acda68922d.jpg)

I can see in your sinograms there're values <=0. This will result black reconstructed image. You can fix that by this:
nmean = np.mean(sinogram)
sinogram[sinogram<= 0.0] = nmean

**Comment by lucifer-dev-cyber** [comment]
Thank You. I think there is something definately wrong from my side.

Can I request you try the al sample. Which I have shared on google drive. If it is possible. May be I can definately know whats going wrong on my side. Using this code-



import tomopy
import numpy as np
from PIL import Image
import multiprocessing as mp
import algotom.prep.correction as corr

def load_image(file_path):
    try:
        mat = np.asarray(Image.open(file_path), dtype=np.float32)
    except IOError:
        print(("No such file or directory: {}").format(file_path))
        raise
    if len(mat.shape) > 2:
        axis_m = np.argmin(mat.shape)
        mat = np.mean(mat, axis=axis_m)
    return mat

def save_image(file_path, mat):
    image = Image.fromarray(mat)
    try:
        image.save(file_path)
    except IOError:
        print(("Couldn't write to file {}").format(file_path))
        raise
    return file_path


if __name__ == '__main__':
    print("Start......")
    # Load data, note that the projections are in the range of 0-360 degree
    proj = np.load("E:/Tomo_data/tomo/proj.npy")
    flat = np.mean(np.load("E:/Tomo_data/tomo/flat.npy"), axis=0)
    dark = np.mean(np.load("E:/Tomo_data/tomo/dark.npy"), axis=0)
    ncore = mp.cpu_count() - 1
    (depth, height, width) = proj.shape
    angles = np.linspace(0.0, 360.0, depth) * np.pi / 180.0

    idx = 30
    # Before tilted correction
    sinogram = (proj[:, idx] - dark[idx]) / (flat[idx] - dark[idx])
    # Find center of rotation:
    # Reduce number of projections as 3600 projections are more than enough
    # for finding the center. Note that we need to pass 180-degree sinogram
    # for the finding method.
    center = tomopy.find_center_vo(
        np.expand_dims(sinogram[0:depth // 2 + 1: 5], 1), ncore=ncore)
    sinogram = -np.log(sinogram)
    rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", ncore=ncore)
    rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
    save_image("E:/Tomo_data/tomo/rec_image_before.tif", rec_image)

    # Find center at different height for calculating the tilt angle
    list_center = []
    for i in range(0, height, height // 2 - 1):
        print("Find center at slice {}".format(i))
        sinogram = (proj[0:depth // 2 + 1:5, i] - dark[i]) / (flat[i] - dark[i])
        center = tomopy.find_center_vo(np.expand_dims(sinogram, 1), ncore=ncore)
        print("Center is {}".format(center))
        list_center.append([i, center])
    list_center = np.asarray(list_center)
    # Find the tilt angle using linear fit
    tilt_angle = -np.rad2deg(np.arctan(np.polyfit(list_center[:, 0], list_center[:, 1], 1)[0]))
    print("Tilt angle: {}".format(tilt_angle))
    # tilt_angle = -0.5729386976835696

    # Generate tilted sinogram using algotom
    sino_tilted = corr.generate_tilted_sinogram(proj, idx, tilt_angle)
    flat_line = corr.generate_tilted_profile_line(flat, idx, tilt_angle)
    dark_line = corr.generate_tilted_profile_line(dark, idx, tilt_angle)
    sinogram = corr.flat_field_correction(sino_tilted, flat_line, dark_line)
    center = tomopy.find_center_vo(np.expand_dims(sinogram, 1), ncore=ncore)
    print("Center after tilt correction is {}".format(center))
    # save_image("E:/Tomo_data/tomo/sino_image.tif", sinogram)
    sinogram = -np.log(sinogram)
    rec_image = tomopy.recon(np.expand_dims(sinogram, 1), angles, center=center, algorithm="gridrec", ncore=ncore)
    rec_image = tomopy.circ_mask(rec_image, axis=0, ratio=1.0)[0]
    save_image("E:/Tomo_data/tomo/rec_image_after.tif", rec_image)
    print("Done!")

**Comment by nghia-vo** [comment]
That code is the same code from I sent you before and it worked. Your raw data is tiff as I understand. Are you sure it's the same code? One thing I can suggest is use tomopy.find_center_vo(np.expand_dims(sinogram, 1), ncore=1), set ncore=1 to check. If in the workflow you're using parallel processing on top of find_center_vo, it may return weird results. 
Out of that, I leave the fun of debugging codes to you, e.g. save intermediate output to tiff, print data shape,... It's good learning experience.
