### ISSUE TITLE
FileNotFoundError: Could not find module 'libtomopy-gridrec.dll' (or one of its dependencies). Try using the full path with constructor syntax. 

### ISSUE THREAD

**Issue by sgxx** [tomopy/tomopy#610]
FileNotFoundError: Could not find module 'libtomopy-gridrec.dll' (or one of its dependencies). Try using the full path with constructor syntax. 

How to resolve this problem?

**Comment by carterbox** [comment]
Please update to latest version of TomoPy and do not ignore the GitHub issue template. You have not provided any of the requested information that would help me solve your problem.
