### ISSUE TITLE
Reconstruction units using different algorithms

### ISSUE THREAD

**Issue by mahayusuf** [tomopy/tomopy#614]
I reconstructed my data using gridrec and using fbp. I am wondering if the units of my reconstructed images be in per cm, per mm, or per pixel? 

Thanks,
Maha

**Comment by mahayusuf** [comment]
My 2nd question is on the Algotom's filter. I used this filter on my sinograms (algotom.rec.reconstruction.apply_ramp_filter) and then reconstructed using the standard "fbp" algorithm in tomopy's reconstruction. 

Will the ramp filter change the units? 

link: https://algotom.readthedocs.io/en/latest/toc/api/algotom.rec.reconstruction.html#algotom.rec.reconstruction.apply_ramp_filter

**Comment by nghia-vo** [comment]
The unit is pixel. The question should be on algotom github page Maha.
