### ISSUE TITLE
OSError: libprep.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by decarlof** [tomopy/tomopy#62]
This error occurs when python is installed in a directory the username trying to install tomopy does not have write permission.

This is what happens:
pj0200% pwd
/local/decarlo/

pj0200% git clone https://github.com/tomopy/tomopy.git tomopy_repo_tomopy
pj0200% ln -s tomopy_repo_tomopy/ tomopy

pj0200% ls -l
lrwxrwxrwx  1 decarlo xsdxmi   18 Jan 17 13:33 tomopy -> tomopy_repo_tomopy/
drwxr-xr-x  9 decarlo xsdxmi 4096 Jan 17 13:37 tomopy_repo_tomopy/

pj0200% cd tomopy
pj0200% python install.py --boost --fftw /local/decarlo/tomopy/lib
 
Determining system setup
 -> changing to work directory... 
    /tmp/tmpnN2KOl
 -> determining platform...  Linux / 
 
Installing FFTW
 -> downloading
 -> expanding tarfile
 -> configuring
 -> making
 -> installing
 
Installing Boost C++
 -> downloading
 -> expanding tarfile
 -> configuring
 -> making
 -> installing
 
Installation successful!!!
 
Before you start installing TomoPy, don't forget to:
 
    1) Set LD_LIBRARY_PATH permanently in your shell to: /local/decarlo/tomopy/lib/lib
       hint: setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/local/decarlo/tomopy/lib/lib
 
    2) Set C_INCLUDE_PATH permanently in your shell to: /local/decarlo/tomopy/lib/include
       hint: setenv C_INCLUDE_PATH ${C_INCLUDE_PATH}:/local/decarlo/tomopy/lib/include

pj0200% env
LD_LIBRARY_PATH=/local/decarlo/tomopy/lib/lib
C_INCLUDE_PATH=/local/decarlo/tomopy/lib/include

pj0200% python -c "import tomopy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tomopy/__init__.py", line 22, in <module>
    import xtomo.xtomo_preprocess
  File "tomopy/xtomo/xtomo_preprocess.py", line 14, in <module>
    from tomopy.algorithms.preprocess.apply_padding import apply_padding
  File "tomopy/algorithms/preprocess/apply_padding.py", line 14, in <module>
    libprep = ctypes.CDLL(libpath)
  File "/APSshare/epd/rh6-x86_64/lib/python2.7/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /local/decarlo/tomopy_repo_tomopy/tomopy/lib/libprep.so: cannot open shared object file: No such file or directory

====================
Solution/Work around:
====================

pj0200% pwd
/local/decarlo/tomopy
pj0200% python setup.py build
pj0200% mkdir /local/decarlo/tomopy/tomopy/lib
pj0200% cp build/lib.linux-x86_64-2.7/tomopy/lib/*.so /local/decarlo/tomopy/tomopy/lib/
pj0200% python -c "import tomopy"
OK!

then to run tomopy from a different directory:
pj0200% python setup.py install --user 

Is possible to find something easier/simpler?

**Comment by dgursoy** [comment]
One can also put their script in the build directory, and run from there. Since there is no movement, it should be easier:

    % pwd 
    /local/tomopy
    % python setup.py build
    % cd build/lib.linux-x86_64-2.7
    % python -c "import tomopy"

**Comment by aglowacki** [comment]
You can also use PYTHONPATH environment variable

As the python documentation states : https://docs.python.org/2/using/cmdline.html

PYTHONPATH <https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH>
Augment the default search path for module files. The format is the same as the shell’s PATH: one or more directory pathnames separated by os.pathsep <https://docs.python.org/2/library/os.html#os.pathsep> (e.g. colons on Unix or semicolons on Windows). Non-existent directories are silently ignored.

In addition to normal directories, individual PYTHONPATH <https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH> entries may refer to zipfiles containing pure Python modules (in either source or compiled form). Extension modules cannot be imported from zipfiles.

The default search path is installation dependent, but generally begins with prefix/lib/pythonversion (see PYTHONHOME <https://docs.python.org/2/using/cmdline.html#envvar-PYTHONHOME> above). It is always appended to PYTHONPATH <https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH>.

An additional directory will be inserted in the search path in front of PYTHONPATH <https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH> as described above under Interface options <https://docs.python.org/2/using/cmdline.html#using-on-interface-options>. The search path can be manipulated from within a Python program as the variable sys.path <https://docs.python.org/2/library/sys.html#sys.path>.


So if you set PYTHONPATH to where to tomopy build is then you should be able to import tomopy. 
You can either add it to your .bashrc or make a separate shell script to set it and run python after.

**Comment by prjemian** [comment]
This is the recommended way to do it.

On 1/22/2015 9:46 AM, aglowacki wrote:
> make a separate shell script to set (a custom PYTHONPATH) and run python after.

By defining (a custom PYTHONPATH) as the default in ~/.bashrc, other 
python software started from the command line could have problems.

Pete

**Comment by decarlof** [comment]
great! thanks for your input
