### ISSUE TITLE
retrieve_phase Paganin filter

### ISSUE THREAD

**Issue by valentinaalb** [tomopy/tomopy#620]
Can someone please clarify if the "regularization parameter alpha" in the retrieve_phase filter actually corresponds to the delta/beta ratio?
This question is valid for the phase.py code previous the correction (2021), as well as for the corrected version. 
My hypothesis is that alpha corresponds to the inverse ratio: alpha=beta/delta.
Thank you in advance

**Comment by dkazanc** [comment]
Hi, I think in the [current](https://github.com/tomopy/tomopy/blob/32b64972b89b926015b6b47c121a8d63a6f47ae9/source/tomopy/prep/phase.py#L192C1-L192C1) TomoPy implementation, the parameter `alpha` is a regularisation (smoothing) parameter. See, for instance, this implementation [here](https://github.com/jbforien/phaseCT/blob/2edb0e65fca02bf0f0a263bb44c1a32830306747/c_phaseRetrieval_v3.py#L84) where `alpha` is a separate entity and the ratio of `(delta/beta)` is also present. 

The implementation in TomoPy is not strictly correct and it has been raised before in this [PR](https://github.com/tomopy/tomopy/pull/547) where these changes were [requested](https://github.com/tomopy/tomopy/pull/547/files). I, however, also not sure that these are correct either as `alpha` (regularisation) has been turned into the `delta/beta` ratio. But they do follow the original Paganin formula. 
It looks like we're talking about two versions here, the one (unregularised) simply uses `delta/beta` ratio and another one adds regularisation parameter `alpha` into the denominator. As in the code before for the regularised version it stated:
```
    Phase retrieval method based on Contrast Transfer Function. This 
    method relies on linearization of the direct problem, based  on  the
    first  order  Taylor expansion of the transmittance function.
    Found in Yu et al. 2018 and adapted from Cloetens et al. 1999
```
I'm not an expert in this, so I'm trying to make sense as well :)
