### ISSUE TITLE
tomo-recon

### ISSUE THREAD

**Issue by HosRahimi** [tomopy/tomopy#621]
i install tomopy with pip.
then i import it and see this error :
TomoPy links to compiled components which are installed separately and loaded using ctypes.util.find_library(). A required library, tomo-recon, was not found.
![Capture](https://github.com/tomopy/tomopy/assets/141782552/6a900080-f3df-47e7-a824-f537513c1dd7)

**Comment by carterbox** [comment]
Please read our installation directions on our documentation page. https://tomopy.readthedocs.io/en/stable/install.html

**Comment by HosRahimi** [comment]
I do that. 
![Capture1](https://github.com/tomopy/tomopy/assets/141782552/07a87d7b-6cbf-4c44-ad39-5c957dd45282)
again return same error

**Comment by ercius** [comment]
It looks like you are using Google Colab as your notebook environment. I dont think conda works the way you are using it in this case. Take a look at [condacolab](https://github.com/conda-incubator/condacolab). After installation of condacolab in the first notebook cell, I got tomopy working in Colab with this line:
`!mamba install -c conda-forge tomopy`

You can also look at this Colab [example notebook](https://colab.research.google.com/drive/1c_RGCgQeLHVXlF44LyOFjfUW32CmG6BP#scrollTo=WVrfw3Ir0gwL)
