### ISSUE TITLE
How to obtain 3D data projection of specific directional angle and pitch angle

### ISSUE THREAD

**Issue by cailijing** [tomopy/tomopy#633]
How to obtain 3D data projection of specific directional angle and pitch angle

Hello, I want to observe a 3D data in the direction of azimuth angle theta and pitch angle phi, for obtaining its system matrix and projected signal. How can I implement this? 

Thank you

**Comment by cailijing** [comment]
> TomoPy does not support laminography. i.e. the rotation axis in our projection operator is always perpendicular to the projection axis.
> 
> Our projection operator is available as a funcion. https://tomopy.readthedocs.io/en/stable/api/tomopy.sim.project.html#tomopy.sim.project.project

Why TomoPy does not support chromatography? Is it because the library is mainly used for reconstruction?
The rotation axis in our projection operator is always perpendicular to the projection axis, does this mean that the pitch angle is not supported?

**Comment by carterbox** [comment]
TomoPy only supports 2D parallel beam tomography. The reason is that the main contributors / developers are all employees at synchrotron light sources where the beam divergence is very small.

**Comment by cailijing** [comment]
OK. Thank you.
