### ISSUE TITLE
scipy.interp2d is deprecated and will be removed

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#635]
**Describe the problem**

Tests now emit the following deprecation warning from SciPy
```
/usr/share/miniconda/envs/tomopy/lib/python3.12/site-packages/tomopy/prep/stripe.py:826: DeprecationWarning: `interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.14.0.
  
  For legacy code, nearly bug-for-bug compatible replacements are
  `RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
  scattered 2D data.
  
  In new code, for regular grids use `RegularGridInterpolator` instead.
  For scattered data, prefer `LinearNDInterpolator` or
  `CloughTocher2DInterpolator`.
  
  For more details see
  `[https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html`](https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html%60)
  
    finter = interpolate.interp2d(listx, listy, matz, kind='linear')
```

The stripe removal methods need to be transitioned to the newer SciPy APIs, so they don't break.

**TODOs**
- [x] Guard against breaks by setting upper limit on scipy compatabilty to <1.14.0 #636 
- [x] Transition functions to new interpolation API and set new minimum scipy compatibility #637

**Comment by carterbox** [comment]
@nghia-vo, have you noticed this warning? Do you already have a plan to transition these methods to the new interpolators?

**Comment by nghia-vo** [comment]
Will do very soon Daniel.
