### ISSUE TITLE
nthread error 

### ISSUE THREAD

**Issue by Jae-yong-Shin** [tomopy/tomopy#638]
Hello,

While verifying the test code operation, an error appeared as shown in the figure below. I checked the previous issue #576, but it did not work.
![image](https://github.com/tomopy/tomopy/assets/145250428/af041180-50fb-4013-aac3-6e34b808e88b)

Interestingly, despite the error, the results could be seen as below.
![image](https://github.com/tomopy/tomopy/assets/145250428/86b999d4-7fab-4e41-b0d9-81fa1c2031a1)

When the 'ncore=1' option is provided, 'normalize' and 'minus log' do not generate an error code, but unfortunately, 'find_center' does not accept the ncore option, thus inevitably generating an error code. What could be causing these error codes? Could you provide a solution to this issue?
![image](https://github.com/tomopy/tomopy/assets/145250428/ef6d3ee6-cbba-4fd7-848b-9638f1df5cce)

Please let me know if you need any information to solve the problem. I will respond immediately.

**Comment by carterbox** [comment]
When you opened this issue, there was a template provided for you. You have not included any information about what platform, tomopy, or python version you are using.

In addtion, to the platform, tomopy version, and python version. Please provide the version of numexpr that you are using and the output of `multiprocessing.cpu_count()` from the standard library.

**Comment by Jae-yong-Shin** [comment]
I just checked the template you mentioned. I didn't notice it before, sorry about that. The information you requested is as follows. Thank you.

Platform Information:

OS: Ubuntu 22.04
Python Version: 3.10.13
TomoPy Version: 1.14.1
### 
Numexpr Version: 2.8.7

![image](https://github.com/tomopy/tomopy/assets/145250428/3a66f2e9-92dc-49a3-88ff-94b88a74d52d)

**Comment by carterbox** [comment]
The number of cores on your system is 112. As the error says, NUMEXPR_MAX_THREADS is set to 64, so you should set NUMEXPR_MAX_THREADS to some number higher than 112.

**Comment by Jae-yong-Shin** [comment]
Thank you!
export NUMEXPR_MAX_THREADS=112
The issue is solved.
