### ISSUE TITLE
Tomopy update to support numpy>=1.20

### ISSUE THREAD

**Issue by mittoalb** [tomopy/tomopy#639]
Hello,

I recently installed TomoPy on a RHEL9 machine. 

Currently I can run correctly the code using:
python3.7.12 and numpy==1.18.0

If i try to use a newer version of numpy and python I start to get errors due to deprecated functions of numpy (example numpy.int -> int).
I would be nice to update the code in order to support newer version of python/numpy also for a better compatibility with other libraries.
Thank you

**Comment by carterbox** [comment]
Please use the bug report template to report any deprecation warnings not the feature request template. There is not enough information in your report to do any debugging or to try and replicate the error that you are reporting.
