### ISSUE TITLE
XTomoDataset instance has no attribute 'remove_gaussian_background'

### ISSUE THREAD

**Issue by smjorgensen** [tomopy/tomopy#64]
I'm pretty new to python, new to Canopy and I've managed to get tomopy installed (finally!) and I'm getting this error when I run the same script that I ran while I was on the system at APS 2BM.  Any suggestions?

    77     d.gridrec()
     78 
---> 79     d.remove_gaussian_background(sigma=15)
     80     tomopy.xtomo_writer(d.data_recon[np.int(margin_slices/2):(SliceEnd-SliceStart-np.int(margin_slices/2)),:,:], output_file, axis=0,x_start=SliceStart+np.int(margin_slices/2),overwrite = True)
     81     d.FLAG_THETA = False

AttributeError: XTomoDataset instance has no attribute 'remove_gaussian_background' 

I'm also getting a warning:
"dark-field assumed as zeros [ok]"
even though when I inspect the  dark array it is 6 x 150 x 2016 and has non-zero values when displayed.

**Comment by xianghuix** [comment]
remove_gaussian_background is one routine I made for the beamline installation. It is not included in tomopy release yet.

Xianghui
________________________________

**Comment by smjorgensen** [comment]
Hi Xianghuix,
Thanks for the reply, I'll just comment it out of the script for now.
Steve

**Comment by dgursoy** [comment]
By default, dark field data should be located at ```exchange/data_dark``` in your HDF5 file. If not it should be manually imported. What is your input data format and group name for dark field, HDF4 or HDF5? You can use HDFView to look into groups in your dataset.

**Comment by xianghuix** [comment]
You are right. You just need to comment out that line.

Xianghui
________________________________

**Comment by smjorgensen** [comment]
Doga, 
Thanks for the reply.
The dataset is HDF5.  In HDFview it shows dark_data under exchange, with dark_data properties size: 10x1600x2016.  The dimensions if dark I mentioned above (6x150,2016) were obtained by applying the shape(dark) command in ipython after the exception generated by the 'remove_gaussian_background' error.  Upon close inspection of the .xtomo_reader parameters, the 6x150x2016 makes sense, as the read parameters in the script are coded to restrict the read to that size. Perhaps the limit on the size of the read causes the "dark-field assumed zero" warning?
If I display the data in the variable dark, it looks like a reasonable dark image.

**Comment by smjorgensen** [comment]
Here is the data read and call to d.dataset (d=tomopy.xtomo_dataset(log='debug'), where dark has been replaced by None for some reason.  Perhaps that is why the warning is issued!  Why were we ignoring the dark fields? (or was this just an oversight from debugging?)

data, white, dark, theta = tomopy.xtomo_reader(file_name,slices_start=SliceStart,slices_end=SliceEnd,white_start=3,white_end=9,dark_start=3,dark_end=9)
    data[0,:,:] = data[1,:,:]
    d.dataset(data, white, None, theta)

**Comment by xianghuix** [comment]
Hi Steve,

    you can replace None with dark. There was some problem with dark image in the first data set so I ignore dark. It does not make visible difference if you compare the reconstruction with and without dark correction.

Xianghui
________________________________

**Comment by smjorgensen** [comment]
Hi Xianghui,
Ok, great.  Thanks for the information.

Steve

Steven M. Jorgensen
Engineer - Micro-CT System Lead
Physiology and Biomedical Engineering
Mayo Clinic College of Medicine
Phone: 507-255-1930 (voice/voice mail)
Fax: 507-255-1935
Pager: 507-284-6721
Email: smj@mayo.edu<mailto:smj@mayo.edu>
___________________________________________
Mayo Clinic
200 First Street SW Rochester, MN 55905
mayoclinic.org

**Comment by decarlof** [comment]
it looks something is wrong with the data set ...
Xianghui: is this data set still at the APS? if so can you give me the link? 
If not: Steve can you upload it to 

ftp ftp.xray.aps.anl.gov
Name (ftp.xray.aps.anl.gov:): anonymous
Password: enter your e-mail address
ftp> cd incoming/tomo/2bm

thanks
f

**Comment by smjorgensen** [comment]
Hi Francesco,

I think the dataset is ok, as I think I’ve figured out my questions, based closer examination of the recon script I’m running and the hdf5 file format.  (Thanks to all of you who had suggestions!)
In looking at cross-section plots (intensity profile)  (line-plot in hdfViewer) of the dark and white fields, there are a few frames at the beginning of the acquisition of those sets that need to be excluded due to corruption, but other than that, images are ok, I believe.  I can handily deal with excluding the ‘bad’ images.

Still, I’m interested in your assessment that ‘something is wrong with the data set’ as I’m very new to this and could easily be overlooking something!

I’ll be glad to upload the dataset tomorrow. (my initial attempts this evening didn’t work out, I could create folders by not rename them, so there are a couple of New Folder entries out there that are empty, sorry!)

Thanks very much for your interest!

Steve

Steven M. Jorgensen
Engineer - Micro-CT System Lead
Physiology and Biomedical Engineering
Mayo Clinic College of Medicine
Phone: 507-255-1930 (voice/voice mail)
Fax: 507-255-1935
Pager: 507-284-6721
Email: smj@mayo.edu<mailto:smj@mayo.edu>
___________________________________________
Mayo Clinic
200 First Street SW Rochester, MN 55905
mayoclinic.org

**Comment by xianghuix** [comment]
Nothing is wrong with Steve bring-home data. The warning was due to 'None' in place of actual dark in xtomo initiation command. Changing None to dark will solve the problem

Xianghui

On Jan 19, 2015 5:24 PM, Francesco De Carlo <notifications@github.com> wrote:

it looks something is wrong with the data set ...
Xianghui: is this data set still at the APS? if so can you give me the link?
If not: Steve can you upload it to

ftp ftp.xray.aps.anl.gov
Name (ftp.xray.aps.anl.gov:): anonymous
Password: enter your e-mail address
ftp> cd incoming/tomo/2bm

thanks
f
