### ISSUE TITLE
How to export 3D mesh

### ISSUE THREAD

**Issue by darkworks** [tomopy/tomopy#642]
**Describe the problem**
I want to reconstruct 3D mesh and export it to dxf or stl etc from tiff files. I had captured  X-ray images of PCB BGA socket via scanner from various angles.  I have total 60 tiff images. so am wondering how to reconstruct 3d mesh properly and export it to dxf or stl. so that can be viewed in 3d programs. I know dragonfly like programs can be used to generate 3d mesh but its commercial so i wonder something like dragonfly we can do here in opensource world or not
 
Sample code
```py
import tomopy
import numpy as np
import dxchange
import matplotlib.pyplot as plt
from mayavi import mlab

# Set the file path and file prefix
file_path = '/home/techsys/Downloads/20240417_123930_bga_test_60proj/tif/'
file_prefix = ''

# Set the number of TIF files
num_files = 60

# Create a list of indices for the files to read
ind = list(range(1, num_files + 1))

# Read the TIF files into a 3D array
tif_files = [file_path + file_prefix + '{:02d}.tif'.format(i) for i in ind]
data = dxchange.reader.read_tiff_stack(tif_files[0], ind=ind)
data.shape, data.min(), data.max()

# compute angle
theta = tomopy.angles(data.shape[0], 0, 360)

# Find the rotation centre
rot_center = tomopy.find_center_vo(data)

# Reconstruct the 3D volume
recon = tomopy.recon(data, theta, center=rot_center, algorithm='gridrec')

# Save and Visualize 3d mesh
# How to save it to dxf or stl ? any tomopy call ?
```

images 

![image](https://github.com/tomopy/tomopy/assets/12841788/89ed8e06-4454-42b6-b1bd-b32fe1262742)

**Comment by carterbox** [comment]
TomoPy does not have any visualization or mesh processing algorithms. It is a tomography reconstruction library only, so these capabilities are out of the scope of this project.

Look for implementations (elsewhere) of the [marching cubes algorithm](https://en.wikipedia.org/wiki/Marching_cubes) to convert your data from a dense volume to sparse surface mesh.
