### ISSUE TITLE
Stripe Removal Information Request

### ISSUE THREAD

**Issue by smjorgensen** [tomopy/tomopy#67]
Is there a reference available which describes the level, sigma and wname parameters?

For example: 
For stripe_removal:
level - reasonable range (n to m); effect of range variation; tradeoffs (i.e. noise vs. blur vs. processing speed)
sigma - resonable range (p to q); effect of range variation; tradeoffs
wname - wavelet filter type - ? options and effects, etc. as above.

Also compare and contrast stripe_removal with stripe_removal2 (and it's parameters "Number of Blocks and alpha (damping factor)?

Thanks very much,

Steve J.

**Comment by dgursoy** [comment]
Hi Steve, you can find more information on parameters in the referenced papers. Please refer to the references in docs:
http://tomopy.github.io/tomopy/resources/tomopy.algorithms.preprocess.stripe_removal.html
http://tomopy.github.io/tomopy/resources/tomopy.algorithms.preprocess.stripe_removal2.html

**Comment by smjorgensen** [comment]
Hi Doga,

Thank you for the reference paper links and all of your work on this project!

Steve

Steven M. Jorgensen
Engineer - Micro-CT System Lead
Physiology and Biomedical Engineering
Mayo Clinic College of Medicine
Phone: 507-255-1930 (voice/voice mail)
Fax: 507-255-1935
Pager: 507-284-6721
Email: smj@mayo.edu<mailto:smj@mayo.edu>
___________________________________________
Mayo Clinic
200 First Street SW Rochester, MN 55905
mayoclinic.org
