### ISSUE TITLE
setting the number of processes to use

### ISSUE THREAD

**Issue by mhagdorn** [tomopy/tomopy#77]
Hi there,
I am struggling with the new release - 0.1.1, is there an example workflow for how to use it? It seems to be quite different to the previous version.

At some stage, I would like to be able to restrict the number of processes a tomopy program uses. I see that the distribute_jobs takes the number of cores as a keyword argument. However, this is not used where distribute_jobs is called. Is that feature not plumbed in?

Regards
magnus

**Comment by dgursoy** [comment]
Hi Magnus - This is still in beta (Gridrec is not parallel for example) so for HPC applications I would still use the code at the legacy branch. In this version we try to make things simpler. An illustrative example would be something like:
```
>>> import tomopy
>>> import numpy as np
>>> obj = tomopy.shepp3d() # create a 3D phantom
>>> ang = np.linspace(0, np.pi, 180) # define projection angles in radian
>>> sim = tomopy.simulate(obj, ang) # generate simulated projection data
>>> rec = tomopy.art(sim, ang) # reconstruct object from simulated data using art (could as well be gridrec)
>>> tomopy.Writer(rec, fname='tmp/rec.tiff').tiff() # write reconstruction to a stack of tiff files
```

**Comment by dgursoy** [comment]
After #78 you can use ``ncore`` and ``nchunk`` arguments to restrict the number of processes and the size of the processing blocks for almost all functions.
