### ISSUE TITLE
Gridrec results inconsistent with legacy version.

### ISSUE THREAD

**Issue by celiafish** [tomopy/tomopy#79]
I used the data.h5 in demo of legacy version to perform the following test.
```
In [5]: import tomopy
In [6]: data, white, dark = tomopy.read_aps_2bm("data.h5") 
In [7]: norm_data = tomopy.normalize(data, white, dark)
In [8]: corr_norm_data = tomopy.correct_air(norm_data)
In [9]: retr_data = tomopy.retrieve_phase(corr_norm_data)
In [10]: corr_retr_data = tomopy.correct_air(retr_data )  
In [11]: import numpy as np
In [12]: theta = np.linspace(0, np.pi, data.shape[0])
In [13]: recon = tomopy.gridrec( corr_retr_data , theta)
In [15]: tomopy.Writer(recon, fname="tmp2/gr.tiff").tiff()
```
This test is based on 0.1.1 version. But I don't think the latest release changed the algorithm. 
Here is the result:
![image](https://cloud.githubusercontent.com/assets/4246579/7306764/b82fb012-e9d5-11e4-801f-521a1749d894.png)

The outside structure should be a complete circle. And it should be white. 
Did I do something wrong? Thanks.

**Comment by dgursoy** [comment]
You should specify ``center`` in line 13, otherwise it uses the middle point in your detector array as the rotation center. Additionally you should mention if these measurements are transmission or emission type using the ``emission`` argument (Note that ``emission`` is by default ``True``).
```
>>> recon = tomopy.gridrec(corr_retr_data , theta, center=662.5, emission=False)
```

**Comment by celiafish** [comment]
The ```center``` issue was solved. But the circle is still not white. 
![image](https://cloud.githubusercontent.com/assets/4246579/7307278/bb706f10-e9d9-11e4-9ffe-753a1fa0442d.png)

**Comment by dgursoy** [comment]
Can you try with 0.1.2? I ran the exact script above and I could get the correct phase values.

**Comment by celiafish** [comment]
It worked well with 0.1.4. Thanks.
