### ISSUE TITLE
number of cores are not set

### ISSUE THREAD

**Issue by mhagdorn** [tomopy/tomopy#80]
with the latest tomopy I can set the number of processes, but this number is not used when the pool is setup. I think this patch should do the trick:
https://gist.github.com/mhagdorn/c9a1b98a8241f7dd389c

**Comment by dgursoy** [comment]
You are right. Also  gridrec chunksize shouldn't be smaller than two, because unlike other algorithms, it reconstructs even number of slices. I'll add these corrections. Thanks Magnus!

**Comment by dgursoy** [comment]
Corrected in #81.
