### ISSUE TITLE
bunch issues

### ISSUE THREAD

**Issue by xianghuix** [tomopy/tomopy#91]
1. gridrec should have ringWidth option as in the past
2. tomopy.recon.rotation.write_center does not seem behave correctly. it should stop after saving trial reconstruction images. it however keeps doing something, probably repeating trial reconstruction again and again, after the first round is finished.
3. in the old version tomopy, logarithm of the normalized data was done implicitly in gridrec routine. is this still same in the current version? If it is, is there a scale factor implicitly used in gridrec routine before the logarithm operation?
4. current output is different from that with old version tomopy. first after 'normalize', the output are float in [0,1]. with old version tomopy, the output was rescaled integer in [0, 10000]. second, the reconstruction with phase retrieval has grayvalues in sample region smaller than the background. this is also opposite from that with old version. 

Thanks,

Xianghui

**Comment by dgursoy** [comment]
Thanks Xianghui. Here's my comments and action plan:
  1.  ``ringWidth`` argument in Mark's implementation was used to correct for the rings. So, I will put it under stripe removal module as a new function.
  2. I'll check that and get back to you.
  3. The ``emission`` argument is now used to identify either the measurement is from an emission (XFM, XDT, etc.) or from an transmission (micro-CT, etc.) mode. Default is ``True``. So for transmission CT you need to explicitly specify ``emission=False`` as an input to the ``recon`` function. 
  4. I am not sure about this. I thought we were converting data to ``float32`` at the beginning in the old version, and continue to work on ``float32`` data. I also didn't changed the algorithm for phase retrieval. I'll check that either.
  5. In this version ``gridrec`` automatically pads sinogram to the next power of two before performing reconstruction. I will make this optional then. There is also an additional function called ``pad`` in ``tomopy.misc.morph`` that can be used to pad volumes along specified axes.

**Comment by xianghuix** [comment]
I did the testings with emission=False. I actually change the default setting of emission to 'False' in write_center. for accurate comparison I need to find another computer that has old version tomopy installed. I might be wrong with padding issue.

**Comment by xianghuix** [comment]
I did some testing with both old version and current version tomopy. My observations of normalization and contrast inversion are wrong. The old version normalize is basically same as the current normalize. The flipping contrast was due to some extra operation in my testing code with current tomopy. The current recon with gridrec is different from that with old version but it does not seem causing significant difference. The border of a slice in a truncated sample case is much brigher than that with old tomopy. I guess the difference might be due to the different padding scheme. zero-padding was used in old version tomopy. current tomopy does not have user options to turn on/off padding and how to pad. 

the tiff writer in new tomopy saves images rotated 90deg ccw from the tiff writer used in old tomopy. personally I like the image orientation with old tomopy tiff writer.

**Comment by dgursoy** [comment]
This border effect is probably due to removed preprocessing function from Mark's ``tomoRecon`` package. In the old version the default value for ``airPixels`` was ``10``, so I assume it was making some corrections before reconstruction at the border. But you can now use ``normalize_bg`` just before running ``recon``. This should remove this brightness problem at the edge. 

Yes now it is writing I guess counter clockwise and with 90 degree tilt to have a standard among all reconstruction methods. It is not the tiff writer but I modified the indexes in ``gridrec``. Is there a particular reason that you prefer the old version? Because this one seemed more natural from computational point of view.

**Comment by xianghuix** [comment]
for using write_center, it seems more convenient to find structure change with the old orientation. this could be due to taht I am used to the old way.

I would suggest to add more kwargs to gridrec so we can tweak its behaviors with full flexibility. At this point, I can think 'ringWidth', 'pad', 'padding_size', 'airPixels'

**Comment by dgursoy** [comment]
The utility functions are now separate from gridrec. For example, you can use ``pad`` function to do all padding stuff. ``normalize_bg`` is for to normalize data without white or dark fields just by looking at the boundary pixels of the sinogram (which is the ``air`` region for many cases). But, thanks for reminding the  tomoRecon's ring correction. It is the only missing functionality I think and we will have it hopefully soon.

**Comment by tomopy** [comment]
Opening a new thread for the implementation of ring removal in tomorecon.
